# generated by datamodel-codegen:
#   filename:  session-directional-base.yaml

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.native import PydanticCodec


codec_0: Final[PydanticCodec[models.UserRequest]] = PydanticCodec(models.UserRequest)
"""Codec of /paths/~1users/post request_body (request application/json)."""

codec_1: Final[PydanticCodec[models.UserResponse]] = PydanticCodec(models.UserResponse)
"""Codec of /paths/~1users/post response_body (response 201 application/json)."""
