# generated by datamodel-codegen:
#   filename:  encoding.json

from __future__ import annotations
from pydantic.dataclasses import dataclass



@dataclass
class Filter:
    value: str | None = None



@dataclass
class Model:
    value: str | None = None