# generated by datamodel-codegen:
#   filename:  encoding.json

from __future__ import annotations
from typing_extensions import NotRequired
from typing import TypeAlias, TypedDict



class Model(TypedDict):
    value: NotRequired[str]



FieldValuesPostRequestValueXPartEncodingHeader: TypeAlias = str