# generated by datamodel-codegen:
#   filename:  encoding.json

from __future__ import annotations
from pydantic import BaseModel, RootModel


class Model(BaseModel):
    value: str | None = None


class FieldValuesPostRequestValueXPartEncodingHeader(RootModel[str]):
    root: str