# Generated by datamodel-code-generator; target=client; schema_version=1
"""Verify the deliveries of one webhook helper with the caller's verifier, then decode their events.

The helper is adapted.plain, whose deliveries are verified by the Verifier the caller
passes, which must authenticate the whole raw body and every fact it returns.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Final, TypeVar

from models import Message as _dcg_type_0

from ..._generated import model_bindings
from ..._runtime.protocols.adapters import AdapterPlan, averify_adapted, verify_adapted
from ..._runtime.protocols.webhook_events import EventDecoder
from ..._runtime.protocols.webhooks import (
    AsyncReplayStore,
    KeySet,
    ReplayStore,
    VerifiedWebhook,
    Verifier,
    WebhookOptions,
)

__all__ = ["verify", "verify_async"]


K = TypeVar("K")


_PLAN: Final[AdapterPlan[_dcg_type_0]] = AdapterPlan(
    helper_id='adapted.plain',
    fingerprint='599bbad08283673d538acfedcefe3b91358b1bff901d889c5fb13f45fb5efaaf',
    timestamp=False,
    delivery_id=False,
    event=EventDecoder(
        model_bindings.codec_2,
        model_bindings.CONTEXT_2,
        validate=False,
    ),
    duplicates='reject',
)


def verify(
    raw_body: bytes,
    headers: Sequence[tuple[str, str]],
    keys: KeySet[K],
    *,
    verifier: Verifier[K],
    now: datetime,
    replay_store: ReplayStore | None = None,
    options: WebhookOptions | None = None,
) -> VerifiedWebhook[_dcg_type_0]:
    """Verify a delivery with verifier and decode its event, claiming it in a store.

    The verifier is called once, synchronously in both functions, and must authenticate
    the whole raw body and every fact it returns; a result that is not a
    VerifiedSignature, lacks a fact this helper requires, returns one it does not
    declare, or has a naive timestamp raises AdapterContractError before decoding. This
    webhook has no timestamp, so replay protection has no time window: a replay store
    keeps a claim for replay_ttl after now. Duplicates are detected only until the claim
    expires. The claim is made after decoding, before your code processes the event: if
    processing then fails, a retried delivery is a duplicate, or rejected under
    duplicates: reject, until the claim expires, so make processing durable or
    idempotent before acknowledging, or use a store whose claims you can release.
    Without a replay store, duplicate=False does not mean the delivery is new.
    """
    return verify_adapted(
        _PLAN,
        raw_body,
        headers,
        keys,
        verifier=verifier,
        now=now,
        replay_store=replay_store,
        options=options,
    )


async def verify_async(
    raw_body: bytes,
    headers: Sequence[tuple[str, str]],
    keys: KeySet[K],
    *,
    verifier: Verifier[K],
    now: datetime,
    replay_store: AsyncReplayStore | None = None,
    options: WebhookOptions | None = None,
) -> VerifiedWebhook[_dcg_type_0]:
    """Verify a delivery with verifier and decode its event, claiming it in an asyncio store.

    The verifier is called once, synchronously in both functions, and must authenticate
    the whole raw body and every fact it returns; a result that is not a
    VerifiedSignature, lacks a fact this helper requires, returns one it does not
    declare, or has a naive timestamp raises AdapterContractError before decoding. This
    webhook has no timestamp, so replay protection has no time window: a replay store
    keeps a claim for replay_ttl after now. Duplicates are detected only until the claim
    expires. The claim is made after decoding, before your code processes the event: if
    processing then fails, a retried delivery is a duplicate, or rejected under
    duplicates: reject, until the claim expires, so make processing durable or
    idempotent before acknowledging, or use a store whose claims you can release.
    Without a replay store, duplicate=False does not mean the delivery is new.
    """
    return await averify_adapted(
        _PLAN,
        raw_body,
        headers,
        keys,
        verifier=verifier,
        now=now,
        replay_store=replay_store,
        options=options,
    )
