# generated by datamodel-codegen:
#   filename:  session-directional-producers.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.native import PydanticCodec


codec_0: Final[PydanticCodec[models.ARequest]] = PydanticCodec(models.ARequest)
"""Codec of /paths/~1a/post request_body (request application/json)."""

codec_1: Final[PydanticCodec[models.AResponse]] = PydanticCodec(models.AResponse)
"""Codec of /paths/~1a/post response_body (response 200 application/json)."""

codec_2: Final[PydanticCodec[models.BRequest]] = PydanticCodec(models.BRequest)
"""Codec of /paths/~1b/post request_body (request application/json)."""

codec_3: Final[PydanticCodec[models.BResponse]] = PydanticCodec(models.BResponse)
"""Codec of /paths/~1b/post response_body (response 200 application/json)."""

codec_4: Final[PydanticCodec[models.Array]] = PydanticCodec(models.Array)
"""Codec of /paths/~1array/post request_body (request application/json)."""

codec_5: Final[PydanticCodec[models.Array]] = PydanticCodec(models.Array)
"""Codec of /paths/~1array/post response_body (response 200 application/json)."""

codec_6: Final[PydanticCodec[models.ChildRequest]] = PydanticCodec(models.ChildRequest)
"""Codec of /paths/~1child/post request_body (request application/json)."""

codec_7: Final[PydanticCodec[models.ChildResponse]] = PydanticCodec(models.ChildResponse)
"""Codec of /paths/~1child/post response_body (response 200 application/json)."""
