# Generated by datamodel-code-generator; target=client; schema_version=1
"""The synchronous protocol helpers of this package, by their dotted names."""

from __future__ import annotations

from functools import cached_property

from models import Note as _dcg_type_0

from .._runtime.client.client import ClientCore
from .._runtime.protocols.pagination import (
    Page,
    Pager,
    first_page,
    following_page,
    iterate_pages,
    resume_pages,
)
from .._runtime.protocols.resume import ResumeState
from .._runtime.protocols.streams import EventStream, open_events
from ..options import UNSET, RequestOptions, SessionOptions, Unset
from ..types.notes import ListNotesResponse
from . import PaginationOptions, StreamOptions, _plans


class ProtocolHelpers:
    """The protocol helpers of this API."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core its helpers send through."""
        self._core = core

    @cached_property
    def notes(self) -> NotesProtocols:
        """The notes protocol helpers."""
        return NotesProtocols(self._core)


class NotesProtocols:
    """The notes protocol helpers."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core its helpers send through."""
        self._core = core

    @cached_property
    def all(self) -> NotesAllPagination:
        """The notes.all pagination helper."""
        return NotesAllPagination(self._core)

    @cached_property
    def watch(self) -> NotesWatchSse:
        """The notes.watch SSE helper."""
        return NotesWatchSse(self._core)


class NotesAllPagination:
    """The notes.all pagination helper of GET /notes."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the helper sends through."""
        self._core = core

    def page(
        self,
        *,
        cursor: str | Unset = UNSET,
        pagination_options: PaginationOptions | None = None,
        options: RequestOptions | None = None,
        session_options: SessionOptions | None = None,
    ) -> Page[_dcg_type_0, ListNotesResponse]:
        """Fetch the first page of GET /notes."""
        return first_page(
            self._core,
            _plans.PLAN_0,
            (cursor,),
            pagination_options=pagination_options,
            options=options,
            session_options=session_options,
        )

    def iterate(
        self,
        *,
        cursor: str | Unset = UNSET,
        pagination_options: PaginationOptions | None = None,
        options: RequestOptions | None = None,
        session_options: SessionOptions | None = None,
    ) -> Pager[_dcg_type_0, ListNotesResponse]:
        """Return a pager over the items of GET /notes; it sends nothing until it is iterated."""
        return iterate_pages(
            self._core,
            _plans.PLAN_0,
            (cursor,),
            pagination_options=pagination_options,
            options=options,
            session_options=session_options,
        )

    def next_page(
        self,
        page: Page[_dcg_type_0, ListNotesResponse],
        *,
        pagination_options: PaginationOptions | None = None,
        options: RequestOptions | None = None,
        session_options: SessionOptions | None = None,
    ) -> Page[_dcg_type_0, ListNotesResponse] | None:
        """Fetch the page after a page of this helper, or return None after the last page."""
        return following_page(
            self._core,
            _plans.PLAN_0,
            page,
            pagination_options=pagination_options,
            options=options,
            session_options=session_options,
        )

    def resume(
        self,
        state: ResumeState,
        *,
        pagination_options: PaginationOptions | None = None,
        options: RequestOptions | None = None,
        session_options: SessionOptions | None = None,
    ) -> Pager[_dcg_type_0, ListNotesResponse]:
        """Return a pager continuing a checkpoint; it sends nothing until it is iterated."""
        return resume_pages(
            self._core,
            _plans.PLAN_0,
            state,
            pagination_options=pagination_options,
            options=options,
            session_options=session_options,
        )


class NotesWatchSse:
    """The notes.watch SSE helper of GET /notes/events."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the helper sends through."""
        self._core = core

    def open(
        self,
        *,
        stream_options: StreamOptions | None = None,
        options: RequestOptions | None = None,
        session_options: SessionOptions | None = None,
    ) -> EventStream[_dcg_type_0]:
        """Open the event stream of GET /notes/events, returning once its response is a declared success."""
        return open_events(
            self._core,
            _plans.STREAM_0,
            (),
            stream_options=stream_options,
            options=options,
            session_options=session_options,
        )
