# generated by datamodel-codegen:
#   filename:  issue.json

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(extra='forbid'))
class SomeSpec:
    services: dict[Annotated[str, Field(pattern=r'^[a-zA-Z0-9._-]+$')], str] | None = (
        None
    )
    """
    Some property.
    """
