# generated by datamodel-codegen:
#   filename:  querystring-targets.yaml

"""The plans of this package's protocol helpers; regenerate them instead of editing."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Final

import models

from .. import _operations
from .._generated import model_bindings
from .._runtime.protocols.pagination import CursorPlan, PageBinding, PaginationPlan
from .._runtime.protocols.polling import PollingPlan
from .._runtime.protocols.records import (
    BodySelector,
    HeaderSelector,
    ParameterTarget,
    QuerystringTarget,
)
from .._runtime.protocols.references import OperationRef
from .._runtime.protocols.streams import EventPlan, StreamResumePlan
from .._runtime.protocols.uploads import UploadPlan
from ..types.default import (
    CreateFileResponse,
    CreateJobResponse,
    GetJobResponse,
    SearchResponse,
)


def _items_0(data: SearchResponse) -> Sequence[str] | None:
    """Return the items of one page of search.all."""
    return data.data


PLAN_0: Final[PaginationPlan[str, SearchResponse]] = PaginationPlan(
    helper_id='search.all',
    operation=OperationRef(pointer='/paths/~1search~1{scope}/get'),
    call=_operations.OPERATION_0,
    items=_items_0,
    items_selector=BodySelector(pointer='/data'),
    continuation=CursorPlan(
        read=BodySelector(pointer='/next'),
        write=ParameterTarget(location='header', name='X-Cursor'),
        end_missing=True,
        empty_string_ends=True,
    ),
    fingerprint='64c7fb5f76009475b309c908f6bfcecbc509102e9b5b4a82c21d53d32c457fb1',
)


def _items_1(data: SearchResponse) -> Sequence[str] | None:
    """Return the items of one page of search.everything."""
    return data.data


PLAN_1: Final[PaginationPlan[str, SearchResponse]] = PaginationPlan(
    helper_id='search.everything',
    operation=OperationRef(pointer='/paths/~1search~1{scope}/get'),
    call=_operations.OPERATION_0,
    items=_items_1,
    items_selector=BodySelector(pointer='/data'),
    continuation=CursorPlan(
        read=BodySelector(pointer='/next'),
        write=ParameterTarget(location='header', name='x-cursor'),
        end_missing=True,
        empty_string_ends=True,
    ),
    fingerprint='dc1c53dfcdba5448472573739bd416de836e4f2acd8e9043051ecafd4d42c817',
    bindings=(
        PageBinding(
            target=ParameterTarget(location='path', name='scope'),
            literal='everything',
        ),
        PageBinding(
            target=QuerystringTarget(name='criteria', pointer='/limit'),
            literal=50,
        ),
    ),
)


PLAN_2: Final[PollingPlan[None, GetJobResponse, CreateJobResponse]] = PollingPlan(
    helper_id='jobs.run',
    operation=OperationRef(pointer='/paths/~1jobs/post'),
    create=_operations.OPERATION_2,
    accepted=(202,),
    poll_operation=OperationRef(pointer='/paths/~1jobs~1{jobId}/get'),
    poll=_operations.OPERATION_3,
    state=BodySelector(pointer='/status'),
    pending=('queued', 'running'),
    succeeded=('done',),
    bindings=(
        PageBinding(
            target=ParameterTarget(location='path', name='jobId'),
            source='initial',
            selector=BodySelector(pointer='/id'),
        ),
        PageBinding(
            target=ParameterTarget(location='header', name='X-Trace'),
            literal='poll',
        ),
        PageBinding(
            target=QuerystringTarget(name='view', pointer='/fields'),
            literal='status',
        ),
    ),
    interval=1.0,
)


PLAN_3: Final[UploadPlan[None, CreateFileResponse]] = UploadPlan(
    helper_id='files.upload',
    operation=OperationRef(pointer='/paths/~1files/post'),
    create=_operations.OPERATION_4,
    probe_operation=OperationRef(pointer='/paths/~1files~1{fileId}/head'),
    probe=_operations.OPERATION_5,
    remote_offset=HeaderSelector(name='Upload-Offset'),
    append_operation=OperationRef(pointer='/paths/~1files~1{fileId}/patch'),
    append=_operations.OPERATION_6,
    offset=ParameterTarget(location='header', name='Upload-Offset'),
    max_chunk_bytes=4,
    partial_commit=True,
    size=ParameterTarget(location='header', name='Upload-Length'),
    probe_bindings=(
        PageBinding(
            target=ParameterTarget(location='path', name='fileId'),
            source='initial',
            selector=BodySelector(pointer='/id'),
        ),
        PageBinding(
            target=QuerystringTarget(name='detail', pointer='/kind'),
            literal='offset',
        ),
    ),
    append_bindings=(
        PageBinding(
            target=ParameterTarget(location='path', name='fileId'),
            source='initial',
            selector=BodySelector(pointer='/id'),
        ),
    ),
)


STREAM_0: Final[EventPlan[models.Message]] = EventPlan(
    helper_id='events.live',
    operation=OperationRef(pointer='/paths/~1events/get'),
    call=_operations.OPERATION_1,
    media='text/event-stream',
    event=model_bindings.codec_23,
    resume=StreamResumePlan(
        operation=OperationRef(pointer='/paths/~1events/get'),
        call=_operations.OPERATION_1,
        media='text/event-stream',
        write=ParameterTarget(location='header', name='Last-Event-ID'),
        own=True,
    ),
)
