# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""The OpenAPI fragments this package adds to its served document; regenerate them instead of editing."""

from typing import Final

from .._runtime.server.openapi import OpenAPIPackagePlan

_BUNDLE = r"""{
 "operations": [
  {
   "key": "/paths/~1items~1{item-id}~1parts~1{part}/get",
   "method": "get",
   "route_path": "/items/{dcg_p0}/parts/{part}",
   "slots": [
    [
     "dcg_p0",
     "item-id"
    ]
   ],
   "fragment": {
    "responses": {
     "200": {
      "description": "The part.",
      "content": {
       "application/json": {
        "schema": {
         "type": "string"
        }
       }
      }
     },
     "500": {
      "description": "Internal Server Error",
      "content": {
       "text/plain": {
        "schema": {
         "$ref": "#/components/schemas/dcg_server_error__b3eacd33433b"
        }
       }
      }
     }
    },
    "security": []
   }
  },
  {
   "key": "/paths/~1adapters/get",
   "method": "get",
   "route_path": "/adapters",
   "slots": [],
   "fragment": {
    "parameters": [
     {
      "name": "session",
      "in": "cookie",
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "filter",
      "in": "query",
      "style": "deepObject",
      "explode": true,
      "schema": {
       "$ref": "#/components/schemas/Filter__54d881e92487"
      }
     },
     {
      "name": "ids",
      "in": "query",
      "explode": false,
      "schema": {
       "type": "array",
       "items": {
        "type": "integer"
       }
      }
     },
     {
      "name": "X-Ids",
      "in": "header",
      "schema": {
       "type": "array",
       "items": {
        "type": "integer"
       }
      }
     },
     {
      "name": "blob",
      "in": "query",
      "content": {
       "application/json": {
        "schema": {
         "type": "object"
        }
       }
      }
     },
     {
      "name": "code",
      "in": "query",
      "schema": {
       "type": "string",
       "pattern": "^[A-Z]+$"
      }
     },
     {
      "name": "mail",
      "in": "query",
      "schema": {
       "type": "string",
       "format": "email"
      }
     },
     {
      "name": "other",
      "in": "query",
      "schema": {
       "type": "string",
       "not": {
        "const": "x"
       }
      }
     },
     {
      "name": "none",
      "in": "query",
      "schema": {
       "type": [
        "string",
        "null"
       ],
       "enum": [
        null
       ]
      }
     },
     {
      "name": "count",
      "in": "query",
      "schema": {
       "type": "integer",
       "default": "ten"
      }
     },
     {
      "name": "point",
      "in": "query",
      "schema": {
       "$ref": "#/components/schemas/Point__3c0b4d3e67cf"
      }
     }
    ],
    "responses": {
     "204": {
      "description": "Nothing."
     },
     "400": {
      "description": "Invalid request",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/dcg_http_error__b3eacd33433b"
        },
        "example": {
         "detail": "Invalid request"
        }
       }
      }
     },
     "422": {
      "description": "Validation Error",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/dcg_validation_error__b3eacd33433b"
        }
       }
      }
     },
     "500": {
      "description": "Internal Server Error",
      "content": {
       "text/plain": {
        "schema": {
         "$ref": "#/components/schemas/dcg_server_error__b3eacd33433b"
        }
       }
      }
     }
    },
    "security": []
   }
  },
  {
   "key": "/paths/~1repeat~1{id}~1again~1{id}/get",
   "method": "get",
   "route_path": "/repeat/{dcg_p0}/again/{dcg_p1}",
   "slots": [
    [
     "dcg_p0",
     "id"
    ],
    [
     "dcg_p1",
     "id"
    ]
   ],
   "fragment": {
    "parameters": [
     {
      "name": "id",
      "in": "path",
      "required": true,
      "schema": {
       "type": "integer"
      }
     }
    ],
    "responses": {
     "204": {
      "description": "Nothing."
     },
     "400": {
      "description": "Invalid request",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/dcg_http_error__b3eacd33433b"
        },
        "example": {
         "detail": "Invalid request"
        }
       }
      }
     },
     "422": {
      "description": "Validation Error",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/dcg_validation_error__b3eacd33433b"
        }
       }
      }
     },
     "500": {
      "description": "Internal Server Error",
      "content": {
       "text/plain": {
        "schema": {
         "$ref": "#/components/schemas/dcg_server_error__b3eacd33433b"
        }
       }
      }
     }
    },
    "security": []
   }
  }
 ],
 "components": {
  "schemas": {
   "dcg_server_error__b3eacd33433b": {
    "type": "string"
   },
   "Filter__54d881e92487": {
    "type": "object",
    "required": [
     "name"
    ],
    "properties": {
     "id": {
      "type": "integer",
      "readOnly": true
     },
     "name": {
      "type": "string"
     }
    }
   },
   "Point__3c0b4d3e67cf": {
    "type": "object",
    "additionalProperties": false,
    "required": [
     "x"
    ],
    "properties": {
     "x": {
      "type": "integer"
     }
    }
   },
   "dcg_http_error__b3eacd33433b": {
    "type": "object",
    "properties": {
     "detail": {}
    },
    "required": [
     "detail"
    ]
   },
   "dcg_validation_error__b3eacd33433b": {
    "type": "object",
    "properties": {
     "detail": {
      "type": "array",
      "items": {
       "type": "object",
       "properties": {
        "loc": {
         "type": "array",
         "items": {
          "anyOf": [
           {
            "type": "string"
           },
           {
            "type": "integer"
           }
          ]
         }
        },
        "msg": {
         "type": "string"
        },
        "type": {
         "type": "string"
        }
       },
       "required": [
        "loc",
        "msg",
        "type"
       ]
      }
     }
    },
    "required": [
     "detail"
    ]
   }
  }
 }
}"""
PLAN: Final = OpenAPIPackagePlan(
    package='server',
    version='3.1.0',
    repeated=True,
    operation_keys=(
        '/paths/~1items~1{item-id}~1parts~1{part}/get',
        '/paths/~1adapters/get',
        '/paths/~1repeat~1{id}~1again~1{id}/get',
    ),
    bundle=_BUNDLE,
)
