# generated by datamodel-codegen:
#   filename:  oas32.yaml

"""Operation plans of this package; regenerate them instead of editing."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Final, TypedDict

import plan_oas32_models
from pydantic import TypeAdapter

from .._runtime.model_codecs.media import FieldPlan
from .._runtime.model_codecs.parameters import ParameterPlan
from .._runtime.server.application import Dependency, OperationPlan
from .._runtime.server.requests import ParameterAdapter, ParameterArgument
from .._runtime.server.responses import Declared, OperationResponses

OperationDependencies = TypedDict(
    'OperationDependencies',
    {
        'get__search': Sequence[Dependency],
        'get__spread': Sequence[Dependency],
        'post__raw': Sequence[Dependency],
    },
    total=False,
)


class GetSearch:
    """Plans of the get__search operation."""

    OPERATION: Final = OperationPlan(
        name='get__search',
        service='untagged',
        keywords=('query', 'theme', 'prefs'),
    )
    @dataclass(frozen=True, slots=True, kw_only=True)
    class Parameters:
        """The adapter parameters of get__search."""

        query: plan_oas32_models.FieldSearchGetQuerystringQueryParameter | None
        prefs: plan_oas32_models.FieldSearchGetCookiePrefsParameter | None

    PARAMETERS: Final = ParameterAdapter(
        arguments=(
            ParameterArgument(
                name='query',
                plan=ParameterPlan(
                    location='querystring',
                    name='query',
                    content_media_type='application/x-www-form-urlencoded',
                    fields=(
                        FieldPlan('q', 'string'),
                        FieldPlan('tags', 'string', repeated=True),
                        FieldPlan('n', 'integer'),
                    ),
                ),
                adapter=TypeAdapter(plan_oas32_models.FieldSearchGetQuerystringQueryParameter),
            ),
            ParameterArgument(
                name='prefs',
                plan=ParameterPlan(
                    location='cookie',
                    name='prefs',
                    style='cookie',
                    explode=True,
                    shape='object',
                    fields=(FieldPlan('a', 'string'),),
                    reserved_names=('theme',),
                ),
                adapter=TypeAdapter(plan_oas32_models.FieldSearchGetCookiePrefsParameter),
            ),
        ),
        record=Parameters,
    )
    RESPONSES: Final = OperationResponses(responses={'204': Declared()}, primary=204)


class GetSpread:
    """Plans of the get__spread operation."""

    OPERATION: Final = OperationPlan(
        name='get__spread',
        service='untagged',
        keywords=('extra', 'window', 'jar', 'crumbs', 'x_counts', 'x_tallies'),
    )
    @dataclass(frozen=True, slots=True, kw_only=True)
    class Parameters:
        """The adapter parameters of get__spread."""

        extra: plan_oas32_models.FieldSpreadGetQueryExtraParameter | None
        window: plan_oas32_models.FieldSpreadGetQueryWindowParameter | None
        jar: plan_oas32_models.FieldSpreadGetCookieJarParameter | None
        crumbs: plan_oas32_models.FieldSpreadGetCookieCrumbsParameter | None
        x_counts: dict[str, int] | None
        x_tallies: dict[str, int] | None

    PARAMETERS: Final = ParameterAdapter(
        arguments=(
            ParameterArgument(
                name='extra',
                plan=ParameterPlan(
                    location='query',
                    name='extra',
                    style='form',
                    explode=True,
                    shape='object',
                    additional=FieldPlan('', 'string'),
                    reserved_names=('limit', 'offset', 'window'),
                ),
                adapter=TypeAdapter(plan_oas32_models.FieldSpreadGetQueryExtraParameter),
            ),
            ParameterArgument(
                name='window',
                plan=ParameterPlan(
                    location='query',
                    name='window',
                    style='form',
                    explode=True,
                    shape='object',
                    fields=(
                        FieldPlan('limit', 'integer'),
                        FieldPlan('offset', 'integer'),
                    ),
                    reserved_names=('extra',),
                ),
                adapter=TypeAdapter(plan_oas32_models.FieldSpreadGetQueryWindowParameter),
            ),
            ParameterArgument(
                name='jar',
                plan=ParameterPlan(
                    location='cookie',
                    name='jar',
                    style='form',
                    explode=True,
                    shape='object',
                    additional=FieldPlan('', 'string'),
                    reserved_names=('crumbs', 'flavor'),
                ),
                adapter=TypeAdapter(plan_oas32_models.FieldSpreadGetCookieJarParameter),
            ),
            ParameterArgument(
                name='crumbs',
                plan=ParameterPlan(
                    location='cookie',
                    name='crumbs',
                    style='cookie',
                    explode=True,
                    shape='object',
                    fields=(FieldPlan('flavor', 'string'),),
                    reserved_names=('jar',),
                ),
                adapter=TypeAdapter(plan_oas32_models.FieldSpreadGetCookieCrumbsParameter),
            ),
            ParameterArgument(
                name='x_counts',
                plan=ParameterPlan(
                    location='header',
                    name='X-Counts',
                    style='simple',
                    explode=True,
                    shape='object',
                    additional=FieldPlan('', 'integer'),
                    reserved_names=('X-Tallies',),
                ),
                adapter=TypeAdapter(dict[str, int]),
            ),
            ParameterArgument(
                name='x_tallies',
                plan=ParameterPlan(
                    location='header',
                    name='X-Tallies',
                    style='simple',
                    explode=True,
                    shape='object',
                    additional=FieldPlan('', 'integer'),
                    reserved_names=('X-Counts',),
                ),
                adapter=TypeAdapter(dict[str, int]),
            ),
        ),
        record=Parameters,
    )
    RESPONSES: Final = OperationResponses(responses={'204': Declared()}, primary=204)


class PostRaw:
    """Plans of the post__raw operation."""

    OPERATION: Final = OperationPlan(
        name='post__raw',
        service='untagged',
        keywords=('querystring_body', 'note'),
    )
    @dataclass(frozen=True, slots=True, kw_only=True)
    class Parameters:
        """The adapter parameters of post__raw."""

        querystring_body: plan_oas32_models.FieldRawPostQuerystringBodyParameter | None
        note: str | None

    PARAMETERS: Final = ParameterAdapter(
        arguments=(
            ParameterArgument(
                name='querystring_body',
                plan=ParameterPlan(
                    location='querystring',
                    name='body',
                    content_media_type='application/json',
                ),
                adapter=TypeAdapter(plan_oas32_models.FieldRawPostQuerystringBodyParameter),
            ),
            ParameterArgument(
                name='note',
                plan=ParameterPlan(
                    location='header',
                    name='note',
                    content_media_type='text/plain',
                ),
                adapter=TypeAdapter(str),
            ),
        ),
        record=Parameters,
    )
    RESPONSES: Final = OperationResponses(responses={'204': Declared()}, primary=204)
