# generated by datamodel-codegen:
#   filename:  field-ownership-conflict.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.stdlib import Field, Model, StdlibCodec



MODELS: Final[dict[type, Model]] = {
    models.A: Model((Field('a', 'a'),), True),
    models.B: Model((Field('b', 'b'),), True),
    models.C: Model((Field('b', 'b'), Field('a', 'a'), Field('c', 'c')), True),
    models.D: Model((Field('a', 'a'), Field('b', 'b'), Field('d', 'd')), True),
    models.E: Model((), True),
}

codec_0: Final[StdlibCodec[models.A]] = StdlibCodec(models.A, MODELS)
"""Codec of /paths/~1bindings~10/post request_body (request application/json)."""

codec_1: Final[StdlibCodec[models.A]] = StdlibCodec(models.A, MODELS)
"""Codec of /paths/~1bindings~10/post response_body (response 200 application/json)."""

codec_2: Final[StdlibCodec[models.B]] = StdlibCodec(models.B, MODELS)
"""Codec of /paths/~1bindings~11/post request_body (request application/json)."""

codec_3: Final[StdlibCodec[models.B]] = StdlibCodec(models.B, MODELS)
"""Codec of /paths/~1bindings~11/post response_body (response 200 application/json)."""

codec_4: Final[StdlibCodec[models.C]] = StdlibCodec(models.C, MODELS)
"""Codec of /paths/~1bindings~12/post request_body (request application/json)."""

codec_5: Final[StdlibCodec[models.C]] = StdlibCodec(models.C, MODELS)
"""Codec of /paths/~1bindings~12/post response_body (response 200 application/json)."""

codec_6: Final[StdlibCodec[models.D]] = StdlibCodec(models.D, MODELS)
"""Codec of /paths/~1bindings~13/post request_body (request application/json)."""

codec_7: Final[StdlibCodec[models.D]] = StdlibCodec(models.D, MODELS)
"""Codec of /paths/~1bindings~13/post response_body (response 200 application/json)."""

codec_8: Final[StdlibCodec[models.E]] = StdlibCodec(models.E, MODELS)
"""Codec of /paths/~1bindings~14/post request_body (request application/json)."""

codec_9: Final[StdlibCodec[models.E]] = StdlibCodec(models.E, MODELS)
"""Codec of /paths/~1bindings~14/post response_body (response 200 application/json)."""
