# generated by datamodel-codegen:
#   filename:  pets.yaml

"""Register a generated router's operations on one APIRouter, with the services that implement them."""

from __future__ import annotations

from collections.abc import Awaitable, Callable, Mapping, Sequence
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Final, TypeAlias

from fastapi import APIRouter
from fastapi.encoders import jsonable_encoder
from fastapi.exceptions import RequestValidationError
from starlette.responses import JSONResponse

from .security import awaitable

if TYPE_CHECKING:
    from fastapi.params import Depends
    from starlette.requests import Request

_REQUEST_VALUES: Final = frozenset({"input", "ctx", "url"})


@dataclass(frozen=True, slots=True, kw_only=True)
class Wiring:
    """What route adders connect: the services by group, the awaited authorize callback, and operation dependencies."""

    services: Mapping[str, Any]
    authorize: Callable[..., Awaitable[object]]
    dependencies: Mapping[str, Sequence[Depends]]


Route: TypeAlias = tuple[str, Callable[[APIRouter, Wiring], None]]


async def validation_error_handler(  # noqa: RUF029 - Starlette runs a synchronous handler in the threadpool.
    _: Request, error: RequestValidationError
) -> JSONResponse:
    """Answer 422 with FastAPI's records without what the request sent: their type, location, and message."""
    records = [{key: value for key, value in record.items() if key not in _REQUEST_VALUES} for record in error.errors()]
    return JSONResponse({"detail": jsonable_encoder(records)}, status_code=422)


def error_handlers(exception_handlers: Mapping[Any, Any] | None) -> dict[Any, Any]:
    """Return an application's exception handlers: validation_error_handler, under the caller's own handlers."""
    return {RequestValidationError: validation_error_handler, **(exception_handlers or {})}


def _unsecured(*_: object) -> None:
    """Stand in for the authorize callback of a router without secured operations, which never calls it."""


def build(  # noqa: PLR0913
    routes: tuple[Route, ...],
    *,
    services: Mapping[str, Any],
    authorize: Callable[..., object] = _unsecured,
    dependencies: Sequence[Depends],
    operation_dependencies: Mapping[str, Any] | None,
    prefix: str,
) -> APIRouter:
    """Register the routes in order on a new router; each looks its service's method up as it registers.

    The service Protocols and FastAPI check the services and settings. Only a dependency for a method the router
    does not have is refused here, since nothing else would report it.
    """
    wiring = Wiring(services=services, authorize=awaitable(authorize), dependencies=operation_dependencies or {})
    if unknown := sorted(wiring.dependencies.keys() - {name for name, _ in routes}):
        msg = f"operation_dependencies names no operation of this router: {', '.join(unknown)}"
        raise ValueError(msg)
    router = APIRouter(prefix=prefix, dependencies=dependencies)
    for _, add in routes:
        add(router, wiring)
    return router
