# generated by datamodel-codegen:
#   filename:  sockets.yaml

"""The plans of this package's WebSocket helpers; regenerate them instead of editing."""

from __future__ import annotations

from typing import Final

import models

from .. import _operations
from .._generated import model_bindings
from .._runtime.protocols.references import OperationRef
from .._runtime.protocols.websocket import ChannelPlan

SOCKET_0: Final[ChannelPlan[models.ClientMessage, models.ServerMessage]] = ChannelPlan(
    helper_id='rooms.chat',
    operation=OperationRef(pointer='/paths/~1rooms~1{room}~1socket/get'),
    call=_operations.OPERATION_0,
    fingerprint='2f356a109b6654cc65d6175f3cd5245db40d801b3dd5b4bcd9050617ca8d2cc7',
    encoder=model_bindings.codec_4,
    decoder=model_bindings.codec_5,
    subprotocols=('chat.v2', 'chat.v1'),
)


SOCKET_1: Final[ChannelPlan[str, bytes]] = ChannelPlan(
    helper_id='feed.text',
    operation=OperationRef(pointer='/paths/~1feed~1socket/get'),
    call=_operations.OPERATION_1,
    fingerprint='5f27732c942fd28d386b84339da9f1152f1a555950adeaa7a262ef485d8c7a3b',
    send_codec='utf8',
    receive_codec='bytes',
    receive_frame='binary',
)


SOCKET_2: Final[ChannelPlan[bytes, str]] = ChannelPlan(
    helper_id='secure.chat',
    operation=OperationRef(pointer='/paths/~1secure~1socket/get'),
    call=_operations.OPERATION_2,
    fingerprint='7072fb3d0f918fc42250649d4e2d6c264f4ea0768a8fb5c77f560f654238e94e',
    send_codec='bytes',
    send_frame='binary',
    receive_codec='utf8',
)
