# generated by datamodel-codegen:
#   filename:  session-contract.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

from typing import Final

import models

from .._runtime.model_codecs.native import PydanticDataclassCodec

codec_0: Final[
    PydanticDataclassCodec[models.FieldRecordsIdPostHeaderTraceParameter]
] = PydanticDataclassCodec(models.FieldRecordsIdPostHeaderTraceParameter)
"""Codec of /paths/~1records~1{id}/post parameter (request header trace)."""

codec_1: Final[
    PydanticDataclassCodec[models.FieldRecordsIdPostQueryFilterParameter]
] = PydanticDataclassCodec(models.FieldRecordsIdPostQueryFilterParameter)
"""Codec of /paths/~1records~1{id}/post parameter (request query filter application/json)."""

codec_2: Final[PydanticDataclassCodec[models.FieldRecordsIdPostPathIdParameter]] = (
    PydanticDataclassCodec(models.FieldRecordsIdPostPathIdParameter)
)
"""Codec of /paths/~1records~1{id}/post parameter (request path id)."""

codec_3: Final[PydanticDataclassCodec[models.PageParameter]] = PydanticDataclassCodec(
    models.PageParameter
)
"""Codec of /paths/~1records~1{id}/post parameter (request query page)."""

codec_4: Final[PydanticDataclassCodec[models.Record]] = PydanticDataclassCodec(
    models.Record
)
"""Codec of /paths/~1records~1{id}/post request_body (request application/json)."""

codec_5: Final[PydanticDataclassCodec[models.Record]] = PydanticDataclassCodec(
    models.Record
)
"""Codec of /paths/~1records~1{id}/post request_body (request application/vnd.acme+json)."""

codec_6: Final[PydanticDataclassCodec[models.Record]] = PydanticDataclassCodec(
    models.Record
)
"""Codec of /paths/~1records~1{id}/post request_body (request multipart/form-data)."""

codec_7: Final[PydanticDataclassCodec[models.Record]] = PydanticDataclassCodec(
    models.Record
)
"""Codec of /paths/~1records~1{id}/post response_body (response 201 application/json)."""

codec_8: Final[
    PydanticDataclassCodec[models.FieldRecordsIdPostResponse201LocationHeader]
] = PydanticDataclassCodec(models.FieldRecordsIdPostResponse201LocationHeader)
"""Codec of /paths/~1records~1{id}/post response_header (response Location 201)."""

codec_9: Final[
    PydanticDataclassCodec[models.FieldRecordsIdPostResponse201XLimitHeader]
] = PydanticDataclassCodec(models.FieldRecordsIdPostResponse201XLimitHeader)
"""Codec of /paths/~1records~1{id}/post response_header (response X-Limit 201)."""

codec_10: Final[PydanticDataclassCodec[models.Problem]] = PydanticDataclassCodec(
    models.Problem
)
"""Codec of /paths/~1records~1{id}/post response_body (response 4XX application/problem+json)."""

codec_11: Final[PydanticDataclassCodec[models.FieldRecordsIdPostPathIdParameter]] = (
    PydanticDataclassCodec(models.FieldRecordsIdPostPathIdParameter)
)
"""Codec of /paths/~1records~1{id}/get parameter (request path id)."""

codec_12: Final[PydanticDataclassCodec[models.PageParameter]] = PydanticDataclassCodec(
    models.PageParameter
)
"""Codec of /paths/~1records~1{id}/get parameter (request query page)."""

codec_13: Final[PydanticDataclassCodec[models.Record]] = PydanticDataclassCodec(
    models.Record
)
"""Codec of /paths/~1records~1{id}/get response_body (response 200 application/json)."""
