# generated by datamodel-codegen:
#   filename:  forward.json

from __future__ import annotations
from typing import Literal, TypedDict



class RequestBase(TypedDict):
    version: Literal['v1', 'v2']