# generated by datamodel-codegen:
#   filename:  server-variants.yaml

from __future__ import annotations

from pydantic import BaseModel

from . import name as name_1
from . import owner as owner_1


class Pet(BaseModel):
    id: int | None = None
    name: name_1.Name
    secret: str | None = None
    owner: owner_1.Owner | None = None
