# generated by datamodel-codegen:
#   filename:  native.yaml

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, ConfigDict, EmailStr, Field, conint, constr
from pydantic.dataclasses import dataclass
from typing_extensions import TypeAliasType


@dataclass
class Cat:
    kind: Literal['cat']


@dataclass
class Dog:
    kind: Literal['dog']


@dataclass
class Ranges:
    small: conint(ge=0, le=10)
    positive: conint(lt=100, gt=0)


@dataclass
class Wide:
    big: int


Name = TypeAliasType("Name", str)


@dataclass
class Patterned:
    code: constr(pattern=r'^[a-z]+$')


@dataclass
class Bounded:
    name: str | None = None


class Color(Enum):
    red = 'red'
    blue = 'blue'


Code = TypeAliasType("Code", constr(max_length=3))


@dataclass
class MaybeInner:
    a: str


@dataclass(config=ConfigDict(extra='forbid'))
class Closed:
    a: str


@dataclass
class Extended(Closed):
    b: str


@dataclass
class Defaulted:
    a: str


@dataclass
class Listed:
    items: list[Any]
    sized: list[str] = Field(..., min_length=1)


@dataclass
class Mapped:
    counts: Any


@dataclass
class Opaque:
    mail: EmailStr


@dataclass
class Anything:
    value: Any
    other: Any


@dataclass
class Constant:
    kind: Literal['fixed']


@dataclass
class Stamped:
    at: AwareDatetime
    host: constr(pattern=r'^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]{0,61}[A-Za-z0-9])$')
    day: date


@dataclass
class Twice:
    a: Code
    b: Code


@dataclass
class Node:
    children: list[Node]


@dataclass(config=ConfigDict(extra='allow'))
class Extra:
    a: str


@dataclass
class Nested:
    grid: list[list[int]]
    loose: dict[str, Any]


Label = TypeAliasType("Label", str)


@dataclass
class Discriminated:
    pet: Cat | Dog = Field(..., discriminator='kind')


@dataclass
class Described:
    name: Name = Field(..., description='The name.')


@dataclass
class Painted:
    color: Color


@dataclass
class Holder:
    code: Code


@dataclass
class Wrapper:
    inner: MaybeInner | None


@dataclass
class Box:
    label: Label
    multi: dict[str, Any] | list[int]
    closed: dict[str, Any] = Field(..., max_length=0)
