# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Business logic of the post_item operation; replace the body with its implementation."""

from __future__ import annotations

import bodies_basemodel_models
from fastapi.responses import Response

from ..errors import UnimplementedOperationError
from ..model_codecs import Unset
from ..responses import HTTPResult, PostItemResponsePayload


def post_item(
    *,
    body: bodies_basemodel_models.Item | Unset,
) -> None | HTTPResult[PostItemResponsePayload] | Response:
    """Answer 501 until the post_item operation is implemented."""
    raise UnimplementedOperationError
