# generated by datamodel-codegen:
#   filename:  session-missing-reference.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.native import PydanticDataclassCodec


codec_0: Final[PydanticDataclassCodec[models.Missing]] = PydanticDataclassCodec(models.Missing)
"""Codec of /paths/~1missing/post request_body (request application/json)."""
