# Generated by datamodel-code-generator; target=client; schema_version=1
"""Model codec bindings of this generated package; regenerate them instead of editing."""

from __future__ import annotations

from functools import cache
from typing import Final

import models

import tests.data.python.parameter_adapters as tests_data_python_parameter_adapters

from .._runtime.model_codecs.adapters import (
    AdapterParameterCodec,
    ParameterCodecAdapterV1,
)
from .._runtime.model_codecs.bindings import (
    ArrayNode,
    FieldBinding,
    LeafNode,
    ModelBinding,
    ModelNode,
    UseBinding,
)
from .._runtime.model_codecs.capabilities import (
    AdapterManifest,
    ParameterCodecCapabilities,
)
from .._runtime.model_codecs.context import CodecContext
from .._runtime.model_codecs.outbound import NativeOutboundCodec
from .._runtime.model_codecs.pydantic_v2 import PydanticModelCodec
from .._runtime.model_codecs.registry import BundleSchemaRegistry, SchemaSource
from .._runtime.model_codecs.schema import DirectionalView, SchemaBundle, SchemaResource
from .._runtime.model_codecs.views import (
    CodecBindingView,
    CodecFieldView,
    CodecSourceRef,
    CodecUseView,
    ModelExportView,
    ParameterPlanView,
)
from .._runtime.model_codecs.wire import freeze_wire


@cache
def _resources() -> tuple[SchemaResource, ...]:
    return (
        SchemaResource(
            uri='https://dcg.invalid/inputs/root',
            contents=freeze_wire({
                'components': {
                    'schemas': {
                        'Filter': {
                            'type': 'object',
                            'properties': {
                                'range': {
                                    'type': 'object',
                                    'properties': {'min': {'type': 'integer'}, 'max': {'type': 'integer'}},
                                },
                                'name': {'type': 'string'},
                            },
                        },
                        'Key': {'type': 'object', 'required': ['a'], 'properties': {'a': {'type': 'integer'}}},
                        'Tags': {'type': 'array', 'items': {'type': 'string'}},
                    },
                },
                'paths': {
                    '/items/{key}': {
                        'get': {
                            'parameters': [
                                {'schema': {'$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Key'}},
                            ],
                        },
                    },
                    '/tags': {
                        'get': {
                            'parameters': [
                                {'schema': {'$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Tags'}},
                                {'schema': {'type': 'string'}},
                                {'schema': {'$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Filter'}},
                                {'schema': {'type': 'array', 'items': {'type': 'string'}}},
                            ],
                        },
                    },
                },
            }),
            roots=(
                '/components/schemas/Filter',
                '/components/schemas/Key',
                '/components/schemas/Tags',
                '/paths/~1items~1{key}/get/parameters/0/schema',
                '/paths/~1tags/get/parameters/0/schema',
                '/paths/~1tags/get/parameters/1/schema',
                '/paths/~1tags/get/parameters/2/schema',
                '/paths/~1tags/get/parameters/3/schema',
            ),
        ),
    )


@cache
def _request_view() -> DirectionalView:
    return DirectionalView(direction='request')


@cache
def request_bundle() -> SchemaBundle:
    return SchemaBundle(_resources(), _request_view())


@cache
def request_registry() -> BundleSchemaRegistry:
    return BundleSchemaRegistry(
        request_bundle(),
        (
            SchemaSource(
                schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/0/schema',
                source=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/0/schema'),
                dialect='https://json-schema.org/draft/2020-12/schema',
                raw=freeze_wire({'$ref': '#/components/schemas/Tags'}),
            ),
            SchemaSource(
                schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/2/schema',
                source=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/2/schema'),
                dialect='https://json-schema.org/draft/2020-12/schema',
                raw=freeze_wire({'$ref': '#/components/schemas/Filter'}),
            ),
            SchemaSource(
                schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/3/schema',
                source=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/3/schema'),
                dialect='https://json-schema.org/draft/2020-12/schema',
                raw=freeze_wire({'type': 'array', 'items': {'type': 'string'}}),
            ),
            SchemaSource(
                schema_id='https://dcg.invalid/inputs/root#/paths/~1items~1%7Bkey%7D/get/parameters/0/schema',
                source=CodecSourceRef(document='/inputs/root', pointer='/paths/~1items~1{key}/get/parameters/0/schema'),
                dialect='https://json-schema.org/draft/2020-12/schema',
                raw=freeze_wire({'$ref': '#/components/schemas/Key'}),
            ),
        ),
    )


@cache
def _model_0() -> ModelBinding:
    return ModelBinding(
        symbol='models:Tags',
        native_kind='root',
        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Tags',
        root=ArrayNode(item=LeafNode()),
    )


@cache
def _model_1() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldTagsGetCookieSessionParameter',
        native_kind='root',
        schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/1/schema',
        root=LeafNode(),
    )


@cache
def _model_2() -> ModelBinding:
    return ModelBinding(
        symbol='models:Filter',
        native_kind='model',
        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Filter',
        fields=(
            FieldBinding(
                field_id='models:Filter.range',
                native_name='range',
                wire_name='range',
                validation_key='range',
                validation_keys=('range',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=ModelNode(symbol='models:Range'),
            ),
            FieldBinding(
                field_id='models:Filter.name',
                native_name='name',
                wire_name='name',
                validation_key='name',
                validation_keys=('name',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=LeafNode(),
            ),
        ),
    )


@cache
def _model_3() -> ModelBinding:
    return ModelBinding(
        symbol='models:Range',
        native_kind='model',
        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Filter/properties/range',
        fields=(
            FieldBinding(
                field_id='models:Range.min',
                native_name='min',
                wire_name='min',
                validation_key='min',
                validation_keys=('min',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:Range.max',
                native_name='max',
                wire_name='max',
                validation_key='max',
                validation_keys=('max',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=LeafNode(),
            ),
        ),
    )


@cache
def _model_4() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldTagsGetHeaderXLabelsParameter',
        native_kind='root',
        schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/3/schema',
        root=ArrayNode(item=LeafNode()),
    )


@cache
def _model_5() -> ModelBinding:
    return ModelBinding(
        symbol='models:Key',
        native_kind='model',
        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Key',
        fields=(
            FieldBinding(
                field_id='models:Key.a',
                native_name='a',
                wire_name='a',
                validation_key='a',
                validation_keys=('a',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
        ),
    )


@cache
def _factory_0() -> ParameterCodecAdapterV1:
    return tests_data_python_parameter_adapters.json_cookie()


@cache
def _factory_1() -> ParameterCodecAdapterV1:
    return tests_data_python_parameter_adapters.json_query()


@cache
def _factory_2() -> ParameterCodecAdapterV1:
    return tests_data_python_parameter_adapters.json_header()


@cache
def _factory_3() -> ParameterCodecAdapterV1:
    return tests_data_python_parameter_adapters.json_path()


CONTEXT_0: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/0/schema',
    operation_id='/paths/~1tags/get',
)


@cache
def codec_0() -> PydanticModelCodec[models.Tags]:
    """Codec of /paths/~1tags/get parameter (request cookie tags)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Tags|ModelNode(symbol='models:Tags')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/0/schema',
            operation_id='/paths/~1tags/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='models:Tags',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:Tags'),
            models=(_model_0(),),
        ),
        models.Tags,
        {'models:Tags': models.Tags},
        request_bundle,
    )


@cache
def outbound_0() -> NativeOutboundCodec[models.Tags]:
    return NativeOutboundCodec(codec_0(), CONTEXT_0)


@cache
def parameter_0() -> AdapterParameterCodec:
    return AdapterParameterCodec(
        manifest=AdapterManifest(
            name='json-cookie',
            import_ref='tests.data.python.parameter_adapters:json_cookie',
            capabilities=ParameterCodecCapabilities(
                locations=('cookie',),
                styles=('form',),
                explode_values=(False,),
                value_kinds=('array',),
                supports_empty_containers=True,
            ),
        ),
        plan=ParameterPlanView(
            binding=CodecBindingView(
                binding_id="https://dcg.invalid/inputs/root#/components/schemas/Tags|ModelNode(symbol='models:Tags')",
                use=CodecUseView(
                    owner_kind='operation',
                    owner=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get'),
                    role='parameter',
                    use_site=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/0'),
                    schema=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/0/schema'),
                    declaration=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/0'),
                    direction='request',
                    projection='value',
                    location='cookie',
                    name='tags',
                    status=None,
                    media=None,
                ),
                schema=request_registry().get('https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/0/schema'),
                backend='pydantic_v2.BaseModel',
                native_kind='root',
                native_export=ModelExportView(module='models', symbol='Tags'),
                fields=(),
                projection_mode='native',
                converter_strategy='pydantic_type_adapter',
            ),
            location='cookie',
            name='tags',
            oas_version='3.1.0',
            style='form',
            explode=False,
            required=False,
            allow_reserved=False,
            allow_empty_value=False,
            content_media_type=None,
            reserved_names=('session',),
        ),
        adapter=_factory_0(),
    )


CONTEXT_1: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/1/schema',
    operation_id='/paths/~1tags/get',
)


@cache
def codec_1() -> PydanticModelCodec[models.FieldTagsGetCookieSessionParameter]:
    """Codec of /paths/~1tags/get parameter (request cookie session)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/1/schema|ModelNode(symbol='models:FieldTagsGetCookieSessionParameter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/1/schema',
            operation_id='/paths/~1tags/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='models:FieldTagsGetCookieSessionParameter',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:FieldTagsGetCookieSessionParameter'),
            models=(_model_1(),),
        ),
        models.FieldTagsGetCookieSessionParameter,
        {'models:FieldTagsGetCookieSessionParameter': models.FieldTagsGetCookieSessionParameter},
        request_bundle,
    )


@cache
def outbound_1() -> NativeOutboundCodec[models.FieldTagsGetCookieSessionParameter]:
    return NativeOutboundCodec(codec_1(), CONTEXT_1)


CONTEXT_2: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/2/schema',
    operation_id='/paths/~1tags/get',
)


@cache
def codec_2() -> PydanticModelCodec[models.Filter]:
    """Codec of /paths/~1tags/get parameter (request query where)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Filter|ModelNode(symbol='models:Filter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/2/schema',
            operation_id='/paths/~1tags/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='models:Filter',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:Filter'),
            models=(_model_2(), _model_3()),
        ),
        models.Filter,
        {'models:Filter': models.Filter, 'models:Range': models.Range},
        request_bundle,
    )


@cache
def outbound_2() -> NativeOutboundCodec[models.Filter]:
    return NativeOutboundCodec(codec_2(), CONTEXT_2)


@cache
def parameter_2() -> AdapterParameterCodec:
    return AdapterParameterCodec(
        manifest=AdapterManifest(
            name='json-query',
            import_ref='tests.data.python.parameter_adapters:json_query',
            capabilities=ParameterCodecCapabilities(
                locations=('query',),
                styles=('deepObject',),
                explode_values=(True,),
                value_kinds=('object',),
            ),
        ),
        plan=ParameterPlanView(
            binding=CodecBindingView(
                binding_id="https://dcg.invalid/inputs/root#/components/schemas/Filter|ModelNode(symbol='models:Filter')",
                use=CodecUseView(
                    owner_kind='operation',
                    owner=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get'),
                    role='parameter',
                    use_site=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/2'),
                    schema=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/2/schema'),
                    declaration=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/2'),
                    direction='request',
                    projection='value',
                    location='query',
                    name='where',
                    status=None,
                    media=None,
                ),
                schema=request_registry().get('https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/2/schema'),
                backend='pydantic_v2.BaseModel',
                native_kind='model',
                native_export=ModelExportView(module='models', symbol='Filter'),
                fields=(
                    CodecFieldView(
                        field_id='models:Filter.range',
                        native_name='range',
                        wire_name='range',
                        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Filter/properties/range',
                        validation_paths=(('range',),),
                        serialization_alias=None,
                        required=False,
                        read_only=False,
                        write_only=False,
                        default_kind='none',
                        excluded=None,
                    ),
                    CodecFieldView(
                        field_id='models:Filter.name',
                        native_name='name',
                        wire_name='name',
                        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Filter/properties/name',
                        validation_paths=(('name',),),
                        serialization_alias=None,
                        required=False,
                        read_only=False,
                        write_only=False,
                        default_kind='none',
                        excluded=None,
                    ),
                ),
                projection_mode='native',
                converter_strategy='pydantic_type_adapter',
            ),
            location='query',
            name='where',
            oas_version='3.1.0',
            style='deepObject',
            explode=True,
            required=False,
            allow_reserved=False,
            allow_empty_value=False,
            content_media_type=None,
            reserved_names=(),
        ),
        adapter=_factory_1(),
    )


CONTEXT_3: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/3/schema',
    operation_id='/paths/~1tags/get',
)


@cache
def codec_3() -> PydanticModelCodec[models.FieldTagsGetHeaderXLabelsParameter]:
    """Codec of /paths/~1tags/get parameter (request header X-Labels)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/3/schema|ModelNode(symbol='models:FieldTagsGetHeaderXLabelsParameter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/3/schema',
            operation_id='/paths/~1tags/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='models:FieldTagsGetHeaderXLabelsParameter',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:FieldTagsGetHeaderXLabelsParameter'),
            models=(_model_4(),),
        ),
        models.FieldTagsGetHeaderXLabelsParameter,
        {'models:FieldTagsGetHeaderXLabelsParameter': models.FieldTagsGetHeaderXLabelsParameter},
        request_bundle,
    )


@cache
def outbound_3() -> NativeOutboundCodec[models.FieldTagsGetHeaderXLabelsParameter]:
    return NativeOutboundCodec(codec_3(), CONTEXT_3)


@cache
def parameter_3() -> AdapterParameterCodec:
    return AdapterParameterCodec(
        manifest=AdapterManifest(
            name='json-header',
            import_ref='tests.data.python.parameter_adapters:json_header',
            capabilities=ParameterCodecCapabilities(
                locations=('header',),
                styles=('simple',),
                explode_values=(False,),
                value_kinds=('array',),
            ),
        ),
        plan=ParameterPlanView(
            binding=CodecBindingView(
                binding_id="https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/3/schema|ModelNode(symbol='models:FieldTagsGetHeaderXLabelsParameter')",
                use=CodecUseView(
                    owner_kind='operation',
                    owner=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get'),
                    role='parameter',
                    use_site=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/3'),
                    schema=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/3/schema'),
                    declaration=CodecSourceRef(document='/inputs/root', pointer='/paths/~1tags/get/parameters/3'),
                    direction='request',
                    projection='value',
                    location='header',
                    name='X-Labels',
                    status=None,
                    media=None,
                ),
                schema=request_registry().get('https://dcg.invalid/inputs/root#/paths/~1tags/get/parameters/3/schema'),
                backend='pydantic_v2.BaseModel',
                native_kind='root',
                native_export=ModelExportView(module='models', symbol='FieldTagsGetHeaderXLabelsParameter'),
                fields=(),
                projection_mode='native',
                converter_strategy='pydantic_type_adapter',
            ),
            location='header',
            name='X-Labels',
            oas_version='3.1.0',
            style='simple',
            explode=False,
            required=False,
            allow_reserved=False,
            allow_empty_value=False,
            content_media_type=None,
            reserved_names=(),
        ),
        adapter=_factory_2(),
    )


CONTEXT_4: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1items~1%7Bkey%7D/get/parameters/0/schema',
    operation_id='/paths/~1items~1{key}/get',
)


@cache
def codec_4() -> PydanticModelCodec[models.Key]:
    """Codec of /paths/~1items~1{key}/get parameter (request path key)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Key|ModelNode(symbol='models:Key')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1items~1%7Bkey%7D/get/parameters/0/schema',
            operation_id='/paths/~1items~1{key}/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='models:Key',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:Key'),
            models=(_model_5(),),
        ),
        models.Key,
        {'models:Key': models.Key},
        request_bundle,
    )


@cache
def outbound_4() -> NativeOutboundCodec[models.Key]:
    return NativeOutboundCodec(codec_4(), CONTEXT_4)


@cache
def parameter_4() -> AdapterParameterCodec:
    return AdapterParameterCodec(
        manifest=AdapterManifest(
            name='json-path',
            import_ref='tests.data.python.parameter_adapters:json_path',
            capabilities=ParameterCodecCapabilities(
                locations=('path',),
                styles=('simple',),
                explode_values=(False,),
                value_kinds=('object',),
            ),
        ),
        plan=ParameterPlanView(
            binding=CodecBindingView(
                binding_id="https://dcg.invalid/inputs/root#/components/schemas/Key|ModelNode(symbol='models:Key')",
                use=CodecUseView(
                    owner_kind='operation',
                    owner=CodecSourceRef(document='/inputs/root', pointer='/paths/~1items~1{key}/get'),
                    role='parameter',
                    use_site=CodecSourceRef(document='/inputs/root', pointer='/paths/~1items~1{key}/get/parameters/0'),
                    schema=CodecSourceRef(
                        document='/inputs/root',
                        pointer='/paths/~1items~1{key}/get/parameters/0/schema',
                    ),
                    declaration=CodecSourceRef(
                        document='/inputs/root',
                        pointer='/paths/~1items~1{key}/get/parameters/0',
                    ),
                    direction='request',
                    projection='value',
                    location='path',
                    name='key',
                    status=None,
                    media=None,
                ),
                schema=request_registry().get('https://dcg.invalid/inputs/root#/paths/~1items~1%7Bkey%7D/get/parameters/0/schema'),
                backend='pydantic_v2.BaseModel',
                native_kind='model',
                native_export=ModelExportView(module='models', symbol='Key'),
                fields=(
                    CodecFieldView(
                        field_id='models:Key.a',
                        native_name='a',
                        wire_name='a',
                        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Key/properties/a',
                        validation_paths=(('a',),),
                        serialization_alias=None,
                        required=True,
                        read_only=False,
                        write_only=False,
                        default_kind='absent',
                        excluded=None,
                    ),
                ),
                projection_mode='native',
                converter_strategy='pydantic_type_adapter',
            ),
            location='path',
            name='key',
            oas_version='3.1.0',
            style='simple',
            explode=False,
            required=True,
            allow_reserved=False,
            allow_empty_value=False,
            content_media_type=None,
            reserved_names=(),
        ),
        adapter=_factory_3(),
    )
