# generated by datamodel-codegen:
#   filename:  session-discriminator-copied.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.stdlib import Choice, Field, Model, StdlibCodec



MODELS: Final[dict[type, Model]] = {
    models.RequestBase: Model((Field('version', 'version'),), True),
    models.RequestV1: Model((Field('version', 'version'), Field('request_id', 'request_id')), True),
    models.RequestV2: Model((Field('version', 'version'),), True),
    models.Grandchild: Model((Field('version', 'version'), Field('request_id', 'request_id')), True),
}

codec_0: Final[StdlibCodec[models.Request]] = StdlibCodec(Choice((), 'version', (('v1', models.RequestV1), ('v2', models.RequestV2))), MODELS)
"""Codec of /paths/~1bindings~10/post request_body (request application/json)."""

codec_1: Final[StdlibCodec[models.Request]] = StdlibCodec(Choice((), 'version', (('v1', models.RequestV1), ('v2', models.RequestV2))), MODELS)
"""Codec of /paths/~1bindings~10/post response_body (response 200 application/json)."""

codec_2: Final[StdlibCodec[models.RequestVersionEnum]] = StdlibCodec(None, MODELS)
"""Codec of /paths/~1bindings~11/post request_body (request application/json)."""

codec_3: Final[StdlibCodec[models.RequestVersionEnum]] = StdlibCodec(None, MODELS)
"""Codec of /paths/~1bindings~11/post response_body (response 200 application/json)."""

codec_4: Final[StdlibCodec[models.RequestBase]] = StdlibCodec(models.RequestBase, MODELS)
"""Codec of /paths/~1bindings~12/post request_body (request application/json)."""

codec_5: Final[StdlibCodec[models.RequestBase]] = StdlibCodec(models.RequestBase, MODELS)
"""Codec of /paths/~1bindings~12/post response_body (response 200 application/json)."""

codec_6: Final[StdlibCodec[models.RequestV1]] = StdlibCodec(models.RequestV1, MODELS)
"""Codec of /paths/~1bindings~13/post request_body (request application/json)."""

codec_7: Final[StdlibCodec[models.RequestV1]] = StdlibCodec(models.RequestV1, MODELS)
"""Codec of /paths/~1bindings~13/post response_body (response 200 application/json)."""

codec_8: Final[StdlibCodec[models.RequestV2]] = StdlibCodec(models.RequestV2, MODELS)
"""Codec of /paths/~1bindings~14/post request_body (request application/json)."""

codec_9: Final[StdlibCodec[models.RequestV2]] = StdlibCodec(models.RequestV2, MODELS)
"""Codec of /paths/~1bindings~14/post response_body (response 200 application/json)."""

codec_10: Final[StdlibCodec[models.Grandchild]] = StdlibCodec(models.Grandchild, MODELS)
"""Codec of /paths/~1bindings~15/post request_body (request application/json)."""

codec_11: Final[StdlibCodec[models.Grandchild]] = StdlibCodec(models.Grandchild, MODELS)
"""Codec of /paths/~1bindings~15/post response_body (response 200 application/json)."""
