# generated by datamodel-codegen:
#   filename:  annotated_forward_reference.json
#   timestamp: 2019-07-26T00:00:00+00:00

from typing import Annotated, Optional

from pydantic import BaseModel, Field, RootModel


class Labels(RootModel[list[str]]):
    root: Annotated[list[str], Field(min_length=1)]


class Tree(BaseModel):
    treeName: Optional[str] = None
    rootNode: Annotated["Node", Field(description='The first node')]
    spare_node: Annotated[Optional["Node"], Field(alias='spare-node')] = None
    nodes: Annotated[Optional[list["Node"]], Field(min_length=1)] = None
    labels: Optional[Labels] = None
    pick: Annotated[Optional["Node"], Field(title='Pick', validate_default=True)] = {}
    spare: Annotated[Optional["Node"], Field(validate_default=True)] = {'nodeValue': 8}
    branches: Optional["Branches"] = None


class Branches(RootModel[list["Twigs"]]):
    root: Annotated[list["Twigs"], Field(min_length=1, title='Branch list')]


class Node(BaseModel):
    nodeValue: Optional[int] = None
    owner_tree: Annotated[Optional[Tree], Field(alias='owner-tree')] = None
    next_node: Annotated[Optional["Node"], Field(alias='next-node')] = None
    kind: Optional[str] = 'leaf'


class Twigs(RootModel[list[Branches]]):
    root: list[Branches]


Tree.model_rebuild()
Branches.model_rebuild()
