# Generated by datamodel-code-generator; target=client; schema_version=1
"""The result records of this package's batch helpers; regenerate them instead of editing."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, TypeAlias, final

from models import ItemError as _dcg_type_1
from models import Tag as _dcg_type_2
from models import User as _dcg_type_0

from ..responses import ResponseInfo

__all__ = [
    'TagsColorsDeliveryUnknown',
    'TagsColorsError',
    'TagsColorsResult',
    'TagsColorsSuccess',
    'TagsPutDeliveryUnknown',
    'TagsPutError',
    'TagsPutResult',
    'TagsPutSuccess',
    'UsersCreateDeliveryUnknown',
    'UsersCreateError',
    'UsersCreateResult',
    'UsersCreateSuccess',
]


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class UsersCreateSuccess:
    """One item of users.create the server applied, with its success value."""

    index: int
    item_id: str
    response: ResponseInfo | None
    value: _dcg_type_0 = field(repr=False)
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['success'] = field(default='success', init=False)


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class UsersCreateError:
    """One item of users.create the server refused, with its error."""

    index: int
    item_id: str
    response: ResponseInfo | None
    error: _dcg_type_1 = field(repr=False)
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['error'] = field(default='error', init=False)


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class UsersCreateDeliveryUnknown:
    """One item of users.create whose request may have reached the server unanswered."""

    index: int
    item_id: str
    response: ResponseInfo | None
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['delivery_unknown'] = field(default='delivery_unknown', init=False)


UsersCreateResult: TypeAlias = UsersCreateSuccess | UsersCreateError | UsersCreateDeliveryUnknown


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class TagsPutSuccess:
    """One item of tags.put the server applied, with its success value."""

    index: int
    item_id: None
    response: ResponseInfo | None
    value: _dcg_type_2 = field(repr=False)
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['success'] = field(default='success', init=False)


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class TagsPutError:
    """One item of tags.put the server refused, with its error."""

    index: int
    item_id: None
    response: ResponseInfo | None
    error: _dcg_type_1 = field(repr=False)
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['error'] = field(default='error', init=False)


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class TagsPutDeliveryUnknown:
    """One item of tags.put whose request may have reached the server unanswered."""

    index: int
    item_id: None
    response: ResponseInfo | None
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['delivery_unknown'] = field(default='delivery_unknown', init=False)


TagsPutResult: TypeAlias = TagsPutSuccess | TagsPutError | TagsPutDeliveryUnknown


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class TagsColorsSuccess:
    """One item of tags.colors the server applied, with its success value."""

    index: int
    item_id: str
    response: ResponseInfo | None
    value: _dcg_type_2 = field(repr=False)
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['success'] = field(default='success', init=False)


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class TagsColorsError:
    """One item of tags.colors the server refused, with its error."""

    index: int
    item_id: str
    response: ResponseInfo | None
    error: _dcg_type_1 = field(repr=False)
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['error'] = field(default='error', init=False)


@final
@dataclass(frozen=True, slots=True, kw_only=True)
class TagsColorsDeliveryUnknown:
    """One item of tags.colors whose request may have reached the server unanswered."""

    index: int
    item_id: str
    response: ResponseInfo | None
    retry_token: bytes | None = field(default=None, repr=False)
    outcome: Literal['delivery_unknown'] = field(default='delivery_unknown', init=False)


TagsColorsResult: TypeAlias = TagsColorsSuccess | TagsColorsError | TagsColorsDeliveryUnknown
