# Generated by datamodel-code-generator; target=client; schema_version=1
"""The operation registry of this package; regenerate it instead of editing."""

from __future__ import annotations

from typing import Final

from ._runtime.client.operations import OperationPlan
