# Generated by datamodel-code-generator; target=client; schema_version=1
"""The arguments of the default operations, which calls take unpacked."""

from __future__ import annotations

from typing_extensions import TypedDict


class GetRootArguments(TypedDict):
    """The parameters of get_root, which a call takes unpacked as keyword arguments."""
