# generated by datamodel-codegen:
#   filename:  copied-field-origins.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.native import PydanticCodec


codec_0: Final[PydanticCodec[models.BaseRequest]] = PydanticCodec(models.BaseRequest)
"""Codec of /paths/~1bindings~10/post request_body (request application/json)."""

codec_1: Final[PydanticCodec[models.BaseResponse]] = PydanticCodec(models.BaseResponse)
"""Codec of /paths/~1bindings~10/post response_body (response 200 application/json)."""

codec_2: Final[PydanticCodec[models.ChildRequest]] = PydanticCodec(models.ChildRequest)
"""Codec of /paths/~1bindings~11/post request_body (request application/json)."""

codec_3: Final[PydanticCodec[models.ChildResponse]] = PydanticCodec(models.ChildResponse)
"""Codec of /paths/~1bindings~11/post response_body (response 200 application/json)."""

codec_4: Final[PydanticCodec[models.GrandChildRequest]] = PydanticCodec(models.GrandChildRequest)
"""Codec of /paths/~1bindings~12/post request_body (request application/json)."""

codec_5: Final[PydanticCodec[models.GrandChildResponse]] = PydanticCodec(models.GrandChildResponse)
"""Codec of /paths/~1bindings~12/post response_body (response 200 application/json)."""
