# Generated by datamodel-code-generator; target=client; schema_version=1
"""The types of the u30e6_u30fc_u30b6_u30fc operations."""

from typing import TYPE_CHECKING

from ._operations import (
    HttpGetUsersErrorData,
    HttpGetUsersHTTPError,
    HttpGetUsersRequestCodecs,
    HttpGetUsersResponse,
)

if TYPE_CHECKING:
    from ._arguments import HttpGetUsersArguments

__all__ = [
    'HttpGetUsersArguments',
    'HttpGetUsersErrorData',
    'HttpGetUsersHTTPError',
    'HttpGetUsersRequestCodecs',
    'HttpGetUsersResponse',
]


def __getattr__(name: str) -> object:
    """Import the TypedDicts of the operations' arguments on first use, which no call needs."""
    if name.endswith("Arguments") and name in __all__:
        from . import _arguments

        return getattr(_arguments, name)
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)
