# generated by datamodel-codegen:
#   filename:  session-directional-producers.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.stdlib import Field, Items, Model, StdlibCodec



MODELS: Final[dict[type, Model]] = {
    models.ARequest: Model((Field('name', 'name'), Field('secret', 'secret')), True),
    models.AResponse: Model((Field('id', 'id'), Field('name', 'name')), True),
    models.A: Model((Field('id', 'id'), Field('name', 'name'), Field('secret', 'secret')), True),
    models.BRequest: Model((Field('name', 'name'), Field('secret', 'secret')), True),
    models.BResponse: Model((Field('id', 'id'), Field('name', 'name')), True),
    models.ChildRequest: Model((Field('secret', 'secret'), Field('name', 'name')), True),
    models.ChildResponse: Model((Field('id', 'id'), Field('name', 'name')), True),
}

codec_0: Final[StdlibCodec[models.ARequest]] = StdlibCodec(models.ARequest, MODELS)
"""Codec of /paths/~1a/post request_body (request application/json)."""

codec_1: Final[StdlibCodec[models.AResponse]] = StdlibCodec(models.AResponse, MODELS)
"""Codec of /paths/~1a/post response_body (response 200 application/json)."""

codec_2: Final[StdlibCodec[models.BRequest]] = StdlibCodec(models.BRequest, MODELS)
"""Codec of /paths/~1b/post request_body (request application/json)."""

codec_3: Final[StdlibCodec[models.BResponse]] = StdlibCodec(models.BResponse, MODELS)
"""Codec of /paths/~1b/post response_body (response 200 application/json)."""

codec_4: Final[StdlibCodec[models.Array]] = StdlibCodec(Items(models.A), MODELS)
"""Codec of /paths/~1array/post request_body (request application/json)."""

codec_5: Final[StdlibCodec[models.Array]] = StdlibCodec(Items(models.A), MODELS)
"""Codec of /paths/~1array/post response_body (response 200 application/json)."""

codec_6: Final[StdlibCodec[models.ChildRequest]] = StdlibCodec(models.ChildRequest, MODELS)
"""Codec of /paths/~1child/post request_body (request application/json)."""

codec_7: Final[StdlibCodec[models.ChildResponse]] = StdlibCodec(models.ChildResponse, MODELS)
"""Codec of /paths/~1child/post response_body (response 200 application/json)."""
