# generated by datamodel-codegen:
#   filename:  pagination.yaml

"""The asyncio client of this package."""

from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from functools import cached_property
from types import TracebackType
from typing import TYPE_CHECKING

import httpx2
from typing_extensions import Self

from ._generated import security
from ._runtime.client.auth import SchemeCredentials, Secret, TokenSource
from ._runtime.client.client import AsyncClientCore, ClientDefaults
from ._runtime.client.errors import add_secondary
from ._runtime.client.options import ClientOptions
from ._runtime.model_codecs.unset import UNSET, Unset
from .bodies import AsyncBodyInput
from .model_codecs import JSONValue
from .options import RequestOptions
from .responses import AsyncRawResponse

if TYPE_CHECKING:
    from .protocols._async_helpers import AsyncProtocolHelpers
    from .resources.archive._async import AsyncArchiveResource
    from .resources.labels._async import AsyncLabelsResource
    from .resources.loose._async import AsyncLooseResource
    from .resources.nested._async import AsyncNestedResource
    from .resources.secure._async import AsyncSecureResource
    from .resources.statuses._async import AsyncStatusesResource
    from .resources.users._async import AsyncUsersResource

_DEFAULTS = ClientDefaults(
    security_schemes=security.ROOT_SCHEMES,
    helpers=(
        ('users.all', 'pagination'),
        ('users.by_header', 'pagination'),
        ('users.search', 'pagination'),
        ('loose.all', 'pagination'),
        ('loose.tokens', 'pagination'),
        ('nested.all', 'pagination'),
        ('labels.all', 'pagination'),
        ('labels.sets', 'pagination'),
        ('archive.all', 'pagination'),
        ('statuses.all', 'pagination'),
        ('secure.users', 'pagination'),
    ),
)


class AsyncClientView:
    """Typed operations and request option layers sharing the root's native client."""

    _core: AsyncClientCore

    @classmethod
    def _from_core(cls, core: AsyncClientCore) -> AsyncClientView:
        view = cls.__new__(cls)
        view._core = core
        return view

    def with_options(self, options: RequestOptions) -> AsyncClientView:
        """Return a typed view with these request options layered on the current settings."""
        return AsyncClientView._from_core(self._core.view(options))

    async def request_raw(
        self,
        method: str,
        url: str,
        *,
        body: AsyncBodyInput[JSONValue] | Unset = UNSET,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Send a request to any absolute URL, outside the operations, and return its raw response in memory."""
        return await self._core.request_raw(method, url, body=body, options=options)

    @cached_property
    def with_streaming_response(self) -> AsyncClientWithStreamingResponse:
        """Raw requests that send on entering a block that streams the response."""
        return AsyncClientWithStreamingResponse(self._core)

    @cached_property
    def users(self) -> AsyncUsersResource:
        """The users operations."""
        from .resources.users._async import AsyncUsersResource

        return AsyncUsersResource(self._core)

    @cached_property
    def loose(self) -> AsyncLooseResource:
        """The loose operations."""
        from .resources.loose._async import AsyncLooseResource

        return AsyncLooseResource(self._core)

    @cached_property
    def nested(self) -> AsyncNestedResource:
        """The nested operations."""
        from .resources.nested._async import AsyncNestedResource

        return AsyncNestedResource(self._core)

    @cached_property
    def labels(self) -> AsyncLabelsResource:
        """The labels operations."""
        from .resources.labels._async import AsyncLabelsResource

        return AsyncLabelsResource(self._core)

    @cached_property
    def archive(self) -> AsyncArchiveResource:
        """The archive operations."""
        from .resources.archive._async import AsyncArchiveResource

        return AsyncArchiveResource(self._core)

    @cached_property
    def statuses(self) -> AsyncStatusesResource:
        """The statuses operations."""
        from .resources.statuses._async import AsyncStatusesResource

        return AsyncStatusesResource(self._core)

    @cached_property
    def secure(self) -> AsyncSecureResource:
        """The secure operations."""
        from .resources.secure._async import AsyncSecureResource

        return AsyncSecureResource(self._core)

    @cached_property
    def protocols(self) -> AsyncProtocolHelpers:
        """The protocol helpers of this API, by their dotted names."""
        from .protocols._async_helpers import AsyncProtocolHelpers

        return AsyncProtocolHelpers(self._core)


class AsyncClient(AsyncClientView):
    """Call the operations of this API with asyncio through HTTPX2."""

    def __init__(
        self,
        *,
        oauth: Secret | TokenSource | None = None,
        options: ClientOptions | None = None,
        http_client: httpx2.AsyncClient | Unset | None = UNSET,
    ) -> None:
        """Borrow the native HTTP client given, or create one this root owns and closes."""
        self._core = AsyncClientCore.create(
            _DEFAULTS,
            options=options,
            http_client=http_client,
            credentials=SchemeCredentials({"oauth": oauth}),
        )

    async def aclose(self) -> None:
        """Close the native HTTP client created by this root once; borrowed clients remain caller owned."""
        await self._core.aclose()

    async def __aenter__(self) -> Self:
        """Return this client, which leaving the block closes."""
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Close this client, keeping a close failure beside an error that leaves the block."""
        try:
            await self.aclose()
        except Exception as error:
            if exc is None:
                raise
            add_secondary(exc, error)


class AsyncClientWithStreamingResponse:
    """Raw requests to any absolute URL that send on entering a block that streams the response."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the requests send through."""
        self._core = core

    def request_raw(
        self,
        method: str,
        url: str,
        *,
        body: AsyncBodyInput[JSONValue] | Unset = UNSET,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Return a block that sends the request on entry and yields its streaming response until exit."""
        return self._core.stream_raw(method, url, body=body, options=options)
