# generated by datamodel-codegen:
#   filename:  pagination.yaml

"""The synchronous client of this package."""

from __future__ import annotations

from contextlib import AbstractContextManager
from functools import cached_property
from types import TracebackType
from typing import TYPE_CHECKING

import httpx2
from typing_extensions import Self

from ._generated import security
from ._runtime.client.client import ClientCore, ClientDefaults
from ._runtime.client.errors import add_secondary
from ._runtime.model_codecs.unset import UNSET, Unset
from .bodies import BodyInput
from .model_codecs import JSONValue
from .options import ClientOptions, RequestOptions
from .responses import RawResponse

if TYPE_CHECKING:
    from .protocols._helpers import ProtocolHelpers
    from .resources.archive._sync import ArchiveResource
    from .resources.labels._sync import LabelsResource
    from .resources.loose._sync import LooseResource
    from .resources.nested._sync import NestedResource
    from .resources.secure._sync import SecureResource
    from .resources.statuses._sync import StatusesResource
    from .resources.users._sync import UsersResource

_DEFAULTS = ClientDefaults(
    user_agent=None,
    security_schemes=security.ROOT_SCHEMES,
    helpers=(
        ('users.all', 'pagination'),
        ('users.by_header', 'pagination'),
        ('users.search', 'pagination'),
        ('loose.all', 'pagination'),
        ('loose.tokens', 'pagination'),
        ('nested.all', 'pagination'),
        ('labels.all', 'pagination'),
        ('labels.sets', 'pagination'),
        ('archive.all', 'pagination'),
        ('statuses.all', 'pagination'),
        ('secure.users', 'pagination'),
    ),
)


class ClientView:
    """Typed operations and request option layers sharing the root's native client."""

    _core: ClientCore

    @classmethod
    def _from_core(cls, core: ClientCore) -> ClientView:
        view = cls.__new__(cls)
        view._core = core
        return view

    def with_options(self, options: RequestOptions) -> ClientView:
        """Return a typed view with these request options layered on the current settings."""
        return ClientView._from_core(self._core.view(options))

    def request_raw(
        self,
        method: str,
        url: str,
        *,
        body: BodyInput[JSONValue] | Unset = UNSET,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Send a request to any absolute URL, outside the operations, and return its raw response in memory."""
        return self._core.request_raw(method, url, body=body, options=options)

    @cached_property
    def with_streaming_response(self) -> ClientWithStreamingResponse:
        """Raw requests that send on entering a block that streams the response."""
        return ClientWithStreamingResponse(self._core)

    @cached_property
    def users(self) -> UsersResource:
        """The users operations."""
        from .resources.users._sync import UsersResource

        return UsersResource(self._core)

    @cached_property
    def loose(self) -> LooseResource:
        """The loose operations."""
        from .resources.loose._sync import LooseResource

        return LooseResource(self._core)

    @cached_property
    def nested(self) -> NestedResource:
        """The nested operations."""
        from .resources.nested._sync import NestedResource

        return NestedResource(self._core)

    @cached_property
    def labels(self) -> LabelsResource:
        """The labels operations."""
        from .resources.labels._sync import LabelsResource

        return LabelsResource(self._core)

    @cached_property
    def archive(self) -> ArchiveResource:
        """The archive operations."""
        from .resources.archive._sync import ArchiveResource

        return ArchiveResource(self._core)

    @cached_property
    def statuses(self) -> StatusesResource:
        """The statuses operations."""
        from .resources.statuses._sync import StatusesResource

        return StatusesResource(self._core)

    @cached_property
    def secure(self) -> SecureResource:
        """The secure operations."""
        from .resources.secure._sync import SecureResource

        return SecureResource(self._core)

    @cached_property
    def protocols(self) -> ProtocolHelpers:
        """The protocol helpers of this API, by their dotted names."""
        from .protocols._helpers import ProtocolHelpers

        return ProtocolHelpers(self._core)


class Client(ClientView):
    """Call the operations of this API through HTTPX2."""

    def __init__(
        self,
        *,
        options: ClientOptions | None = None,
        http_client: httpx2.Client | Unset | None = UNSET,
    ) -> None:
        """Borrow the native HTTP client given, or create one this root owns and closes."""
        self._core = ClientCore.create(_DEFAULTS, options=options, http_client=http_client)

    def close(self) -> None:
        """Close the native HTTP client created by this root once; borrowed clients remain caller owned."""
        self._core.close()

    def __enter__(self) -> Self:
        """Return this client, which leaving the block closes."""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Close this client, keeping a close failure beside an error that leaves the block."""
        try:
            self.close()
        except Exception as error:
            if exc is None:
                raise
            add_secondary(exc, error)


class ClientWithStreamingResponse:
    """Raw requests to any absolute URL that send on entering a block that streams the response."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the requests send through."""
        self._core = core

    def request_raw(
        self,
        method: str,
        url: str,
        *,
        body: BodyInput[JSONValue] | Unset = UNSET,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Return a block that sends the request on entry and yields its streaming response until exit."""
        return self._core.stream_raw(method, url, body=body, options=options)
