# generated by datamodel-codegen:
#   filename:  ambiguous.yaml

from __future__ import annotations
from typing import Literal, TypeAlias, TypedDict



RequestVersionEnum: TypeAlias = Literal['v1', 'v2']



class RequestBase(TypedDict):
    version: RequestVersionEnum



class RequestV1(RequestBase):
    version: RequestVersionEnum
    request_id: str



class RequestV2(RequestBase):
    pass



class Grandchild(RequestV1):
    version: RequestVersionEnum



class GreatGrandchild(Grandchild):
    version: RequestVersionEnum



SecondRequest: TypeAlias = Grandchild | RequestV2



Request: TypeAlias = RequestV1 | RequestV2