# generated by datamodel-codegen:
#   filename:  oas30.yaml

"""Operation plans of this package; regenerate them instead of editing."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Final, TypedDict

import plan_oas30_models
from fastapi import params
from pydantic import TypeAdapter

from .._runtime.model_codecs.media import FieldPlan
from .._runtime.model_codecs.parameters import ParameterPlan
from .._runtime.server.requests import ParameterAdapter, ParameterArgument
from .._runtime.server.responses import Declared, OperationResponses

OperationDependencies = TypedDict(
    'OperationDependencies',
    {
        'get_items': Sequence[params.Depends]
    },
    total=False,
)


class GetItems:
    """Plans of the get_items operation."""

    @dataclass(frozen=True, slots=True, kw_only=True)
    class Parameters:
        """The adapter parameters of get_items."""

        flags: list[bool] | None
        page: plan_oas30_models.FieldItemsGetQueryPageParameter | None
        X_Id: list[int]
        pref: plan_oas30_models.FieldItemsGetCookiePrefParameter | None

    PARAMETERS: Final = ParameterAdapter(
        arguments=(ParameterArgument(name='flags', plan=ParameterPlan(location='query', name='flags', style='spaceDelimited', shape='array', kind='boolean', reserved_names=('limit', 'page', 'q')), adapter=TypeAdapter(list[bool])), ParameterArgument(name='page', plan=ParameterPlan(location='query', name='page', style='form', shape='object', fields=(FieldPlan('size', 'integer'),), additional=FieldPlan('', 'string'), reserved_names=('flags', 'limit', 'q')), adapter=TypeAdapter(plan_oas30_models.FieldItemsGetQueryPageParameter)), ParameterArgument(name='X_Id', plan=ParameterPlan(location='header', name='X-Id', style='simple', required=True, shape='array', kind='integer'), adapter=TypeAdapter(list[int])), ParameterArgument(name='pref', plan=ParameterPlan(location='cookie', name='pref', style='form', explode=True, shape='object', fields=(FieldPlan('theme', 'string'),), additional=FieldPlan('', 'string')), adapter=TypeAdapter(plan_oas30_models.FieldItemsGetCookiePrefParameter))),
        record=Parameters,
    )
    RESPONSES: Final = OperationResponses(
        responses={'200': Declared(media_type='application/json', model=plan_oas30_models.Item)},
    )
