# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Model codec bindings of this generated package; regenerate them instead of editing."""

from __future__ import annotations

from functools import cache
from typing import Final

import plan_oas30_models

from .._runtime.model_codecs.bindings import (
    ArrayNode,
    FieldBinding,
    LeafNode,
    ModelBinding,
    ModelNode,
    UseBinding,
)
from .._runtime.model_codecs.context import CodecContext
from .._runtime.model_codecs.outbound import NativeOutboundCodec
from .._runtime.model_codecs.pydantic_v2 import PydanticModelCodec
from .._runtime.model_codecs.schema import DirectionalView, SchemaBundle, SchemaResource
from .._runtime.model_codecs.wire import freeze_wire


@cache
def _resources() -> tuple[SchemaResource, ...]:
    return (
        SchemaResource(
            uri='https://dcg.invalid/inputs/root',
            contents=freeze_wire({
                'components': {
                    'schemas': {
                        'Item': {
                            'type': 'object',
                            'properties': {
                                'id': {'type': 'integer', 'exclusiveMinimum': 0},
                                'name': {'type': ['string', 'null'], 'x-extra': {'keep': 'me'}},
                                'tag': {'$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Tag'},
                                'other': {'$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Tag'},
                                'score': {'type': 'number', 'exclusiveMaximum': 10},
                                'choice': {'type': ['string', 'null'], 'enum': ['a', 'b']},
                                'untyped': {},
                                'lonely': {},
                            },
                        },
                        'Tag': {'type': 'string', 'minLength': 1},
                    },
                },
                'paths': {
                    '/items': {
                        'get': {
                            'parameters': [
                                {'schema': {'type': 'integer', 'maximum': 100, 'exclusiveMinimum': 1}},
                                {'schema': {'type': ['string', 'null']}},
                                {'schema': {'type': 'array', 'items': {'type': 'boolean'}}},
                                {
                                    'schema': {
                                        'type': 'object',
                                        'properties': {'size': {'type': 'integer'}},
                                        'additionalProperties': {'type': 'string'},
                                    },
                                },
                                {'schema': {'type': 'array', 'items': {'type': 'integer'}}},
                                {'schema': {'type': 'object', 'properties': {'theme': {'type': 'string'}}}},
                            ],
                            'responses': {
                                '200': {
                                    'content': {
                                        'application/json': {
                                            'schema': {
                                                '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Item',
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            }),
            roots=(
                '/components/schemas/Item',
                '/components/schemas/Tag',
                '/paths/~1items/get/parameters/0/schema',
                '/paths/~1items/get/parameters/1/schema',
                '/paths/~1items/get/parameters/2/schema',
                '/paths/~1items/get/parameters/3/schema',
                '/paths/~1items/get/parameters/4/schema',
                '/paths/~1items/get/parameters/5/schema',
                '/paths/~1items/get/responses/200/content/application~1json/schema',
            ),
        ),
    )


@cache
def _request_view() -> DirectionalView:
    return DirectionalView(direction='request')


@cache
def _response_view() -> DirectionalView:
    return DirectionalView(direction='response')


@cache
def request_bundle() -> SchemaBundle:
    return SchemaBundle(_resources(), _request_view())


@cache
def response_bundle() -> SchemaBundle:
    return SchemaBundle(_resources(), _response_view())


@cache
def _model_0() -> ModelBinding:
    return ModelBinding(
        symbol='plan_oas30_models:FieldItemsGetQueryFlagsParameter',
        native_kind='root',
        schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/2/schema',
        root=ArrayNode(item=LeafNode()),
    )


@cache
def _model_1() -> ModelBinding:
    return ModelBinding(
        symbol='plan_oas30_models:FieldItemsGetQueryPageParameter',
        native_kind='model',
        schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/3/schema',
        fields=(
            FieldBinding(
                field_id='plan_oas30_models:FieldItemsGetQueryPageParameter.size',
                native_name='size',
                wire_name='size',
                validation_key='size',
                validation_keys=('size',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=LeafNode(),
            ),
        ),
        extra='allow',
    )


@cache
def _model_2() -> ModelBinding:
    return ModelBinding(
        symbol='plan_oas30_models:FieldItemsGetHeaderXIdParameter',
        native_kind='root',
        schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/4/schema',
        root=ArrayNode(item=LeafNode()),
    )


@cache
def _model_3() -> ModelBinding:
    return ModelBinding(
        symbol='plan_oas30_models:FieldItemsGetCookiePrefParameter',
        native_kind='model',
        schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/5/schema',
        fields=(
            FieldBinding(
                field_id='plan_oas30_models:FieldItemsGetCookiePrefParameter.theme',
                native_name='theme',
                wire_name='theme',
                validation_key='theme',
                validation_keys=('theme',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=LeafNode(),
            ),
        ),
    )


@cache
def _model_4() -> ModelBinding:
    return ModelBinding(
        symbol='plan_oas30_models:Item',
        native_kind='model',
        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Item',
        fields=(
            FieldBinding(
                field_id='plan_oas30_models:Item.id',
                native_name='id',
                wire_name='id',
                validation_key='id',
                validation_keys=('id',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='plan_oas30_models:Item.name',
                native_name='name',
                wire_name='name',
                validation_key='name',
                validation_keys=('name',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='plan_oas30_models:Item.tag',
                native_name='tag',
                wire_name='tag',
                validation_key='tag',
                validation_keys=('tag',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=ModelNode(symbol='plan_oas30_models:Tag'),
            ),
            FieldBinding(
                field_id='plan_oas30_models:Item.other',
                native_name='other',
                wire_name='other',
                validation_key='other',
                validation_keys=('other',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=ModelNode(symbol='plan_oas30_models:Tag'),
            ),
            FieldBinding(
                field_id='plan_oas30_models:Item.score',
                native_name='score',
                wire_name='score',
                validation_key='score',
                validation_keys=('score',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=True,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='plan_oas30_models:Item.choice',
                native_name='choice',
                wire_name='choice',
                validation_key='choice',
                validation_keys=('choice',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='plan_oas30_models:Item.untyped',
                native_name='untyped',
                wire_name='untyped',
                validation_key='untyped',
                validation_keys=('untyped',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='plan_oas30_models:Item.lonely',
                native_name='lonely',
                wire_name='lonely',
                validation_key='lonely',
                validation_keys=('lonely',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
        ),
    )


@cache
def _model_5() -> ModelBinding:
    return ModelBinding(
        symbol='plan_oas30_models:Tag',
        native_kind='root',
        schema_id='https://dcg.invalid/inputs/root#/components/schemas/Tag',
        root=LeafNode(),
    )


CONTEXT_0: Final = CodecContext(
    surface='server',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/2/schema',
    operation_id='/paths/~1items/get',
)


@cache
def codec_0() -> PydanticModelCodec[plan_oas30_models.FieldItemsGetQueryFlagsParameter]:
    """Codec of /paths/~1items/get parameter (request query flags)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/2/schema|ModelNode(symbol='plan_oas30_models:FieldItemsGetQueryFlagsParameter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/2/schema',
            operation_id='/paths/~1items/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='plan_oas30_models:FieldItemsGetQueryFlagsParameter',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='plan_oas30_models:FieldItemsGetQueryFlagsParameter'),
            models=(_model_0(),),
        ),
        plan_oas30_models.FieldItemsGetQueryFlagsParameter,
        {'plan_oas30_models:FieldItemsGetQueryFlagsParameter': plan_oas30_models.FieldItemsGetQueryFlagsParameter},
        request_bundle,
    )


CONTEXT_1: Final = CodecContext(
    surface='server',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/3/schema',
    operation_id='/paths/~1items/get',
)


@cache
def codec_1() -> PydanticModelCodec[plan_oas30_models.FieldItemsGetQueryPageParameter]:
    """Codec of /paths/~1items/get parameter (request query page)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/3/schema|ModelNode(symbol='plan_oas30_models:FieldItemsGetQueryPageParameter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/3/schema',
            operation_id='/paths/~1items/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='plan_oas30_models:FieldItemsGetQueryPageParameter',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='plan_oas30_models:FieldItemsGetQueryPageParameter'),
            models=(_model_1(),),
        ),
        plan_oas30_models.FieldItemsGetQueryPageParameter,
        {'plan_oas30_models:FieldItemsGetQueryPageParameter': plan_oas30_models.FieldItemsGetQueryPageParameter},
        request_bundle,
    )


CONTEXT_2: Final = CodecContext(
    surface='server',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/4/schema',
    operation_id='/paths/~1items/get',
)


@cache
def codec_2() -> PydanticModelCodec[plan_oas30_models.FieldItemsGetHeaderXIdParameter]:
    """Codec of /paths/~1items/get parameter (request header X-Id)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/4/schema|ModelNode(symbol='plan_oas30_models:FieldItemsGetHeaderXIdParameter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/4/schema',
            operation_id='/paths/~1items/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='plan_oas30_models:FieldItemsGetHeaderXIdParameter',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='plan_oas30_models:FieldItemsGetHeaderXIdParameter'),
            models=(_model_2(),),
        ),
        plan_oas30_models.FieldItemsGetHeaderXIdParameter,
        {'plan_oas30_models:FieldItemsGetHeaderXIdParameter': plan_oas30_models.FieldItemsGetHeaderXIdParameter},
        request_bundle,
    )


CONTEXT_3: Final = CodecContext(
    surface='server',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/5/schema',
    operation_id='/paths/~1items/get',
)


@cache
def codec_3() -> PydanticModelCodec[plan_oas30_models.FieldItemsGetCookiePrefParameter]:
    """Codec of /paths/~1items/get parameter (request cookie pref)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/5/schema|ModelNode(symbol='plan_oas30_models:FieldItemsGetCookiePrefParameter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/parameters/5/schema',
            operation_id='/paths/~1items/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='plan_oas30_models:FieldItemsGetCookiePrefParameter',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='plan_oas30_models:FieldItemsGetCookiePrefParameter'),
            models=(_model_3(),),
        ),
        plan_oas30_models.FieldItemsGetCookiePrefParameter,
        {'plan_oas30_models:FieldItemsGetCookiePrefParameter': plan_oas30_models.FieldItemsGetCookiePrefParameter},
        request_bundle,
    )


CONTEXT_4: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/responses/200/content/application~1json/schema',
    operation_id='/paths/~1items/get',
    media_type='application/json',
)


@cache
def codec_4() -> PydanticModelCodec[plan_oas30_models.Item]:
    """Codec of /paths/~1items/get response_body (response 200 application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Item|ModelNode(symbol='plan_oas30_models:Item')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1items/get/responses/200/content/application~1json/schema',
            operation_id='/paths/~1items/get',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='plan_oas30_models:Item',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='plan_oas30_models:Item'),
            models=(_model_4(), _model_5()),
        ),
        plan_oas30_models.Item,
        {'plan_oas30_models:Item': plan_oas30_models.Item, 'plan_oas30_models:Tag': plan_oas30_models.Tag},
        response_bundle,
    )


@cache
def outbound_4() -> NativeOutboundCodec[plan_oas30_models.Item]:
    return NativeOutboundCodec(codec_4(), CONTEXT_4)
