# Generated by datamodel-code-generator; target=client; schema_version=1
"""Model codec bindings of this generated package; regenerate them instead of editing."""

from __future__ import annotations

from functools import cache
from typing import Final

import models

from .._runtime.model_codecs.bindings import (
    ArrayNode,
    FieldBinding,
    LeafNode,
    ModelBinding,
    ModelNode,
    UnionNode,
    UseBinding,
)
from .._runtime.model_codecs.context import CodecContext
from .._runtime.model_codecs.outbound import EnvelopeOutboundCodec, NativeOutboundCodec
from .._runtime.model_codecs.schema import (
    DirectionalView,
    SchemaBundle,
    SchemaPatch,
    SchemaResource,
)
from .._runtime.model_codecs.structural import StructuralModelCodec
from .._runtime.model_codecs.wire import freeze_wire


@cache
def _resources() -> tuple[SchemaResource, ...]:
    return (
        SchemaResource(
            uri='https://dcg.invalid/inputs/root',
            contents=freeze_wire({
                'components': {
                    'schemas': {
                        'Address': {
                            'type': 'object',
                            'properties': {
                                'city': {'type': 'string'},
                                'codes': {'type': 'array', 'items': {'type': 'integer'}},
                            },
                        },
                        'Draft': {
                            'type': 'object',
                            'required': ['id', 'title', 'secret'],
                            'properties': {
                                'id': {'type': 'integer', 'readOnly': True},
                                'title': {'type': 'string'},
                                'secret': {'type': 'string', 'writeOnly': True},
                            },
                        },
                    },
                },
                'paths': {
                    '/anything': {'post': {'requestBody': {'content': {'multipart/form-data': {'schema': {}}}}}},
                    '/attachments': {
                        'get': {
                            'responses': {
                                '202': {
                                    'content': {
                                        'multipart/form-data': {
                                            'schema': {
                                                'type': 'object',
                                                'properties': {'id': {'type': 'integer'}},
                                                'additionalProperties': False,
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/avatars': {
                        'post': {
                            'requestBody': {
                                'content': {
                                    'application/json': {
                                        'schema': {
                                            '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Address',
                                        },
                                    },
                                    'multipart/form-data': {
                                        'schema': {
                                            'type': 'object',
                                            'properties': {
                                                'caption': {'type': 'string'},
                                                'avatar': {'type': 'string', 'format': 'binary'},
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/documents': {
                        'post': {
                            'requestBody': {
                                'content': {
                                    'application/vnd.api+json': {
                                        'schema': {'$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Draft'},
                                    },
                                },
                            },
                            'responses': {
                                '3XX': {
                                    'content': {
                                        'application/json': {
                                            'schema': {
                                                '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Draft',
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/documents/{id}': {
                        'get': {
                            'parameters': [
                                {
                                    'content': {
                                        'application/json': {
                                            'schema': {'type': 'object', 'properties': {'key': {'type': 'string'}}},
                                        },
                                    },
                                },
                            ],
                            'responses': {
                                '200': {
                                    'content': {
                                        'application/vnd.api+json': {
                                            'schema': {
                                                '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Draft',
                                            },
                                        },
                                    },
                                    'headers': {
                                        'X-Draft': {
                                            'schema': {
                                                '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Draft',
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/forms': {
                        'post': {
                            'requestBody': {
                                'content': {
                                    'application/x-www-form-urlencoded': {
                                        'schema': {
                                            'type': 'object',
                                            'required': ['name'],
                                            'properties': {
                                                'name': {'type': 'string'},
                                                'count': {'type': 'integer'},
                                                'labels': {'type': 'array', 'items': {'type': 'string'}},
                                            },
                                        },
                                    },
                                },
                            },
                            'responses': {
                                '200': {
                                    'content': {
                                        'application/x-www-form-urlencoded': {
                                            'schema': {
                                                'type': 'object',
                                                'properties': {
                                                    'name': {'type': 'string'},
                                                    'count': {'type': 'integer'},
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/labels': {
                        'post': {
                            'requestBody': {
                                'content': {
                                    'multipart/form-data': {
                                        'schema': {
                                            'type': 'object',
                                            'properties': {'sheet': {'type': 'string', 'format': 'binary'}},
                                            'additionalProperties': {'type': 'string'},
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/photos': {
                        'post': {
                            'requestBody': {
                                'content': {
                                    'multipart/form-data': {
                                        'schema': {
                                            'type': 'object',
                                            'required': ['photo'],
                                            'properties': {'photo': {'type': 'string', 'format': 'binary'}},
                                            'additionalProperties': False,
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/profiles': {
                        'get': {
                            'responses': {
                                '200': {
                                    'content': {
                                        'multipart/form-data': {
                                            'schema': {
                                                'type': 'object',
                                                'required': ['name'],
                                                'properties': {
                                                    'name': {'type': 'string'},
                                                    'age': {'type': 'integer'},
                                                    'score': {'type': 'number'},
                                                    'ratio': {'type': ['integer', 'number']},
                                                    'active': {'type': 'boolean'},
                                                    'tags': {'type': 'array', 'items': {'type': 'string'}},
                                                    'address': {
                                                        '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Address',
                                                    },
                                                },
                                                'additionalProperties': {'type': 'integer'},
                                            },
                                        },
                                    },
                                },
                            },
                        },
                        'post': {
                            'requestBody': {
                                'content': {
                                    'multipart/form-data': {
                                        'schema': {
                                            'type': 'object',
                                            'required': ['name'],
                                            'properties': {
                                                'name': {'type': 'string'},
                                                'age': {'type': 'integer'},
                                                'active': {'type': 'boolean'},
                                                'tags': {'type': 'array', 'items': {'type': 'string'}},
                                                'address': {
                                                    '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Address',
                                                },
                                                'nickname': {'type': ['string', 'null']},
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/scans': {
                        'post': {
                            'requestBody': {
                                'content': {
                                    'multipart/form-data': {
                                        'schema': {
                                            'type': 'object',
                                            'properties': {'note': {'type': 'string'}},
                                            'additionalProperties': {'type': 'string', 'format': 'binary'},
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/uploads': {
                        'get': {
                            'responses': {
                                '200': {
                                    'content': {
                                        'multipart/form-data': {
                                            'schema': {
                                                'type': 'object',
                                                'required': ['title', 'photo', 'secret'],
                                                'properties': {
                                                    'title': {'type': 'string'},
                                                    'count': {'type': 'integer'},
                                                    'tags': {'type': 'array', 'items': {'type': 'string'}},
                                                    'meta': {
                                                        '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Address',
                                                    },
                                                    'draft': {
                                                        '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Draft',
                                                    },
                                                    'photo': {'type': 'string', 'format': 'binary'},
                                                    'pages': {
                                                        'type': 'array',
                                                        'items': {
                                                            'type': 'string',
                                                            'contentMediaType': 'application/pdf',
                                                        },
                                                    },
                                                    'secret': {'type': 'string', 'writeOnly': True},
                                                },
                                                'additionalProperties': {'type': 'integer'},
                                            },
                                        },
                                    },
                                },
                                '201': {
                                    'content': {
                                        'multipart/form-data': {
                                            'schema': {
                                                'type': 'object',
                                                'properties': {'note': {'type': 'string'}},
                                                'additionalProperties': {'type': 'string', 'format': 'binary'},
                                            },
                                        },
                                    },
                                },
                                '202': {
                                    'content': {
                                        'multipart/form-data': {
                                            'schema': {
                                                'type': 'object',
                                                'properties': {'photo': {'type': 'string', 'format': 'binary'}},
                                            },
                                        },
                                    },
                                },
                                '203': {
                                    'content': {
                                        'multipart/form-data': {
                                            'schema': {
                                                'type': 'object',
                                                'properties': {'photo': {'type': 'string', 'format': 'binary'}},
                                                'additionalProperties': False,
                                            },
                                        },
                                    },
                                },
                            },
                        },
                        'post': {
                            'requestBody': {
                                'content': {
                                    'multipart/form-data': {
                                        'schema': {
                                            'type': 'object',
                                            'required': ['id', 'title', 'photo'],
                                            'properties': {
                                                'id': {'type': 'integer', 'readOnly': True},
                                                'title': {'type': 'string'},
                                                'count': {'type': 'integer'},
                                                'tags': {'type': 'array', 'items': {'type': 'string'}},
                                                'meta': {
                                                    '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Address',
                                                },
                                                'photo': {'type': 'string', 'format': 'binary'},
                                                'pages': {
                                                    'type': 'array',
                                                    'items': {'type': 'string', 'contentMediaType': 'application/pdf'},
                                                },
                                            },
                                            'additionalProperties': {'type': 'integer'},
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            }),
            roots=(
                '/components/schemas/Address',
                '/components/schemas/Draft',
                '/paths/~1anything/post/requestBody/content/multipart~1form-data/schema',
                '/paths/~1attachments/get/responses/202/content/multipart~1form-data/schema',
                '/paths/~1avatars/post/requestBody/content/application~1json/schema',
                '/paths/~1avatars/post/requestBody/content/multipart~1form-data/schema',
                '/paths/~1documents/post/requestBody/content/application~1vnd.api+json/schema',
                '/paths/~1documents/post/responses/3XX/content/application~1json/schema',
                '/paths/~1documents~1{id}/get/parameters/0/content/application~1json/schema',
                '/paths/~1documents~1{id}/get/responses/200/content/application~1vnd.api+json/schema',
                '/paths/~1documents~1{id}/get/responses/200/headers/X-Draft/schema',
                '/paths/~1forms/post/requestBody/content/application~1x-www-form-urlencoded/schema',
                '/paths/~1forms/post/responses/200/content/application~1x-www-form-urlencoded/schema',
                '/paths/~1labels/post/requestBody/content/multipart~1form-data/schema',
                '/paths/~1photos/post/requestBody/content/multipart~1form-data/schema',
                '/paths/~1profiles/get/responses/200/content/multipart~1form-data/schema',
                '/paths/~1profiles/post/requestBody/content/multipart~1form-data/schema',
                '/paths/~1scans/post/requestBody/content/multipart~1form-data/schema',
                '/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema',
                '/paths/~1uploads/get/responses/201/content/multipart~1form-data/schema',
                '/paths/~1uploads/get/responses/202/content/multipart~1form-data/schema',
                '/paths/~1uploads/get/responses/203/content/multipart~1form-data/schema',
                '/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema',
            ),
        ),
    )


@cache
def _request_view() -> DirectionalView:
    return DirectionalView(
        direction='request',
        patches=(
            SchemaPatch(
                uri='https://dcg.invalid/inputs/root',
                pointer='/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema',
                keyword='required',
                value=('title', 'photo'),
            ),
            SchemaPatch(
                uri='https://dcg.invalid/inputs/root',
                pointer='/components/schemas/Draft',
                keyword='required',
                value=('title', 'secret'),
            ),
        ),
        flagged=(
            'https://dcg.invalid/inputs/root#/paths/~1documents/post/requestBody/content/application~1vnd.api+json/schema',
            'https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema',
            'https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/id',
        ),
    )


@cache
def _response_view() -> DirectionalView:
    return DirectionalView(
        direction='response',
        patches=(
            SchemaPatch(
                uri='https://dcg.invalid/inputs/root',
                pointer='/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema',
                keyword='required',
                value=('title', 'photo'),
            ),
            SchemaPatch(
                uri='https://dcg.invalid/inputs/root',
                pointer='/components/schemas/Draft',
                keyword='required',
                value=('id', 'title'),
            ),
        ),
        flagged=(
            'https://dcg.invalid/inputs/root#/paths/~1documents/post/responses/3XX/content/application~1json/schema',
            'https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/responses/200/content/application~1vnd.api+json/schema',
            'https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/responses/200/headers/X-Draft/schema',
            'https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema',
            'https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/draft',
            'https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/secret',
        ),
    )


@cache
def request_bundle() -> SchemaBundle:
    return SchemaBundle(_resources(), _request_view())


@cache
def response_bundle() -> SchemaBundle:
    return SchemaBundle(_resources(), _response_view())


@cache
def _model_0() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldFormsPostRequest',
        native_kind='typed_dict',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:FieldFormsPostRequest.name',
                native_name='name',
                wire_name='name',
                validation_key='name',
                validation_keys=('name',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldFormsPostRequest.count',
                native_name='count',
                wire_name='count',
                validation_key='count',
                validation_keys=('count',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldFormsPostRequest.labels',
                native_name='labels',
                wire_name='labels',
                validation_key='labels',
                validation_keys=('labels',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=ArrayNode(item=LeafNode()),
            ),
        ),
    )


@cache
def _model_1() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldFormsPostResponse',
        native_kind='typed_dict',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:FieldFormsPostResponse.name',
                native_name='name',
                wire_name='name',
                validation_key='name',
                validation_keys=('name',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldFormsPostResponse.count',
                native_name='count',
                wire_name='count',
                validation_key='count',
                validation_keys=('count',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
        ),
    )


@cache
def _model_2() -> ModelBinding:
    return ModelBinding(
        symbol='models:Address',
        native_kind='typed_dict',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:Address.city',
                native_name='city',
                wire_name='city',
                validation_key='city',
                validation_keys=('city',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:Address.codes',
                native_name='codes',
                wire_name='codes',
                validation_key='codes',
                validation_keys=('codes',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=ArrayNode(item=LeafNode()),
            ),
        ),
    )


@cache
def _model_3() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldProfilesPostRequest',
        native_kind='typed_dict',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:FieldProfilesPostRequest.name',
                native_name='name',
                wire_name='name',
                validation_key='name',
                validation_keys=('name',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldProfilesPostRequest.age',
                native_name='age',
                wire_name='age',
                validation_key='age',
                validation_keys=('age',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldProfilesPostRequest.active',
                native_name='active',
                wire_name='active',
                validation_key='active',
                validation_keys=('active',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldProfilesPostRequest.tags',
                native_name='tags',
                wire_name='tags',
                validation_key='tags',
                validation_keys=('tags',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=ArrayNode(item=LeafNode()),
            ),
            FieldBinding(
                field_id='models:FieldProfilesPostRequest.address',
                native_name='address',
                wire_name='address',
                validation_key='address',
                validation_keys=('address',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=ModelNode(symbol='models:Address'),
            ),
            FieldBinding(
                field_id='models:FieldProfilesPostRequest.nickname',
                native_name='nickname',
                wire_name='nickname',
                validation_key='nickname',
                validation_keys=('nickname',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=UnionNode(members=(LeafNode(),), nullable=True),
            ),
        ),
    )


@cache
def _model_4() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldProfilesGetResponse',
        native_kind='typed_dict',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:FieldProfilesGetResponse.name',
                native_name='name',
                wire_name='name',
                validation_key='name',
                validation_keys=('name',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldProfilesGetResponse.age',
                native_name='age',
                wire_name='age',
                validation_key='age',
                validation_keys=('age',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldProfilesGetResponse.score',
                native_name='score',
                wire_name='score',
                validation_key='score',
                validation_keys=('score',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldProfilesGetResponse.ratio',
                native_name='ratio',
                wire_name='ratio',
                validation_key='ratio',
                validation_keys=('ratio',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=UnionNode(members=(LeafNode(), LeafNode())),
            ),
            FieldBinding(
                field_id='models:FieldProfilesGetResponse.active',
                native_name='active',
                wire_name='active',
                validation_key='active',
                validation_keys=('active',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:FieldProfilesGetResponse.tags',
                native_name='tags',
                wire_name='tags',
                validation_key='tags',
                validation_keys=('tags',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=ArrayNode(item=LeafNode()),
            ),
            FieldBinding(
                field_id='models:FieldProfilesGetResponse.address',
                native_name='address',
                wire_name='address',
                validation_key='address',
                validation_keys=('address',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=ModelNode(symbol='models:Address'),
            ),
        ),
        extra='allow',
        extra_items=LeafNode(),
    )


@cache
def _model_5() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldAttachmentsGetResponse',
        native_kind='typed_dict',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:FieldAttachmentsGetResponse.id',
                native_name='id',
                wire_name='id',
                validation_key='id',
                validation_keys=('id',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
        ),
        extra='forbid',
    )


@cache
def _model_6() -> ModelBinding:
    return ModelBinding(
        symbol='models:Draft',
        native_kind='typed_dict',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:Draft.id',
                native_name='id',
                wire_name='id',
                validation_key='id',
                validation_keys=('id',),
                required=True,
                read_only=True,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:Draft.title',
                native_name='title',
                wire_name='title',
                validation_key='title',
                validation_keys=('title',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:Draft.secret',
                native_name='secret',
                wire_name='secret',
                validation_key='secret',
                validation_keys=('secret',),
                required=True,
                read_only=False,
                write_only=True,
                omit_none=False,
                type=LeafNode(),
            ),
        ),
    )


@cache
def _model_7() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldDocumentsIdGetPathIdParameter',
        native_kind='typed_dict',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:FieldDocumentsIdGetPathIdParameter.key',
                native_name='key',
                wire_name='key',
                validation_key='key',
                validation_keys=('key',),
                required=False,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
        ),
    )


CONTEXT_0: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1forms/post/requestBody/content/application~1x-www-form-urlencoded/schema',
    operation_id='/paths/~1forms/post',
    media_type='application/x-www-form-urlencoded',
)


@cache
def codec_0() -> StructuralModelCodec[models.FieldFormsPostRequest]:
    """Codec of /paths/~1forms/post request_body (request application/x-www-form-urlencoded)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1forms/post/requestBody/content/application~1x-www-form-urlencoded/schema|ModelNode(symbol='models:FieldFormsPostRequest')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1forms/post/requestBody/content/application~1x-www-form-urlencoded/schema',
            operation_id='/paths/~1forms/post',
            media_type='application/x-www-form-urlencoded',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:FieldFormsPostRequest',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:FieldFormsPostRequest'),
            models=(_model_0(),),
        ),
        models.FieldFormsPostRequest,
        {'models:FieldFormsPostRequest': models.FieldFormsPostRequest},
        request_bundle(),
    )


@cache
def outbound_0() -> NativeOutboundCodec[models.FieldFormsPostRequest]:
    return NativeOutboundCodec(codec_0(), CONTEXT_0)


CONTEXT_1: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1forms/post/responses/200/content/application~1x-www-form-urlencoded/schema',
    operation_id='/paths/~1forms/post',
    media_type='application/x-www-form-urlencoded',
)


@cache
def codec_1() -> StructuralModelCodec[models.FieldFormsPostResponse]:
    """Codec of /paths/~1forms/post response_body (response 200 application/x-www-form-urlencoded)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1forms/post/responses/200/content/application~1x-www-form-urlencoded/schema|ModelNode(symbol='models:FieldFormsPostResponse')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1forms/post/responses/200/content/application~1x-www-form-urlencoded/schema',
            operation_id='/paths/~1forms/post',
            media_type='application/x-www-form-urlencoded',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:FieldFormsPostResponse',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:FieldFormsPostResponse'),
            models=(_model_1(),),
        ),
        models.FieldFormsPostResponse,
        {'models:FieldFormsPostResponse': models.FieldFormsPostResponse},
        response_bundle(),
    )


CONTEXT_2: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1profiles/post/requestBody/content/multipart~1form-data/schema',
    operation_id='/paths/~1profiles/post',
    media_type='multipart/form-data',
)


@cache
def codec_2() -> StructuralModelCodec[models.FieldProfilesPostRequest]:
    """Codec of /paths/~1profiles/post request_body (request multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1profiles/post/requestBody/content/multipart~1form-data/schema|ModelNode(symbol='models:FieldProfilesPostRequest')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1profiles/post/requestBody/content/multipart~1form-data/schema',
            operation_id='/paths/~1profiles/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:FieldProfilesPostRequest',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:FieldProfilesPostRequest'),
            models=(_model_2(), _model_3()),
        ),
        models.FieldProfilesPostRequest,
        {'models:Address': models.Address, 'models:FieldProfilesPostRequest': models.FieldProfilesPostRequest},
        request_bundle(),
    )


@cache
def outbound_2() -> NativeOutboundCodec[models.FieldProfilesPostRequest]:
    return NativeOutboundCodec(codec_2(), CONTEXT_2)


CONTEXT_3: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1profiles/get/responses/200/content/multipart~1form-data/schema',
    operation_id='/paths/~1profiles/get',
    media_type='multipart/form-data',
)


@cache
def codec_3() -> StructuralModelCodec[models.FieldProfilesGetResponse]:
    """Codec of /paths/~1profiles/get response_body (response 200 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1profiles/get/responses/200/content/multipart~1form-data/schema|ModelNode(symbol='models:FieldProfilesGetResponse')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1profiles/get/responses/200/content/multipart~1form-data/schema',
            operation_id='/paths/~1profiles/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:FieldProfilesGetResponse',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:FieldProfilesGetResponse'),
            models=(_model_2(), _model_4()),
        ),
        models.FieldProfilesGetResponse,
        {'models:Address': models.Address, 'models:FieldProfilesGetResponse': models.FieldProfilesGetResponse},
        response_bundle(),
    )


CONTEXT_4: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1anything/post/requestBody/content/multipart~1form-data/schema',
    operation_id='/paths/~1anything/post',
    media_type='multipart/form-data',
)


@cache
def codec_4() -> StructuralModelCodec[models.FieldAnythingPostRequest]:
    """Codec of /paths/~1anything/post request_body (request multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1anything/post/requestBody/content/multipart~1form-data/schema|LeafNode(representation='value')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1anything/post/requestBody/content/multipart~1form-data/schema',
            operation_id='/paths/~1anything/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='alias',
            native_export='models:FieldAnythingPostRequest',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        models.FieldAnythingPostRequest,
        {},
        request_bundle(),
    )


@cache
def outbound_4() -> NativeOutboundCodec[models.FieldAnythingPostRequest]:
    return NativeOutboundCodec(codec_4(), CONTEXT_4)


CONTEXT_5: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1attachments/get/responses/202/content/multipart~1form-data/schema',
    operation_id='/paths/~1attachments/get',
    media_type='multipart/form-data',
)


@cache
def codec_5() -> StructuralModelCodec[models.FieldAttachmentsGetResponse]:
    """Codec of /paths/~1attachments/get response_body (response 202 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1attachments/get/responses/202/content/multipart~1form-data/schema|ModelNode(symbol='models:FieldAttachmentsGetResponse')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1attachments/get/responses/202/content/multipart~1form-data/schema',
            operation_id='/paths/~1attachments/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:FieldAttachmentsGetResponse',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:FieldAttachmentsGetResponse'),
            models=(_model_5(),),
        ),
        models.FieldAttachmentsGetResponse,
        {'models:FieldAttachmentsGetResponse': models.FieldAttachmentsGetResponse},
        response_bundle(),
    )


CONTEXT_6: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1avatars/post/requestBody/content/application~1json/schema',
    operation_id='/paths/~1avatars/post',
    media_type='application/json',
)


@cache
def codec_6() -> StructuralModelCodec[models.Address]:
    """Codec of /paths/~1avatars/post request_body (request application/json)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Address|ModelNode(symbol='models:Address')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1avatars/post/requestBody/content/application~1json/schema',
            operation_id='/paths/~1avatars/post',
            media_type='application/json',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:Address',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:Address'),
            models=(_model_2(),),
        ),
        models.Address,
        {'models:Address': models.Address},
        request_bundle(),
    )


@cache
def outbound_6() -> NativeOutboundCodec[models.Address]:
    return NativeOutboundCodec(codec_6(), CONTEXT_6)


CONTEXT_7: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1documents/post/requestBody/content/application~1vnd.api+json/schema',
    operation_id='/paths/~1documents/post',
    media_type='application/vnd.api+json',
)


@cache
def codec_7() -> StructuralModelCodec[models.Draft]:
    """Codec of /paths/~1documents/post request_body (request application/vnd.api+json)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Draft|ModelNode(symbol='models:Draft')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1documents/post/requestBody/content/application~1vnd.api+json/schema',
            operation_id='/paths/~1documents/post',
            media_type='application/vnd.api+json',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:Draft',
            projection_mode='envelope',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:Draft'),
            models=(_model_6(),),
        ),
        models.Draft,
        {'models:Draft': models.Draft},
        request_bundle(),
    )


@cache
def outbound_7() -> EnvelopeOutboundCodec[models.Draft]:
    return EnvelopeOutboundCodec(codec_7(), CONTEXT_7)


CONTEXT_8: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1documents/post/responses/3XX/content/application~1json/schema',
    operation_id='/paths/~1documents/post',
    media_type='application/json',
)


@cache
def codec_8() -> StructuralModelCodec[models.Draft]:
    """Codec of /paths/~1documents/post response_body (response 3XX application/json)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Draft|ModelNode(symbol='models:Draft')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1documents/post/responses/3XX/content/application~1json/schema',
            operation_id='/paths/~1documents/post',
            media_type='application/json',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:Draft',
            projection_mode='envelope',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:Draft'),
            models=(_model_6(),),
        ),
        models.Draft,
        {'models:Draft': models.Draft},
        response_bundle(),
    )


CONTEXT_9: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/parameters/0/content/application~1json/schema',
    operation_id='/paths/~1documents~1{id}/get',
    media_type='application/json',
)


@cache
def codec_9() -> StructuralModelCodec[models.FieldDocumentsIdGetPathIdParameter]:
    """Codec of /paths/~1documents~1{id}/get parameter (request path id application/json)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/parameters/0/content/application~1json/schema|ModelNode(symbol='models:FieldDocumentsIdGetPathIdParameter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/parameters/0/content/application~1json/schema',
            operation_id='/paths/~1documents~1{id}/get',
            media_type='application/json',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:FieldDocumentsIdGetPathIdParameter',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:FieldDocumentsIdGetPathIdParameter'),
            models=(_model_7(),),
        ),
        models.FieldDocumentsIdGetPathIdParameter,
        {'models:FieldDocumentsIdGetPathIdParameter': models.FieldDocumentsIdGetPathIdParameter},
        request_bundle(),
    )


@cache
def outbound_9() -> NativeOutboundCodec[models.FieldDocumentsIdGetPathIdParameter]:
    return NativeOutboundCodec(codec_9(), CONTEXT_9)


CONTEXT_10: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/responses/200/content/application~1vnd.api+json/schema',
    operation_id='/paths/~1documents~1{id}/get',
    media_type='application/vnd.api+json',
)


@cache
def codec_10() -> StructuralModelCodec[models.Draft]:
    """Codec of /paths/~1documents~1{id}/get response_body (response 200 application/vnd.api+json)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Draft|ModelNode(symbol='models:Draft')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/responses/200/content/application~1vnd.api+json/schema',
            operation_id='/paths/~1documents~1{id}/get',
            media_type='application/vnd.api+json',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:Draft',
            projection_mode='envelope',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:Draft'),
            models=(_model_6(),),
        ),
        models.Draft,
        {'models:Draft': models.Draft},
        response_bundle(),
    )


CONTEXT_11: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/responses/200/headers/X-Draft/schema',
    operation_id='/paths/~1documents~1{id}/get',
)


@cache
def codec_11() -> StructuralModelCodec[models.Draft]:
    """Codec of /paths/~1documents~1{id}/get response_header (response X-Draft 200)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Draft|ModelNode(symbol='models:Draft')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1documents~1%7Bid%7D/get/responses/200/headers/X-Draft/schema',
            operation_id='/paths/~1documents~1{id}/get',
            media_type=None,
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:Draft',
            projection_mode='envelope',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:Draft'),
            models=(_model_6(),),
        ),
        models.Draft,
        {'models:Draft': models.Draft},
        response_bundle(),
    )


CONTEXT_12: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/id',
    operation_id='/paths/~1uploads/post',
    media_type='multipart/form-data',
)


@cache
def codec_12() -> StructuralModelCodec[int]:
    """Codec of /paths/~1uploads/post request_body (request id multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/id|LeafNode(representation='value')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/id',
            operation_id='/paths/~1uploads/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        int,
        {},
        request_bundle(),
    )


@cache
def outbound_12() -> NativeOutboundCodec[int]:
    return NativeOutboundCodec(codec_12(), CONTEXT_12)


CONTEXT_13: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/title',
    operation_id='/paths/~1uploads/post',
    media_type='multipart/form-data',
)


@cache
def codec_13() -> StructuralModelCodec[str]:
    """Codec of /paths/~1uploads/post request_body (request title multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/title|LeafNode(representation='value')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/title',
            operation_id='/paths/~1uploads/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        str,
        {},
        request_bundle(),
    )


@cache
def outbound_13() -> NativeOutboundCodec[str]:
    return NativeOutboundCodec(codec_13(), CONTEXT_13)


CONTEXT_14: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/count',
    operation_id='/paths/~1uploads/post',
    media_type='multipart/form-data',
)


@cache
def codec_14() -> StructuralModelCodec[int]:
    """Codec of /paths/~1uploads/post request_body (request count multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/count|LeafNode(representation='value')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/count',
            operation_id='/paths/~1uploads/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        int,
        {},
        request_bundle(),
    )


@cache
def outbound_14() -> NativeOutboundCodec[int]:
    return NativeOutboundCodec(codec_14(), CONTEXT_14)


CONTEXT_15: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/tags',
    operation_id='/paths/~1uploads/post',
    media_type='multipart/form-data',
)


@cache
def codec_15() -> StructuralModelCodec[list[str]]:
    """Codec of /paths/~1uploads/post request_body (request tags multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/tags|ArrayNode(item=LeafNode(representation='value'), container='list')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/tags',
            operation_id='/paths/~1uploads/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='array',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ArrayNode(item=LeafNode()),
            models=(),
        ),
        list[str],
        {},
        request_bundle(),
    )


@cache
def outbound_15() -> NativeOutboundCodec[list[str]]:
    return NativeOutboundCodec(codec_15(), CONTEXT_15)


CONTEXT_16: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/meta',
    operation_id='/paths/~1uploads/post',
    media_type='multipart/form-data',
)


@cache
def codec_16() -> StructuralModelCodec[models.Address]:
    """Codec of /paths/~1uploads/post request_body (request meta multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Address|ModelNode(symbol='models:Address')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/properties/meta',
            operation_id='/paths/~1uploads/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:Address',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:Address'),
            models=(_model_2(),),
        ),
        models.Address,
        {'models:Address': models.Address},
        request_bundle(),
    )


@cache
def outbound_16() -> NativeOutboundCodec[models.Address]:
    return NativeOutboundCodec(codec_16(), CONTEXT_16)


CONTEXT_17: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/additionalProperties',
    operation_id='/paths/~1uploads/post',
    media_type='multipart/form-data',
)


@cache
def codec_17() -> StructuralModelCodec[int]:
    """Codec of /paths/~1uploads/post request_body (request multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/additionalProperties|LeafNode(representation='value')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/post/requestBody/content/multipart~1form-data/schema/additionalProperties',
            operation_id='/paths/~1uploads/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        int,
        {},
        request_bundle(),
    )


@cache
def outbound_17() -> NativeOutboundCodec[int]:
    return NativeOutboundCodec(codec_17(), CONTEXT_17)


CONTEXT_18: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/title',
    operation_id='/paths/~1uploads/get',
    media_type='multipart/form-data',
)


@cache
def codec_18() -> StructuralModelCodec[str]:
    """Codec of /paths/~1uploads/get response_body (response title 200 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/title|LeafNode(representation='value')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/title',
            operation_id='/paths/~1uploads/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        str,
        {},
        response_bundle(),
    )


CONTEXT_19: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/count',
    operation_id='/paths/~1uploads/get',
    media_type='multipart/form-data',
)


@cache
def codec_19() -> StructuralModelCodec[int]:
    """Codec of /paths/~1uploads/get response_body (response count 200 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/count|LeafNode(representation='value')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/count',
            operation_id='/paths/~1uploads/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        int,
        {},
        response_bundle(),
    )


CONTEXT_20: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/tags/items',
    operation_id='/paths/~1uploads/get',
    media_type='multipart/form-data',
)


@cache
def codec_20() -> StructuralModelCodec[str]:
    """Codec of /paths/~1uploads/get response_body (response tags 200 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/tags/items|LeafNode(representation='value')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/tags/items',
            operation_id='/paths/~1uploads/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        str,
        {},
        response_bundle(),
    )


CONTEXT_21: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/meta',
    operation_id='/paths/~1uploads/get',
    media_type='multipart/form-data',
)


@cache
def codec_21() -> StructuralModelCodec[models.Address]:
    """Codec of /paths/~1uploads/get response_body (response meta 200 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Address|ModelNode(symbol='models:Address')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/meta',
            operation_id='/paths/~1uploads/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:Address',
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:Address'),
            models=(_model_2(),),
        ),
        models.Address,
        {'models:Address': models.Address},
        response_bundle(),
    )


CONTEXT_22: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/draft',
    operation_id='/paths/~1uploads/get',
    media_type='multipart/form-data',
)


@cache
def codec_22() -> StructuralModelCodec[models.Draft]:
    """Codec of /paths/~1uploads/get response_body (response draft 200 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Draft|ModelNode(symbol='models:Draft')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/draft',
            operation_id='/paths/~1uploads/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='typed_dict',
            native_export='models:Draft',
            projection_mode='envelope',
            converter_strategy='typeddict_structural',
            type=ModelNode(symbol='models:Draft'),
            models=(_model_6(),),
        ),
        models.Draft,
        {'models:Draft': models.Draft},
        response_bundle(),
    )


CONTEXT_23: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/secret',
    operation_id='/paths/~1uploads/get',
    media_type='multipart/form-data',
)


@cache
def codec_23() -> StructuralModelCodec[str]:
    """Codec of /paths/~1uploads/get response_body (response secret 200 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/secret|LeafNode(representation='value')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/properties/secret',
            operation_id='/paths/~1uploads/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        str,
        {},
        response_bundle(),
    )


CONTEXT_24: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/additionalProperties',
    operation_id='/paths/~1uploads/get',
    media_type='multipart/form-data',
)


@cache
def codec_24() -> StructuralModelCodec[int]:
    """Codec of /paths/~1uploads/get response_body (response 200 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/additionalProperties|LeafNode(representation='value')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/200/content/multipart~1form-data/schema/additionalProperties',
            operation_id='/paths/~1uploads/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        int,
        {},
        response_bundle(),
    )


CONTEXT_25: Final = CodecContext(
    surface='client',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/201/content/multipart~1form-data/schema/properties/note',
    operation_id='/paths/~1uploads/get',
    media_type='multipart/form-data',
)


@cache
def codec_25() -> StructuralModelCodec[str]:
    """Codec of /paths/~1uploads/get response_body (response note 201 multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/201/content/multipart~1form-data/schema/properties/note|LeafNode(representation='value')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1uploads/get/responses/201/content/multipart~1form-data/schema/properties/note',
            operation_id='/paths/~1uploads/get',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        str,
        {},
        response_bundle(),
    )


CONTEXT_26: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1avatars/post/requestBody/content/multipart~1form-data/schema/properties/caption',
    operation_id='/paths/~1avatars/post',
    media_type='multipart/form-data',
)


@cache
def codec_26() -> StructuralModelCodec[str]:
    """Codec of /paths/~1avatars/post request_body (request caption multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1avatars/post/requestBody/content/multipart~1form-data/schema/properties/caption|LeafNode(representation='value')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1avatars/post/requestBody/content/multipart~1form-data/schema/properties/caption',
            operation_id='/paths/~1avatars/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        str,
        {},
        request_bundle(),
    )


@cache
def outbound_26() -> NativeOutboundCodec[str]:
    return NativeOutboundCodec(codec_26(), CONTEXT_26)


CONTEXT_27: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1scans/post/requestBody/content/multipart~1form-data/schema/properties/note',
    operation_id='/paths/~1scans/post',
    media_type='multipart/form-data',
)


@cache
def codec_27() -> StructuralModelCodec[str]:
    """Codec of /paths/~1scans/post request_body (request note multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1scans/post/requestBody/content/multipart~1form-data/schema/properties/note|LeafNode(representation='value')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1scans/post/requestBody/content/multipart~1form-data/schema/properties/note',
            operation_id='/paths/~1scans/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        str,
        {},
        request_bundle(),
    )


@cache
def outbound_27() -> NativeOutboundCodec[str]:
    return NativeOutboundCodec(codec_27(), CONTEXT_27)


CONTEXT_28: Final = CodecContext(
    surface='client',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1labels/post/requestBody/content/multipart~1form-data/schema/additionalProperties',
    operation_id='/paths/~1labels/post',
    media_type='multipart/form-data',
)


@cache
def codec_28() -> StructuralModelCodec[str]:
    """Codec of /paths/~1labels/post request_body (request multipart/form-data)."""
    return StructuralModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1labels/post/requestBody/content/multipart~1form-data/schema/additionalProperties|LeafNode(representation='value')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1labels/post/requestBody/content/multipart~1form-data/schema/additionalProperties',
            operation_id='/paths/~1labels/post',
            media_type='multipart/form-data',
            backend='typing.TypedDict',
            native_kind='scalar',
            native_export=None,
            projection_mode='native',
            converter_strategy='typeddict_structural',
            type=LeafNode(),
            models=(),
        ),
        str,
        {},
        request_bundle(),
    )


@cache
def outbound_28() -> NativeOutboundCodec[str]:
    return NativeOutboundCodec(codec_28(), CONTEXT_28)
