# generated by datamodel-codegen:
#   filename:  parameters.json

from __future__ import annotations
from dataclasses import dataclass
from typing import TypeAlias



@dataclass
class Item:
    x: int | None = None



LimitParameter: TypeAlias = int



FieldXGetQueryQParameter: TypeAlias = int



FieldXGetQueryOptionalParameter: TypeAlias = str



FieldXGetQueryFilterParameter: TypeAlias = str