# generated by datamodel-codegen:
#   filename:  parameter_content.yaml

from __future__ import annotations
from pydantic import BaseModel


class ItemsGetResponse(BaseModel):
    ok: bool | None = None