# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Results, payload types, and response codecs of this package."""

from typing import Final, Literal, TypeAlias, overload

import models
from typing_extensions import Never

from ._generated import model_bindings
from ._runtime.model_codecs.outbound import NativeOutboundCodec
from ._runtime.model_codecs.unset import UNSET, Unset
from ._runtime.model_codecs.values import ModelValue
from ._runtime.server.codecs import ResponseCodecs
from ._runtime.server.responses import HTTPResult

ListPetsResponsePayload: TypeAlias = (
    models.FieldPetsGetResponse
    | ModelValue[models.FieldPetsGetResponse]
    | models.Error
    | ModelValue[models.Error]
)


_ListPetsResponseCodec: TypeAlias = (
    NativeOutboundCodec[models.FieldPetsGetResponse]
    | NativeOutboundCodec[models.Error]
)


class _ListPetsResponseCodecs(ResponseCodecs[_ListPetsResponseCodec]):
    """Outbound codecs of the list_pets response bodies."""

    @overload
    def body(
        self,
        *,
        status_code: Literal[200],
        media_type: Literal['application/json'] | None = None,
    ) -> NativeOutboundCodec[models.FieldPetsGetResponse]: ...
    @overload
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> _ListPetsResponseCodec: ...
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> _ListPetsResponseCodec:
        """Return the outbound codec of one declared response body."""
        return self.select(status_code, media_type)


ListPetsResponseCodecs: Final = _ListPetsResponseCodecs(
    (
        ('200', (('application/json', model_bindings.outbound_1),)),
        ('default', (('application/json', model_bindings.outbound_2),)),
    ),
)


CreatePetResponsePayload: TypeAlias = models.Pet | ModelValue[models.Pet]


class _CreatePetResponseCodecs(ResponseCodecs[NativeOutboundCodec[models.Pet]]):
    """Outbound codecs of the create_pet response bodies."""

    @overload
    def body(
        self,
        *,
        status_code: Literal[201],
        media_type: Literal['application/json'] | None = None,
    ) -> NativeOutboundCodec[models.Pet]: ...
    @overload
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> NativeOutboundCodec[models.Pet]: ...
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> NativeOutboundCodec[models.Pet]:
        """Return the outbound codec of one declared response body."""
        return self.select(status_code, media_type)


CreatePetResponseCodecs: Final = _CreatePetResponseCodecs(
    (('201', (('application/json', model_bindings.outbound_3),)),),
)


ListMyPetsResponsePayload: TypeAlias = (
    models.FieldPetsMineGetResponse
    | ModelValue[models.FieldPetsMineGetResponse]
)


class _ListMyPetsResponseCodecs(
    ResponseCodecs[NativeOutboundCodec[models.FieldPetsMineGetResponse]],
):
    """Outbound codecs of the list_my_pets response bodies."""

    @overload
    def body(
        self,
        *,
        status_code: Literal[200],
        media_type: Literal['application/json'] | None = None,
    ) -> NativeOutboundCodec[models.FieldPetsMineGetResponse]: ...
    @overload
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> NativeOutboundCodec[models.FieldPetsMineGetResponse]: ...
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> NativeOutboundCodec[models.FieldPetsMineGetResponse]:
        """Return the outbound codec of one declared response body."""
        return self.select(status_code, media_type)


ListMyPetsResponseCodecs: Final = _ListMyPetsResponseCodecs(
    (('200', (('application/json', model_bindings.outbound_4),)),),
)


GetPetResponsePayload: TypeAlias = (
    models.Pet
    | ModelValue[models.Pet]
    | models.Error
    | ModelValue[models.Error]
)


_GetPetResponseCodec: TypeAlias = (
    NativeOutboundCodec[models.Pet]
    | NativeOutboundCodec[models.Error]
)


class _GetPetResponseCodecs(ResponseCodecs[_GetPetResponseCodec]):
    """Outbound codecs of the get_pet response bodies."""

    @overload
    def body(
        self,
        *,
        status_code: Literal[200],
        media_type: Literal['application/json'] | None = None,
    ) -> NativeOutboundCodec[models.Pet]: ...
    @overload
    def body(
        self,
        *,
        status_code: Literal[404],
        media_type: Literal['application/json'] | None = None,
    ) -> NativeOutboundCodec[models.Error]: ...
    @overload
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> _GetPetResponseCodec: ...
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> _GetPetResponseCodec:
        """Return the outbound codec of one declared response body."""
        return self.select(status_code, media_type)


GetPetResponseCodecs: Final = _GetPetResponseCodecs(
    (
        ('200', (('application/json', model_bindings.outbound_5),)),
        ('404', (('application/json', model_bindings.outbound_6),)),
    ),
)


DeletePetResponsePayload: TypeAlias = Never


class _DeletePetResponseCodecs(ResponseCodecs[Never]):
    """Outbound codecs of the delete_pet response bodies."""


DeletePetResponseCodecs: Final = _DeletePetResponseCodecs(())


GetInventoryResponsePayload: TypeAlias = (
    models.FieldStoreInventoryGetResponse
    | ModelValue[models.FieldStoreInventoryGetResponse]
)


class _GetInventoryResponseCodecs(
    ResponseCodecs[NativeOutboundCodec[models.FieldStoreInventoryGetResponse]],
):
    """Outbound codecs of the get_inventory response bodies."""

    @overload
    def body(
        self,
        *,
        status_code: Literal[200],
        media_type: Literal['application/json'] | None = None,
    ) -> NativeOutboundCodec[models.FieldStoreInventoryGetResponse]: ...
    @overload
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> NativeOutboundCodec[models.FieldStoreInventoryGetResponse]: ...
    def body(
        self,
        *,
        status_code: int,
        media_type: str | None = None,
    ) -> NativeOutboundCodec[models.FieldStoreInventoryGetResponse]:
        """Return the outbound codec of one declared response body."""
        return self.select(status_code, media_type)


GetInventoryResponseCodecs: Final = _GetInventoryResponseCodecs(
    (('200', (('application/json', model_bindings.outbound_7),)),),
)


__all__ = [
    'CreatePetResponseCodecs',
    'CreatePetResponsePayload',
    'DeletePetResponseCodecs',
    'DeletePetResponsePayload',
    'GetInventoryResponseCodecs',
    'GetInventoryResponsePayload',
    'GetPetResponseCodecs',
    'GetPetResponsePayload',
    'HTTPResult',
    'ListMyPetsResponseCodecs',
    'ListMyPetsResponsePayload',
    'ListPetsResponseCodecs',
    'ListPetsResponsePayload',
    'UNSET',
    'Unset',
]
