# Generated by datamodel-code-generator; target=client; schema_version=1
"""The asyncio operations of the forms resource."""

from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from functools import cached_property
from typing import Any as _dcg_type_6
from typing import Literal, overload

from models import Address as _dcg_type_4
from models import Bounds as _dcg_type_9
from models import FieldAnythingPostRequest as _dcg_type_2
from models import FieldAttachmentsGetResponse as _dcg_type_3
from models import FieldCardsPostRequest as _dcg_type_7
from models import FieldFormsPostRequest as _dcg_type_0
from models import FieldProfilesPostRequest as _dcg_type_1
from models import FieldSearchesPostRequest as _dcg_type_5
from models import FieldStickersPostRequest as _dcg_type_8
from typing_extensions import Never

from ... import _operations
from ..._runtime.client.client import AsyncClientCore
from ...bodies import AsyncMultipartBody, FormData, MultipartData
from ...model_codecs import JSONValue
from ...options import UNSET, RequestOptions, Unset
from ...responses import AsyncRawResponse, Response
from ...types.forms import (
    ReadPartsResponse,
    ReadProfileResponse,
    ReadUploadResponse,
    SubmitAlbumResponse,
    SubmitAnythingResponse,
    SubmitAvatarResponse,
    SubmitCardResponse,
    SubmitCoverResponse,
    SubmitFormResponse,
    SubmitLabelsResponse,
    SubmitPairsResponse,
    SubmitPartsResponse,
    SubmitPhotosResponse,
    SubmitProfileResponse,
    SubmitScansResponse,
    SubmitSearchResponse,
    SubmitStickersResponse,
    SubmitUploadResponse,
)


class AsyncFormsResource:
    """The forms operations."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    @cached_property
    def with_response(self) -> AsyncFormsWithResponse:
        """The same operations, returning each result with its response metadata."""
        return AsyncFormsWithResponse(self._core)

    @cached_property
    def with_raw_response(self) -> AsyncFormsWithRawResponse:
        """The same operations, returning each raw response with its body read into memory."""
        return AsyncFormsWithRawResponse(self._core)

    @cached_property
    def with_streaming_response(self) -> AsyncFormsWithStreamingResponse:
        """The same operations, returning blocks that send each call on entry and stream its response."""
        return AsyncFormsWithStreamingResponse(self._core)

    async def submit_form(
        self,
        *,
        body: _dcg_type_0,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitFormResponse:
        """Call POST /forms."""
        return (await self._core.execute(
            _operations.OPERATION_0,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )).data

    async def submit_profile(
        self,
        *,
        body: _dcg_type_1,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitProfileResponse:
        """Call POST /profiles."""
        return (await self._core.execute(
            _operations.OPERATION_1,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def read_profile(
        self,
        *,
        response_media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> ReadProfileResponse:
        """Call GET /profiles."""
        return (await self._core.execute(
            _operations.OPERATION_2,
            (),
            options=options,
            response_media_type=response_media_type,
        )).data

    async def submit_anything(
        self,
        *,
        body: _dcg_type_2,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitAnythingResponse:
        """Call POST /anything."""
        return (await self._core.execute(
            _operations.OPERATION_3,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_parts(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitPartsResponse:
        """Call POST /attachments."""
        return (await self._core.execute(
            _operations.OPERATION_4,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    @overload
    async def read_parts(
        self,
        *,
        response_media_type: None = None,
        options: RequestOptions | None = None,
    ) -> ReadPartsResponse: ...
    @overload
    async def read_parts(
        self,
        *,
        response_media_type: Literal['multipart/mixed'],
        options: RequestOptions | None = None,
    ) -> MultipartData[bytes]: ...
    @overload
    async def read_parts(
        self,
        *,
        response_media_type: Literal['multipart/form-data'],
        options: RequestOptions | None = None,
    ) -> _dcg_type_3: ...
    async def read_parts(
        self,
        *,
        response_media_type: Literal['multipart/mixed', 'multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> ReadPartsResponse:
        """Call GET /attachments."""
        return (await self._core.execute(
            _operations.OPERATION_5,
            (),
            options=options,
            response_media_type=response_media_type,
        )).data

    async def submit_pairs(
        self,
        *,
        body: FormData | Unset = UNSET,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitPairsResponse:
        """Call POST /pairs."""
        return (await self._core.execute(
            _operations.OPERATION_6,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )).data

    async def submit_upload(
        self,
        *,
        body: AsyncMultipartBody[int | str | list[str] | _dcg_type_4],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitUploadResponse:
        """Call POST /uploads."""
        return (await self._core.execute(
            _operations.OPERATION_7,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def read_upload(
        self,
        *,
        response_media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> ReadUploadResponse:
        """Call GET /uploads."""
        return (await self._core.execute(
            _operations.OPERATION_8,
            (),
            options=options,
            response_media_type=response_media_type,
        )).data

    @overload
    async def submit_avatar(
        self,
        *,
        body: AsyncMultipartBody[str | JSONValue],
        media_type: Literal['multipart/form-data'],
        options: RequestOptions | None = None,
    ) -> SubmitAvatarResponse: ...
    @overload
    async def submit_avatar(
        self,
        *,
        body: _dcg_type_4,
        media_type: Literal['application/json'],
        options: RequestOptions | None = None,
    ) -> SubmitAvatarResponse: ...
    @overload
    async def submit_avatar(
        self,
        *,
        body: Unset = UNSET,
        media_type: None = None,
        options: RequestOptions | None = None,
    ) -> SubmitAvatarResponse: ...
    async def submit_avatar(
        self,
        *,
        body: AsyncMultipartBody[str | JSONValue] | _dcg_type_4 | Unset = UNSET,
        media_type: Literal['multipart/form-data', 'application/json'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitAvatarResponse:
        """Call POST /avatars."""
        return (await self._core.execute(
            _operations.OPERATION_9,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_scans(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitScansResponse:
        """Call POST /scans."""
        return (await self._core.execute(
            _operations.OPERATION_10,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_photos(
        self,
        *,
        body: AsyncMultipartBody[Never],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitPhotosResponse:
        """Call POST /photos."""
        return (await self._core.execute(
            _operations.OPERATION_11,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_labels(
        self,
        *,
        body: AsyncMultipartBody[str],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitLabelsResponse:
        """Call POST /labels."""
        return (await self._core.execute(
            _operations.OPERATION_12,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_search(
        self,
        *,
        body: _dcg_type_5,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitSearchResponse:
        """Call POST /searches."""
        return (await self._core.execute(
            _operations.OPERATION_15,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_cover(
        self,
        *,
        body: AsyncMultipartBody[str | int | _dcg_type_4 | _dcg_type_6 | JSONValue],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitCoverResponse:
        """Call POST /covers."""
        return (await self._core.execute(
            _operations.OPERATION_16,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_card(
        self,
        *,
        body: _dcg_type_7,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitCardResponse:
        """Call POST /cards."""
        return (await self._core.execute(
            _operations.OPERATION_17,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_stickers(
        self,
        *,
        body: _dcg_type_8,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitStickersResponse:
        """Call POST /stickers."""
        return (await self._core.execute(
            _operations.OPERATION_18,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_album(
        self,
        *,
        body: AsyncMultipartBody[_dcg_type_9 | str | list[str] | JSONValue],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitAlbumResponse:
        """Call POST /albums."""
        return (await self._core.execute(
            _operations.OPERATION_19,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data


class AsyncFormsWithResponse:
    """The forms operations, returning each result with its response metadata."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    async def submit_form(
        self,
        *,
        body: _dcg_type_0,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitFormResponse]:
        """Call POST /forms."""
        return await self._core.execute(
            _operations.OPERATION_0,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_profile(
        self,
        *,
        body: _dcg_type_1,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitProfileResponse]:
        """Call POST /profiles."""
        return await self._core.execute(
            _operations.OPERATION_1,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def read_profile(
        self,
        *,
        response_media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[ReadProfileResponse]:
        """Call GET /profiles."""
        return await self._core.execute(
            _operations.OPERATION_2,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_anything(
        self,
        *,
        body: _dcg_type_2,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitAnythingResponse]:
        """Call POST /anything."""
        return await self._core.execute(
            _operations.OPERATION_3,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_parts(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitPartsResponse]:
        """Call POST /attachments."""
        return await self._core.execute(
            _operations.OPERATION_4,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    @overload
    async def read_parts(
        self,
        *,
        response_media_type: None = None,
        options: RequestOptions | None = None,
    ) -> Response[ReadPartsResponse]: ...
    @overload
    async def read_parts(
        self,
        *,
        response_media_type: Literal['multipart/mixed'],
        options: RequestOptions | None = None,
    ) -> Response[MultipartData[bytes]]: ...
    @overload
    async def read_parts(
        self,
        *,
        response_media_type: Literal['multipart/form-data'],
        options: RequestOptions | None = None,
    ) -> Response[_dcg_type_3]: ...
    async def read_parts(
        self,
        *,
        response_media_type: Literal['multipart/mixed', 'multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[ReadPartsResponse]:
        """Call GET /attachments."""
        return await self._core.execute(
            _operations.OPERATION_5,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_pairs(
        self,
        *,
        body: FormData | Unset = UNSET,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitPairsResponse]:
        """Call POST /pairs."""
        return await self._core.execute(
            _operations.OPERATION_6,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_upload(
        self,
        *,
        body: AsyncMultipartBody[int | str | list[str] | _dcg_type_4],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitUploadResponse]:
        """Call POST /uploads."""
        return await self._core.execute(
            _operations.OPERATION_7,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def read_upload(
        self,
        *,
        response_media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[ReadUploadResponse]:
        """Call GET /uploads."""
        return await self._core.execute(
            _operations.OPERATION_8,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    @overload
    async def submit_avatar(
        self,
        *,
        body: AsyncMultipartBody[str | JSONValue],
        media_type: Literal['multipart/form-data'],
        options: RequestOptions | None = None,
    ) -> Response[SubmitAvatarResponse]: ...
    @overload
    async def submit_avatar(
        self,
        *,
        body: _dcg_type_4,
        media_type: Literal['application/json'],
        options: RequestOptions | None = None,
    ) -> Response[SubmitAvatarResponse]: ...
    @overload
    async def submit_avatar(
        self,
        *,
        body: Unset = UNSET,
        media_type: None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitAvatarResponse]: ...
    async def submit_avatar(
        self,
        *,
        body: AsyncMultipartBody[str | JSONValue] | _dcg_type_4 | Unset = UNSET,
        media_type: Literal['multipart/form-data', 'application/json'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitAvatarResponse]:
        """Call POST /avatars."""
        return await self._core.execute(
            _operations.OPERATION_9,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_scans(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitScansResponse]:
        """Call POST /scans."""
        return await self._core.execute(
            _operations.OPERATION_10,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_photos(
        self,
        *,
        body: AsyncMultipartBody[Never],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitPhotosResponse]:
        """Call POST /photos."""
        return await self._core.execute(
            _operations.OPERATION_11,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_labels(
        self,
        *,
        body: AsyncMultipartBody[str],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitLabelsResponse]:
        """Call POST /labels."""
        return await self._core.execute(
            _operations.OPERATION_12,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_search(
        self,
        *,
        body: _dcg_type_5,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitSearchResponse]:
        """Call POST /searches."""
        return await self._core.execute(
            _operations.OPERATION_15,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_cover(
        self,
        *,
        body: AsyncMultipartBody[str | int | _dcg_type_4 | _dcg_type_6 | JSONValue],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitCoverResponse]:
        """Call POST /covers."""
        return await self._core.execute(
            _operations.OPERATION_16,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_card(
        self,
        *,
        body: _dcg_type_7,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitCardResponse]:
        """Call POST /cards."""
        return await self._core.execute(
            _operations.OPERATION_17,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_stickers(
        self,
        *,
        body: _dcg_type_8,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitStickersResponse]:
        """Call POST /stickers."""
        return await self._core.execute(
            _operations.OPERATION_18,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_album(
        self,
        *,
        body: AsyncMultipartBody[_dcg_type_9 | str | list[str] | JSONValue],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitAlbumResponse]:
        """Call POST /albums."""
        return await self._core.execute(
            _operations.OPERATION_19,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )


class AsyncFormsWithRawResponse:
    """The forms operations, returning each raw response with its body read into memory."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    async def submit_form(
        self,
        *,
        body: _dcg_type_0,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /forms."""
        return await self._core.execute_raw(
            _operations.OPERATION_0,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_profile(
        self,
        *,
        body: _dcg_type_1,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /profiles."""
        return await self._core.execute_raw(
            _operations.OPERATION_1,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def read_profile(
        self,
        *,
        response_media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call GET /profiles."""
        return await self._core.execute_raw(
            _operations.OPERATION_2,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_anything(
        self,
        *,
        body: _dcg_type_2,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /anything."""
        return await self._core.execute_raw(
            _operations.OPERATION_3,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_parts(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /attachments."""
        return await self._core.execute_raw(
            _operations.OPERATION_4,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def read_parts(
        self,
        *,
        response_media_type: Literal['multipart/mixed', 'multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call GET /attachments."""
        return await self._core.execute_raw(
            _operations.OPERATION_5,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_pairs(
        self,
        *,
        body: FormData | Unset = UNSET,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /pairs."""
        return await self._core.execute_raw(
            _operations.OPERATION_6,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_upload(
        self,
        *,
        body: AsyncMultipartBody[int | str | list[str] | _dcg_type_4],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /uploads."""
        return await self._core.execute_raw(
            _operations.OPERATION_7,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def read_upload(
        self,
        *,
        response_media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call GET /uploads."""
        return await self._core.execute_raw(
            _operations.OPERATION_8,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    @overload
    async def submit_avatar(
        self,
        *,
        body: AsyncMultipartBody[str | JSONValue],
        media_type: Literal['multipart/form-data'],
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse: ...
    @overload
    async def submit_avatar(
        self,
        *,
        body: _dcg_type_4,
        media_type: Literal['application/json'],
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse: ...
    @overload
    async def submit_avatar(
        self,
        *,
        body: Unset = UNSET,
        media_type: None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse: ...
    async def submit_avatar(
        self,
        *,
        body: AsyncMultipartBody[str | JSONValue] | _dcg_type_4 | Unset = UNSET,
        media_type: Literal['multipart/form-data', 'application/json'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /avatars."""
        return await self._core.execute_raw(
            _operations.OPERATION_9,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_scans(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /scans."""
        return await self._core.execute_raw(
            _operations.OPERATION_10,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_photos(
        self,
        *,
        body: AsyncMultipartBody[Never],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /photos."""
        return await self._core.execute_raw(
            _operations.OPERATION_11,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_labels(
        self,
        *,
        body: AsyncMultipartBody[str],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /labels."""
        return await self._core.execute_raw(
            _operations.OPERATION_12,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_search(
        self,
        *,
        body: _dcg_type_5,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /searches."""
        return await self._core.execute_raw(
            _operations.OPERATION_15,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_cover(
        self,
        *,
        body: AsyncMultipartBody[str | int | _dcg_type_4 | _dcg_type_6 | JSONValue],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /covers."""
        return await self._core.execute_raw(
            _operations.OPERATION_16,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_card(
        self,
        *,
        body: _dcg_type_7,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /cards."""
        return await self._core.execute_raw(
            _operations.OPERATION_17,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_stickers(
        self,
        *,
        body: _dcg_type_8,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /stickers."""
        return await self._core.execute_raw(
            _operations.OPERATION_18,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_album(
        self,
        *,
        body: AsyncMultipartBody[_dcg_type_9 | str | list[str] | JSONValue],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /albums."""
        return await self._core.execute_raw(
            _operations.OPERATION_19,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )


class AsyncFormsWithStreamingResponse:
    """The forms operations, returning blocks that send each call on entry and stream its response."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    def submit_form(
        self,
        *,
        body: _dcg_type_0,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /forms."""
        return self._core.stream(
            _operations.OPERATION_0,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def submit_profile(
        self,
        *,
        body: _dcg_type_1,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /profiles."""
        return self._core.stream(
            _operations.OPERATION_1,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def read_profile(
        self,
        *,
        response_media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call GET /profiles."""
        return self._core.stream(
            _operations.OPERATION_2,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def submit_anything(
        self,
        *,
        body: _dcg_type_2,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /anything."""
        return self._core.stream(
            _operations.OPERATION_3,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_parts(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /attachments."""
        return self._core.stream(
            _operations.OPERATION_4,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def read_parts(
        self,
        *,
        response_media_type: Literal['multipart/mixed', 'multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call GET /attachments."""
        return self._core.stream(
            _operations.OPERATION_5,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def submit_pairs(
        self,
        *,
        body: FormData | Unset = UNSET,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /pairs."""
        return self._core.stream(
            _operations.OPERATION_6,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def submit_upload(
        self,
        *,
        body: AsyncMultipartBody[int | str | list[str] | _dcg_type_4],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /uploads."""
        return self._core.stream(
            _operations.OPERATION_7,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def read_upload(
        self,
        *,
        response_media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call GET /uploads."""
        return self._core.stream(
            _operations.OPERATION_8,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    @overload
    def submit_avatar(
        self,
        *,
        body: AsyncMultipartBody[str | JSONValue],
        media_type: Literal['multipart/form-data'],
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]: ...
    @overload
    def submit_avatar(
        self,
        *,
        body: _dcg_type_4,
        media_type: Literal['application/json'],
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]: ...
    @overload
    def submit_avatar(
        self,
        *,
        body: Unset = UNSET,
        media_type: None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]: ...
    def submit_avatar(
        self,
        *,
        body: AsyncMultipartBody[str | JSONValue] | _dcg_type_4 | Unset = UNSET,
        media_type: Literal['multipart/form-data', 'application/json'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /avatars."""
        return self._core.stream(
            _operations.OPERATION_9,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_scans(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /scans."""
        return self._core.stream(
            _operations.OPERATION_10,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_photos(
        self,
        *,
        body: AsyncMultipartBody[Never],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /photos."""
        return self._core.stream(
            _operations.OPERATION_11,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_labels(
        self,
        *,
        body: AsyncMultipartBody[str],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /labels."""
        return self._core.stream(
            _operations.OPERATION_12,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_search(
        self,
        *,
        body: _dcg_type_5,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /searches."""
        return self._core.stream(
            _operations.OPERATION_15,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_cover(
        self,
        *,
        body: AsyncMultipartBody[str | int | _dcg_type_4 | _dcg_type_6 | JSONValue],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /covers."""
        return self._core.stream(
            _operations.OPERATION_16,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_card(
        self,
        *,
        body: _dcg_type_7,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /cards."""
        return self._core.stream(
            _operations.OPERATION_17,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_stickers(
        self,
        *,
        body: _dcg_type_8,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /stickers."""
        return self._core.stream(
            _operations.OPERATION_18,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_album(
        self,
        *,
        body: AsyncMultipartBody[_dcg_type_9 | str | list[str] | JSONValue],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /albums."""
        return self._core.stream(
            _operations.OPERATION_19,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )
