# Generated by datamodel-code-generator; target=client; schema_version=1
"""The result types, errors, and header accessors of the users operations."""

from __future__ import annotations

from typing import Final, Literal, TypeAlias

from models import FieldUsersGetResponse200LinkHeader as _dcg_type_1
from models import UserPage as _dcg_type_0

from ..._generated import model_bindings
from ..._runtime.client.codecs import (
    HeaderBranch,
    ResponseHeaders,
    native_value,
    optional_header,
)
from ..._runtime.model_codecs.parameters import ParameterPlan
from ...errors import HTTPStatusError
from ...options import Unset
from ...responses import ResponseInfo

ListUsersResponse: TypeAlias = _dcg_type_0
ListUsersErrorData: TypeAlias = None


class ListUsersHTTPError(HTTPStatusError[ListUsersErrorData]):
    """An error response of list_users, with its decoded payload when one is declared."""


_LIST_USERS_HEADERS: Final[ResponseHeaders[_dcg_type_1, Unset]] = ResponseHeaders(
    'listUsers',
    frozenset({'200'}),
    (
        (
            'Link',
            (
                (
                    '200',
                    HeaderBranch(
                        plan=ParameterPlan(
                            location='header',
                            name='Link',
                            style='simple',
                        ),
                        decode=native_value(model_bindings.codec_5, model_bindings.CONTEXT_5),
                        missing=optional_header,
                    ),
                ),
            ),
        ),
    ),
)


def decode_list_users_header(
    info: ResponseInfo,
    *,
    name: Literal['Link'],
) -> _dcg_type_1 | Unset:
    """Decode one declared response header of list_users from a response's metadata."""
    return _LIST_USERS_HEADERS.decode(info, name)


SearchUsersResponse: TypeAlias = _dcg_type_0
SearchUsersErrorData: TypeAlias = None


class SearchUsersHTTPError(HTTPStatusError[SearchUsersErrorData]):
    """An error response of search_users, with its decoded payload when one is declared."""
