# generated by datamodel-codegen:
#   filename:  constrained-union.json

from __future__ import annotations
from typing_extensions import NotRequired
from typing import TypedDict



class Payload(TypedDict):
    value: str | int
    one: NotRequired[str | int]
    items: NotRequired[list[str | int]]