# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Business logic of the repeat operation; replace the body with its implementation."""

from __future__ import annotations

import parameters_basemodel_models
from fastapi.responses import Response

from ..errors import UnimplementedOperationError
from ..responses import HTTPResult, RepeatResponsePayload


def repeat(
    *,
    id: parameters_basemodel_models.FieldRepeatIdAgainIdGetPathIdParameter,
) -> None | HTTPResult[RepeatResponsePayload] | Response:
    """Answer 501 until the repeat operation is implemented."""
    raise UnimplementedOperationError
