# Generated by datamodel-code-generator; target=client; schema_version=1
"""The result types, errors, and header accessors of the loose operations."""

from __future__ import annotations

from typing import TypeAlias

from models import LoosePage as _dcg_type_0

from ...errors import HTTPStatusError

ListLooseResponse: TypeAlias = _dcg_type_0
ListLooseErrorData: TypeAlias = None


class ListLooseHTTPError(HTTPStatusError[ListLooseErrorData]):
    """An error response of list_loose, with its decoded payload when one is declared."""
