# generated by datamodel-codegen:
#   filename:  serialize-imports.json

from __future__ import annotations
from pydantic.dataclasses import dataclass



@dataclass
class Base:
    name: str



@dataclass
class Child(Base):
    extra: int