# Generated by datamodel-code-generator; target=client; schema_version=1
"""The types of the files operations."""

from ._operations import (
    ReadFileErrorData,
    ReadFileHTTPError,
    ReadFileResponse,
    ReplaceFileErrorData,
    ReplaceFileHTTPError,
    ReplaceFileResponse,
    StoreFileErrorData,
    StoreFileHTTPError,
    StoreFileResponse,
)

__all__ = [
    'ReadFileErrorData',
    'ReadFileHTTPError',
    'ReadFileResponse',
    'ReplaceFileErrorData',
    'ReplaceFileHTTPError',
    'ReplaceFileResponse',
    'StoreFileErrorData',
    'StoreFileHTTPError',
    'StoreFileResponse',
]
