# Generated by datamodel-code-generator; target=client; schema_version=1
"""The asyncio operations of the pets.photos resource."""

from __future__ import annotations

from functools import cached_property
from typing import Literal

from models import FieldPetsPetIdPhotoPutPathPetIdParameter as _dcg_type_0

from .... import _operations
from ...._runtime.client.client import AsyncClientCore
from ....model_codecs import ModelValue
from ....options import UNSET, RequestOptions, Unset
from ....responses import Response
from ....types.pets.photos import UploadResponse


class AsyncPetsPhotosResource:
    """The pets.photos operations."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    @cached_property
    def with_response(self) -> AsyncPetsPhotosWithResponse:
        """The same operations, returning each result with its response metadata."""
        return AsyncPetsPhotosWithResponse(self._core)

    async def upload(
        self,
        *,
        pet_id: _dcg_type_0 | ModelValue[_dcg_type_0],
        body: bytes | Unset = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> UploadResponse:
        """Call PUT /pets/{petId}/photo."""
        return (await self._core.execute(
            _operations.OPERATION_5,
            (pet_id,),
            body=body,
            media_type=media_type,
            options=options,
        )).data


class AsyncPetsPhotosWithResponse:
    """The pets.photos operations, returning each result with its metadata."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    async def upload(
        self,
        *,
        pet_id: _dcg_type_0 | ModelValue[_dcg_type_0],
        body: bytes | Unset = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[UploadResponse]:
        """Call PUT /pets/{petId}/photo."""
        return await self._core.execute(
            _operations.OPERATION_5,
            (pet_id,),
            body=body,
            media_type=media_type,
            options=options,
        )
