# generated by datamodel-codegen:
#   filename:  references.yaml

"""Endpoints of every operation; regenerate them instead of editing."""

from collections.abc import Sequence
from typing import Annotated, Final

import models
from fastapi import APIRouter, Body, Depends, Header, Query, Security, params
from fastapi.security import HTTPAuthorizationCredentials
from pydantic import Field

from . import security
from ._generated import contract
from ._generated.contract import OperationDependencies
from ._runtime.server.application import Wiring, build, checked
from ._runtime.server.responses import dispatch
from ._runtime.server.security import (
    AsyncAuthorize,
    Authorize,
    PrincipalT,
    authenticate,
)
from .services import Service


def _add_list_pets(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    service: Service[object] = wiring.services['service']
    list_pets_handler = checked(
        service.list_pets,
        'The service.list_pets method of GET /pets',
    )

    list_pets_authorize = wiring.authorizer()

    async def list_pets_principal(
        *,
        bearer_alias: Annotated[HTTPAuthorizationCredentials | None, Security(security.bearer_alias)],
    ) -> object:
        return await authenticate(
            ((('bearer_alias', ()),),),
            {'bearer_alias': bearer_alias},
            list_pets_authorize,
            'Bearer',
        )

    def list_pets(
        *,
        principal: Annotated[object, Depends(list_pets_principal)],
        limit: Annotated[Annotated[int, Field(ge=1)] | None, Query(alias='limit')] = None,
        page: Annotated[Annotated[int, Field(ge=1)] | None, Query(alias='page')] = None,
        x_trace: Annotated[str | None, Header(alias='X-Trace', convert_underscores=False)] = None,
    ) -> object:
        return dispatch(
            list_pets_handler(
                principal=principal,
                limit=limit,
                page=page,
                x_trace=x_trace,
            ),
            contract.ListPets.RESPONSES,
        )

    router.add_api_route(
        '/pets',
        list_pets,
        methods=['GET'],
        status_code=200,
        response_model=models.PetsResponse,
        response_model_by_alias=True,
        response_model_exclude_unset=True,
        operation_id='listPets',
        response_description='The pets.',
        dependencies=wiring.dependencies.get('list_pets'),
    )


def _add_create_pet(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    service: Service[object] = wiring.services['service']
    create_pet_handler = checked(
        service.create_pet,
        'The service.create_pet method of POST /pets',
    )

    create_pet_authorize = wiring.authorizer()

    async def create_pet_principal(
        *,
        library_key: Annotated[str | None, Security(security.library_key)],
    ) -> object:
        return await authenticate(
            ((('library_key', ()),),),
            {'library_key': library_key},
            create_pet_authorize,
            'APIKey',
        )

    def create_pet(
        *,
        principal: Annotated[object, Depends(create_pet_principal)],
        x_trace: Annotated[str | None, Header(alias='X-Trace', convert_underscores=False)] = None,
        body: Annotated[models.Pet, Body(media_type='application/json')],
    ) -> object:
        return dispatch(
            create_pet_handler(
                principal=principal,
                x_trace=x_trace,
                body=body,
            ),
            contract.CreatePet.RESPONSES,
        )

    router.add_api_route(
        '/pets',
        create_pet,
        methods=['POST'],
        status_code=201,
        response_model=models.Pet,
        response_model_by_alias=True,
        response_model_exclude_unset=True,
        operation_id='createPet',
        response_description='Created.',
        dependencies=wiring.dependencies.get('create_pet'),
    )


def _add_list_owners(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    service: Service[object] = wiring.services['service']
    list_owners_handler = checked(
        service.list_owners,
        'The service.list_owners method of GET /owners',
    )

    list_owners_authorize = wiring.authorizer()

    async def list_owners_principal(
        *,
        metadata_key: Annotated[str | None, Security(security.metadata_key)],
    ) -> object:
        return await authenticate(
            ((('metadata_key', ()),),),
            {'metadata_key': metadata_key},
            list_owners_authorize,
            'APIKey',
        )

    def list_owners(
        *,
        principal: Annotated[object, Depends(list_owners_principal)],
        limit: Annotated[Annotated[int, Field(ge=1)] | None, Query(alias='limit')] = None,
    ) -> object:
        return dispatch(
            list_owners_handler(
                principal=principal,
                limit=limit,
            ),
            contract.ListOwners.RESPONSES,
        )

    router.add_api_route(
        '/owners',
        list_owners,
        methods=['GET'],
        status_code=200,
        response_model=models.FieldOwnersGetResponse,
        response_model_by_alias=True,
        response_model_exclude_unset=True,
        operation_id='listOwners',
        response_description='The owners.',
        dependencies=wiring.dependencies.get('list_owners'),
    )


LITERAL_ROUTES: Final = (
    ('list_pets', _add_list_pets),
    ('create_pet', _add_create_pet),
    ('list_owners', _add_list_owners),
)
TEMPLATED_ROUTES: Final = ()


def build_router(
    *,
    service: Service[PrincipalT],
    authorize: Authorize[PrincipalT] | AsyncAuthorize[PrincipalT],
    dependencies: Sequence[params.Depends] = (),
    operation_dependencies: OperationDependencies | None = None,
    prefix: str = "",
) -> APIRouter:
    """Register every operation on a new router, literal paths first."""
    return build(
        (*LITERAL_ROUTES, *TEMPLATED_ROUTES),
        services={'service': service},
        authorize=authorize,
        dependencies=dependencies,
        operation_dependencies=operation_dependencies,
        prefix=prefix,
    )
