# Generated by datamodel-code-generator; target=client; schema_version=1
"""The asyncio operations of the forms resource."""

from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from functools import cached_property
from typing import Literal

from models import FieldAnythingPostRequest as _dcg_type_2
from models import FieldFormsPostRequest as _dcg_type_0
from models import FieldProfilesPostRequest as _dcg_type_1

from ... import _operations
from ..._runtime.client.client import AsyncClientCore
from ...bodies import AsyncMultipartBody, FormData
from ...model_codecs import ModelValue
from ...options import UNSET, RequestOptions, Unset
from ...responses import AsyncRawResponse, Response
from ...types.forms import (
    SubmitAnythingResponse,
    SubmitFormResponse,
    SubmitPairsResponse,
    SubmitPartsResponse,
    SubmitProfileResponse,
)


class AsyncFormsResource:
    """The forms operations."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    @cached_property
    def with_response(self) -> AsyncFormsWithResponse:
        """The same operations, returning each result with its response metadata."""
        return AsyncFormsWithResponse(self._core)

    @cached_property
    def with_raw_response(self) -> AsyncFormsWithRawResponse:
        """The same operations, returning each raw response with its body read into memory."""
        return AsyncFormsWithRawResponse(self._core)

    @cached_property
    def with_streaming_response(self) -> AsyncFormsWithStreamingResponse:
        """The same operations, returning blocks that send each call on entry and stream its response."""
        return AsyncFormsWithStreamingResponse(self._core)

    async def submit_form(
        self,
        *,
        body: _dcg_type_0 | ModelValue[_dcg_type_0],
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitFormResponse:
        """Call POST /forms."""
        return (await self._core.execute(
            _operations.OPERATION_0,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )).data

    async def submit_profile(
        self,
        *,
        body: _dcg_type_1 | ModelValue[_dcg_type_1],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitProfileResponse:
        """Call POST /profiles."""
        return (await self._core.execute(
            _operations.OPERATION_1,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_anything(
        self,
        *,
        body: _dcg_type_2 | ModelValue[_dcg_type_2],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitAnythingResponse:
        """Call POST /anything."""
        return (await self._core.execute(
            _operations.OPERATION_2,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_parts(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitPartsResponse:
        """Call POST /attachments."""
        return (await self._core.execute(
            _operations.OPERATION_3,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )).data

    async def submit_pairs(
        self,
        *,
        body: FormData | Unset = UNSET,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> SubmitPairsResponse:
        """Call POST /pairs."""
        return (await self._core.execute(
            _operations.OPERATION_4,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )).data


class AsyncFormsWithResponse:
    """The forms operations, returning each result with its response metadata."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    async def submit_form(
        self,
        *,
        body: _dcg_type_0 | ModelValue[_dcg_type_0],
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitFormResponse]:
        """Call POST /forms."""
        return await self._core.execute(
            _operations.OPERATION_0,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_profile(
        self,
        *,
        body: _dcg_type_1 | ModelValue[_dcg_type_1],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitProfileResponse]:
        """Call POST /profiles."""
        return await self._core.execute(
            _operations.OPERATION_1,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_anything(
        self,
        *,
        body: _dcg_type_2 | ModelValue[_dcg_type_2],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitAnythingResponse]:
        """Call POST /anything."""
        return await self._core.execute(
            _operations.OPERATION_2,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_parts(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitPartsResponse]:
        """Call POST /attachments."""
        return await self._core.execute(
            _operations.OPERATION_3,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_pairs(
        self,
        *,
        body: FormData | Unset = UNSET,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SubmitPairsResponse]:
        """Call POST /pairs."""
        return await self._core.execute(
            _operations.OPERATION_4,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )


class AsyncFormsWithRawResponse:
    """The forms operations, returning each raw response with its body read into memory."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    async def submit_form(
        self,
        *,
        body: _dcg_type_0 | ModelValue[_dcg_type_0],
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /forms."""
        return await self._core.execute_raw(
            _operations.OPERATION_0,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    async def submit_profile(
        self,
        *,
        body: _dcg_type_1 | ModelValue[_dcg_type_1],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /profiles."""
        return await self._core.execute_raw(
            _operations.OPERATION_1,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_anything(
        self,
        *,
        body: _dcg_type_2 | ModelValue[_dcg_type_2],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /anything."""
        return await self._core.execute_raw(
            _operations.OPERATION_2,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_parts(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /attachments."""
        return await self._core.execute_raw(
            _operations.OPERATION_3,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    async def submit_pairs(
        self,
        *,
        body: FormData | Unset = UNSET,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncRawResponse:
        """Call POST /pairs."""
        return await self._core.execute_raw(
            _operations.OPERATION_4,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )


class AsyncFormsWithStreamingResponse:
    """The forms operations, returning blocks that send each call on entry and stream its response."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    def submit_form(
        self,
        *,
        body: _dcg_type_0 | ModelValue[_dcg_type_0],
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /forms."""
        return self._core.stream(
            _operations.OPERATION_0,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def submit_profile(
        self,
        *,
        body: _dcg_type_1 | ModelValue[_dcg_type_1],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /profiles."""
        return self._core.stream(
            _operations.OPERATION_1,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_anything(
        self,
        *,
        body: _dcg_type_2 | ModelValue[_dcg_type_2],
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /anything."""
        return self._core.stream(
            _operations.OPERATION_2,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_parts(
        self,
        *,
        body: AsyncMultipartBody[str] | Unset = UNSET,
        media_type: Literal['multipart/form-data'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /attachments."""
        return self._core.stream(
            _operations.OPERATION_3,
            (),
            body=body,
            media_type=media_type,
            options=options,
        )

    def submit_pairs(
        self,
        *,
        body: FormData | Unset = UNSET,
        media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        response_media_type: Literal['application/x-www-form-urlencoded'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractAsyncContextManager[AsyncRawResponse]:
        """Call POST /pairs."""
        return self._core.stream(
            _operations.OPERATION_4,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )
