# generated by datamodel-codegen:
#   filename:  session-inherited-shapes.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.stdlib import Field, Model, StdlibCodec



MODELS: Final[dict[type, Model]] = {
    models.Detail: Model((Field('code', 'code', omit_none=True), Field('count', 'count', omit_none=True))),
    models.Payload: Model((Field('detail', 'detail', models.Detail, omit_none=True), Field('label', 'label', omit_none=True))),
    models.Node: Model((Field('detail', 'detail', models.Detail, omit_none=True), Field('label', 'label', omit_none=True))),
    models.Parent: Model((Field('payload', 'payload', models.Node, omit_none=True), Field('position', 'position', omit_none=True))),
    models.Child: Model((Field('payload', 'payload', models.Payload, omit_none=True), Field('position', 'position', omit_none=True))),
}

codec_0: Final[StdlibCodec[models.Child]] = StdlibCodec(models.Child, MODELS)
"""Codec of /paths/~1bindings~10/post request_body (request application/json)."""

codec_1: Final[StdlibCodec[models.Child]] = StdlibCodec(models.Child, MODELS)
"""Codec of /paths/~1bindings~10/post response_body (response 200 application/json)."""

codec_2: Final[StdlibCodec[models.Parent]] = StdlibCodec(models.Parent, MODELS)
"""Codec of /paths/~1bindings~11/post request_body (request application/json)."""

codec_3: Final[StdlibCodec[models.Parent]] = StdlibCodec(models.Parent, MODELS)
"""Codec of /paths/~1bindings~11/post response_body (response 200 application/json)."""

codec_4: Final[StdlibCodec[models.Node]] = StdlibCodec(models.Node, MODELS)
"""Codec of /paths/~1bindings~12/post request_body (request application/json)."""

codec_5: Final[StdlibCodec[models.Node]] = StdlibCodec(models.Node, MODELS)
"""Codec of /paths/~1bindings~12/post response_body (response 200 application/json)."""

codec_6: Final[StdlibCodec[models.Detail]] = StdlibCodec(models.Detail, MODELS)
"""Codec of /paths/~1bindings~13/post request_body (request application/json)."""

codec_7: Final[StdlibCodec[models.Detail]] = StdlibCodec(models.Detail, MODELS)
"""Codec of /paths/~1bindings~13/post response_body (response 200 application/json)."""

codec_8: Final[StdlibCodec[models.Pair]] = StdlibCodec(None, MODELS)
"""Codec of /paths/~1bindings~14/post request_body (request application/json)."""

codec_9: Final[StdlibCodec[models.Pair]] = StdlibCodec(None, MODELS)
"""Codec of /paths/~1bindings~14/post response_body (response 200 application/json)."""
