# generated by datamodel-codegen:
#   filename:  auth.yaml

"""The synchronous operations of the auth resource."""

from __future__ import annotations

from contextlib import AbstractContextManager
from functools import cached_property
from typing import Literal

import models

from ... import _operations
from ..._runtime.client.client import ClientCore
from ...bodies import MultipartBody, SyncBinaryBody
from ...options import UNSET, RequestOptions
from ...responses import RawResponse, Response
from ...types.auth import (
    AliasAuthResponse,
    AndAuthResponse,
    AnonymousResponse,
    ApiKeyCookieResponse,
    ApiKeyHeaderResponse,
    ApiKeyQueryResponse,
    AuthorizationOrResponse,
    BasicResponse,
    BearerResponse,
    ChallengeLessResponse,
    CookieParametersResponse,
    EmptySecurityResponse,
    IdempotentAuthResponse,
    InheritedAuthResponse,
    NeverAuthResponse,
    OauthEmptyResponse,
    OauthReadResponse,
    OauthScopesResponse,
    OpenidReadResponse,
    OptionalAuthResponse,
    OptionalTokenFirstResponse,
    OrAuthResponse,
    SignedBodyResponse,
    SignedMultipartResponse,
    UnsafeAuthResponse,
    VendorAuthResponse,
)


class AuthResource:
    """The auth operations."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    @cached_property
    def with_response(self) -> AuthWithResponse:
        """The same operations, returning each result with its response metadata."""
        return AuthWithResponse(self._core)

    @cached_property
    def with_raw_response(self) -> AuthWithRawResponse:
        """The same operations, returning each raw response with its body read into memory."""
        return AuthWithRawResponse(self._core)

    @cached_property
    def with_streaming_response(self) -> AuthWithStreamingResponse:
        """The same operations, returning blocks that send each call on entry and stream its response."""
        return AuthWithStreamingResponse(self._core)

    def inherited_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> InheritedAuthResponse:
        """Call GET /inherited."""
        return self._core.execute(
            _operations.OPERATION_0,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def anonymous(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AnonymousResponse:
        """Call GET /anonymous."""
        return self._core.execute(
            _operations.OPERATION_1,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def empty_security(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> EmptySecurityResponse:
        """Call GET /empty."""
        return self._core.execute(
            _operations.OPERATION_2,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def optional_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> OptionalAuthResponse:
        """Call GET /optional."""
        return self._core.execute(
            _operations.OPERATION_3,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def optional_token_first(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> OptionalTokenFirstResponse:
        """Call GET /optional-token-first."""
        return self._core.execute(
            _operations.OPERATION_4,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def and_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AndAuthResponse:
        """Call GET /and."""
        return self._core.execute(
            _operations.OPERATION_5,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def or_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> OrAuthResponse:
        """Call GET /or."""
        return self._core.execute(
            _operations.OPERATION_6,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def authorization_or(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AuthorizationOrResponse:
        """Call GET /authorization-or."""
        return self._core.execute(
            _operations.OPERATION_7,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def api_key_header(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> ApiKeyHeaderResponse:
        """Call GET /api-key/header."""
        return self._core.execute(
            _operations.OPERATION_8,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def api_key_query(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> ApiKeyQueryResponse:
        """Call GET /api-key/query."""
        return self._core.execute(
            _operations.OPERATION_9,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def api_key_cookie(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> ApiKeyCookieResponse:
        """Call GET /api-key/cookie."""
        return self._core.execute(
            _operations.OPERATION_10,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def cookie_parameters(
        self,
        *,
        theme: str,
        page: int,
        x_trace: str,
        filter: models.FieldApiKeyCookieParametersGetQueryFilterParameter | UNSET = UNSET,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> CookieParametersResponse:
        """Call GET /api-key/cookie-parameters."""
        return self._core.execute(
            _operations.OPERATION_11,
            (theme, page, x_trace, filter),
            options=options,
            response_media_type=response_media_type,
        ).data

    def basic(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> BasicResponse:
        """Call GET /basic."""
        return self._core.execute(
            _operations.OPERATION_12,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def bearer(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> BearerResponse:
        """Call GET /bearer."""
        return self._core.execute(
            _operations.OPERATION_13,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def alias_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AliasAuthResponse:
        """Call GET /alias."""
        return self._core.execute(
            _operations.OPERATION_14,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def oauth_read(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> OauthReadResponse:
        """Call GET /oauth/read."""
        return self._core.execute(
            _operations.OPERATION_15,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def oauth_scopes(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> OauthScopesResponse:
        """Call GET /oauth/scopes."""
        return self._core.execute(
            _operations.OPERATION_16,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def oauth_empty(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> OauthEmptyResponse:
        """Call GET /oauth/empty."""
        return self._core.execute(
            _operations.OPERATION_17,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def openid_read(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> OpenidReadResponse:
        """Call GET /openid/read."""
        return self._core.execute(
            _operations.OPERATION_18,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def challenge_less(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> ChallengeLessResponse:
        """Call GET /challenge-less."""
        return self._core.execute(
            _operations.OPERATION_19,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def unsafe_auth(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> UnsafeAuthResponse:
        """Call POST /unsafe."""
        return self._core.execute(
            _operations.OPERATION_20,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        ).data

    def idempotent_auth(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> IdempotentAuthResponse:
        """Call POST /idempotent."""
        return self._core.execute(
            _operations.OPERATION_21,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        ).data

    def never_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> NeverAuthResponse:
        """Call GET /never."""
        return self._core.execute(
            _operations.OPERATION_22,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def vendor_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> VendorAuthResponse:
        """Call GET /vendor."""
        return self._core.execute(
            _operations.OPERATION_23,
            (),
            options=options,
            response_media_type=response_media_type,
        ).data

    def signed_body(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> SignedBodyResponse:
        """Call PUT /signed."""
        return self._core.execute(
            _operations.OPERATION_24,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        ).data

    def signed_multipart(
        self,
        *,
        body: MultipartBody[str],
        media_type: Literal['multipart/form-data'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> SignedMultipartResponse:
        """Call POST /signed-multipart."""
        return self._core.execute(
            _operations.OPERATION_25,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        ).data


class AuthWithResponse:
    """The auth operations, returning each result with its response metadata."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    def inherited_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[InheritedAuthResponse]:
        """Call GET /inherited."""
        return self._core.execute(
            _operations.OPERATION_0,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def anonymous(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[AnonymousResponse]:
        """Call GET /anonymous."""
        return self._core.execute(
            _operations.OPERATION_1,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def empty_security(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[EmptySecurityResponse]:
        """Call GET /empty."""
        return self._core.execute(
            _operations.OPERATION_2,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def optional_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[OptionalAuthResponse]:
        """Call GET /optional."""
        return self._core.execute(
            _operations.OPERATION_3,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def optional_token_first(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[OptionalTokenFirstResponse]:
        """Call GET /optional-token-first."""
        return self._core.execute(
            _operations.OPERATION_4,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def and_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[AndAuthResponse]:
        """Call GET /and."""
        return self._core.execute(
            _operations.OPERATION_5,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def or_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[OrAuthResponse]:
        """Call GET /or."""
        return self._core.execute(
            _operations.OPERATION_6,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def authorization_or(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[AuthorizationOrResponse]:
        """Call GET /authorization-or."""
        return self._core.execute(
            _operations.OPERATION_7,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_header(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[ApiKeyHeaderResponse]:
        """Call GET /api-key/header."""
        return self._core.execute(
            _operations.OPERATION_8,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_query(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[ApiKeyQueryResponse]:
        """Call GET /api-key/query."""
        return self._core.execute(
            _operations.OPERATION_9,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_cookie(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[ApiKeyCookieResponse]:
        """Call GET /api-key/cookie."""
        return self._core.execute(
            _operations.OPERATION_10,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def cookie_parameters(
        self,
        *,
        theme: str,
        page: int,
        x_trace: str,
        filter: models.FieldApiKeyCookieParametersGetQueryFilterParameter | UNSET = UNSET,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[CookieParametersResponse]:
        """Call GET /api-key/cookie-parameters."""
        return self._core.execute(
            _operations.OPERATION_11,
            (theme, page, x_trace, filter),
            options=options,
            response_media_type=response_media_type,
        )

    def basic(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[BasicResponse]:
        """Call GET /basic."""
        return self._core.execute(
            _operations.OPERATION_12,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def bearer(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[BearerResponse]:
        """Call GET /bearer."""
        return self._core.execute(
            _operations.OPERATION_13,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def alias_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[AliasAuthResponse]:
        """Call GET /alias."""
        return self._core.execute(
            _operations.OPERATION_14,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_read(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[OauthReadResponse]:
        """Call GET /oauth/read."""
        return self._core.execute(
            _operations.OPERATION_15,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_scopes(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[OauthScopesResponse]:
        """Call GET /oauth/scopes."""
        return self._core.execute(
            _operations.OPERATION_16,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_empty(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[OauthEmptyResponse]:
        """Call GET /oauth/empty."""
        return self._core.execute(
            _operations.OPERATION_17,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def openid_read(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[OpenidReadResponse]:
        """Call GET /openid/read."""
        return self._core.execute(
            _operations.OPERATION_18,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def challenge_less(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[ChallengeLessResponse]:
        """Call GET /challenge-less."""
        return self._core.execute(
            _operations.OPERATION_19,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def unsafe_auth(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[UnsafeAuthResponse]:
        """Call POST /unsafe."""
        return self._core.execute(
            _operations.OPERATION_20,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def idempotent_auth(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[IdempotentAuthResponse]:
        """Call POST /idempotent."""
        return self._core.execute(
            _operations.OPERATION_21,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def never_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[NeverAuthResponse]:
        """Call GET /never."""
        return self._core.execute(
            _operations.OPERATION_22,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def vendor_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[VendorAuthResponse]:
        """Call GET /vendor."""
        return self._core.execute(
            _operations.OPERATION_23,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def signed_body(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SignedBodyResponse]:
        """Call PUT /signed."""
        return self._core.execute(
            _operations.OPERATION_24,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def signed_multipart(
        self,
        *,
        body: MultipartBody[str],
        media_type: Literal['multipart/form-data'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> Response[SignedMultipartResponse]:
        """Call POST /signed-multipart."""
        return self._core.execute(
            _operations.OPERATION_25,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )


class AuthWithRawResponse:
    """The auth operations, returning each raw response with its body read into memory."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    def inherited_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /inherited."""
        return self._core.execute_raw(
            _operations.OPERATION_0,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def anonymous(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /anonymous."""
        return self._core.execute_raw(
            _operations.OPERATION_1,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def empty_security(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /empty."""
        return self._core.execute_raw(
            _operations.OPERATION_2,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def optional_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /optional."""
        return self._core.execute_raw(
            _operations.OPERATION_3,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def optional_token_first(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /optional-token-first."""
        return self._core.execute_raw(
            _operations.OPERATION_4,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def and_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /and."""
        return self._core.execute_raw(
            _operations.OPERATION_5,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def or_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /or."""
        return self._core.execute_raw(
            _operations.OPERATION_6,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def authorization_or(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /authorization-or."""
        return self._core.execute_raw(
            _operations.OPERATION_7,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_header(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /api-key/header."""
        return self._core.execute_raw(
            _operations.OPERATION_8,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_query(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /api-key/query."""
        return self._core.execute_raw(
            _operations.OPERATION_9,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_cookie(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /api-key/cookie."""
        return self._core.execute_raw(
            _operations.OPERATION_10,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def cookie_parameters(
        self,
        *,
        theme: str,
        page: int,
        x_trace: str,
        filter: models.FieldApiKeyCookieParametersGetQueryFilterParameter | UNSET = UNSET,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /api-key/cookie-parameters."""
        return self._core.execute_raw(
            _operations.OPERATION_11,
            (theme, page, x_trace, filter),
            options=options,
            response_media_type=response_media_type,
        )

    def basic(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /basic."""
        return self._core.execute_raw(
            _operations.OPERATION_12,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def bearer(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /bearer."""
        return self._core.execute_raw(
            _operations.OPERATION_13,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def alias_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /alias."""
        return self._core.execute_raw(
            _operations.OPERATION_14,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_read(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /oauth/read."""
        return self._core.execute_raw(
            _operations.OPERATION_15,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_scopes(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /oauth/scopes."""
        return self._core.execute_raw(
            _operations.OPERATION_16,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_empty(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /oauth/empty."""
        return self._core.execute_raw(
            _operations.OPERATION_17,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def openid_read(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /openid/read."""
        return self._core.execute_raw(
            _operations.OPERATION_18,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def challenge_less(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /challenge-less."""
        return self._core.execute_raw(
            _operations.OPERATION_19,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def unsafe_auth(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call POST /unsafe."""
        return self._core.execute_raw(
            _operations.OPERATION_20,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def idempotent_auth(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call POST /idempotent."""
        return self._core.execute_raw(
            _operations.OPERATION_21,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def never_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /never."""
        return self._core.execute_raw(
            _operations.OPERATION_22,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def vendor_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call GET /vendor."""
        return self._core.execute_raw(
            _operations.OPERATION_23,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def signed_body(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call PUT /signed."""
        return self._core.execute_raw(
            _operations.OPERATION_24,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def signed_multipart(
        self,
        *,
        body: MultipartBody[str],
        media_type: Literal['multipart/form-data'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call POST /signed-multipart."""
        return self._core.execute_raw(
            _operations.OPERATION_25,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )


class AuthWithStreamingResponse:
    """The auth operations, returning blocks that send each call on entry and stream its response."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    def inherited_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /inherited."""
        return self._core.stream(
            _operations.OPERATION_0,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def anonymous(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /anonymous."""
        return self._core.stream(
            _operations.OPERATION_1,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def empty_security(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /empty."""
        return self._core.stream(
            _operations.OPERATION_2,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def optional_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /optional."""
        return self._core.stream(
            _operations.OPERATION_3,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def optional_token_first(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /optional-token-first."""
        return self._core.stream(
            _operations.OPERATION_4,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def and_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /and."""
        return self._core.stream(
            _operations.OPERATION_5,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def or_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /or."""
        return self._core.stream(
            _operations.OPERATION_6,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def authorization_or(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /authorization-or."""
        return self._core.stream(
            _operations.OPERATION_7,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_header(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /api-key/header."""
        return self._core.stream(
            _operations.OPERATION_8,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_query(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /api-key/query."""
        return self._core.stream(
            _operations.OPERATION_9,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def api_key_cookie(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /api-key/cookie."""
        return self._core.stream(
            _operations.OPERATION_10,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def cookie_parameters(
        self,
        *,
        theme: str,
        page: int,
        x_trace: str,
        filter: models.FieldApiKeyCookieParametersGetQueryFilterParameter | UNSET = UNSET,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /api-key/cookie-parameters."""
        return self._core.stream(
            _operations.OPERATION_11,
            (theme, page, x_trace, filter),
            options=options,
            response_media_type=response_media_type,
        )

    def basic(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /basic."""
        return self._core.stream(
            _operations.OPERATION_12,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def bearer(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /bearer."""
        return self._core.stream(
            _operations.OPERATION_13,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def alias_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /alias."""
        return self._core.stream(
            _operations.OPERATION_14,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_read(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /oauth/read."""
        return self._core.stream(
            _operations.OPERATION_15,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_scopes(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /oauth/scopes."""
        return self._core.stream(
            _operations.OPERATION_16,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def oauth_empty(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /oauth/empty."""
        return self._core.stream(
            _operations.OPERATION_17,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def openid_read(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /openid/read."""
        return self._core.stream(
            _operations.OPERATION_18,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def challenge_less(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /challenge-less."""
        return self._core.stream(
            _operations.OPERATION_19,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def unsafe_auth(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call POST /unsafe."""
        return self._core.stream(
            _operations.OPERATION_20,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def idempotent_auth(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call POST /idempotent."""
        return self._core.stream(
            _operations.OPERATION_21,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def never_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /never."""
        return self._core.stream(
            _operations.OPERATION_22,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def vendor_auth(
        self,
        *,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call GET /vendor."""
        return self._core.stream(
            _operations.OPERATION_23,
            (),
            options=options,
            response_media_type=response_media_type,
        )

    def signed_body(
        self,
        *,
        body: SyncBinaryBody | UNSET = UNSET,
        media_type: Literal['application/octet-stream'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call PUT /signed."""
        return self._core.stream(
            _operations.OPERATION_24,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )

    def signed_multipart(
        self,
        *,
        body: MultipartBody[str],
        media_type: Literal['multipart/form-data'] | None = None,
        response_media_type: Literal['application/octet-stream'] | None = None,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call POST /signed-multipart."""
        return self._core.stream(
            _operations.OPERATION_25,
            (),
            body=body,
            media_type=media_type,
            options=options,
            response_media_type=response_media_type,
        )
