# generated by datamodel-codegen:
#   filename:  inherited.json

from __future__ import annotations
from pydantic import Field, constr
from pydantic.dataclasses import dataclass



@dataclass
class PayloadItem:
    code: constr(min_length=1) | None = None



@dataclass
class PayloadItem1:
    code: int | None = None



@dataclass
class PayloadItem2:
    code: str | None = None



@dataclass
class PayloadItem3:
    code: int | None = None



@dataclass
class Parent:
    payload: list[PayloadItem2 | PayloadItem3] | None = Field(None, max_length=2)



@dataclass
class Child(Parent):
    payload: list[PayloadItem | PayloadItem1] | None = Field(None, max_length=2)