# generated by datamodel-codegen:
#   filename:  session-integer-status.yaml

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.stdlib import Model, StdlibCodec


codec_0: Final[StdlibCodec[models.FieldItemsPostResponseItem]] = StdlibCodec(None, MODELS)
"""Codec of /paths/~1items/post response_body (response 200 application/json)."""
