# generated by datamodel-codegen:
#   filename:  fingerprint-nested-changed.yaml

"""The plans of this package's pagination helpers; regenerate them instead of editing."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Final

import models

from .. import _operations
from .._runtime.protocols.pagination import CountPlan, PaginationPlan
from .._runtime.protocols.records import BodySelector, ParameterTarget
from .._runtime.protocols.references import OperationRef
from ..types.default import ListThingsResponse


def _items_0(data: ListThingsResponse) -> Sequence[models.Thing] | None:
    """Return the items of one page of things.pages."""
    return data.data


PLAN_0: Final[PaginationPlan[models.Thing, ListThingsResponse]] = PaginationPlan(
    helper_id='things.pages',
    operation=OperationRef(pointer='/paths/~1things/get'),
    call=_operations.OPERATION_0,
    items=_items_0,
    items_selector=BodySelector(pointer='/data'),
    continuation=CountPlan(
        kind='offset',
        write=ParameterTarget(location='query', name='offset'),
        first=0,
        step=None,
        has_more=BodySelector(pointer='/has_more'),
    ),
    fingerprint='7b3780c6d6c80c10db99a7674562ac36f7e5332a8d9f2615182a795d62f5db96',
)
