# generated by datamodel-codegen:
#   filename:  naming.yaml

"""The synchronous operations of the item_store_1 resource."""

from __future__ import annotations

from contextlib import AbstractContextManager
from functools import cached_property

from ... import _operations
from ..._runtime.client.client import ClientCore
from ...options import RequestOptions
from ...responses import RawResponse, Response
from ...types.item_store_1 import DeleteItemsByItemIdTagsResponse


class ItemStore1Resource:
    """The item_store_1 operations."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    @cached_property
    def with_response(self) -> ItemStore1WithResponse:
        """The same operations, returning each result with its response metadata."""
        return ItemStore1WithResponse(self._core)

    @cached_property
    def with_raw_response(self) -> ItemStore1WithRawResponse:
        """The same operations, returning each raw response with its body read into memory."""
        return ItemStore1WithRawResponse(self._core)

    @cached_property
    def with_streaming_response(self) -> ItemStore1WithStreamingResponse:
        """The same operations, returning blocks that send each call on entry and stream its response."""
        return ItemStore1WithStreamingResponse(self._core)

    def delete_items_by_item_id_tags(
        self,
        *,
        itemId: int,
        options: RequestOptions | None = None,
    ) -> DeleteItemsByItemIdTagsResponse:
        """Call DELETE /items/{itemId}/tags."""
        return self._core.execute(
            _operations.OPERATION_2,
            (itemId,),
            options=options,
        ).data


class ItemStore1WithResponse:
    """The item_store_1 operations, returning each result with its response metadata."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    def delete_items_by_item_id_tags(
        self,
        *,
        itemId: int,
        options: RequestOptions | None = None,
    ) -> Response[DeleteItemsByItemIdTagsResponse]:
        """Call DELETE /items/{itemId}/tags."""
        return self._core.execute(_operations.OPERATION_2, (itemId,), options=options)


class ItemStore1WithRawResponse:
    """The item_store_1 operations, returning each raw response with its body read into memory."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    def delete_items_by_item_id_tags(
        self,
        *,
        itemId: int,
        options: RequestOptions | None = None,
    ) -> RawResponse:
        """Call DELETE /items/{itemId}/tags."""
        return self._core.execute_raw(
            _operations.OPERATION_2,
            (itemId,),
            options=options,
        )


class ItemStore1WithStreamingResponse:
    """The item_store_1 operations, returning blocks that send each call on entry and stream its response."""

    def __init__(self, core: ClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    def delete_items_by_item_id_tags(
        self,
        *,
        itemId: int,
        options: RequestOptions | None = None,
    ) -> AbstractContextManager[RawResponse]:
        """Call DELETE /items/{itemId}/tags."""
        return self._core.stream(_operations.OPERATION_2, (itemId,), options=options)
