# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Authorization of this package's secured operations; replace the body with the checks they need."""

from __future__ import annotations

from .auth_types import AuthContext
from .errors import UnimplementedOperationError


def authorize(context: AuthContext[object]) -> object:
    """Answer 501 until authorization is implemented; otherwise return the principal handlers receive."""
    raise UnimplementedOperationError
