# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Model codec bindings of this generated package; regenerate them instead of editing."""

from __future__ import annotations

from functools import cache
from typing import Final

import models

from .._runtime.model_codecs.bindings import (
    ArrayNode,
    FieldBinding,
    LeafNode,
    MapNode,
    ModelBinding,
    ModelNode,
    UnionNode,
    UseBinding,
)
from .._runtime.model_codecs.context import CodecContext
from .._runtime.model_codecs.outbound import NativeOutboundCodec
from .._runtime.model_codecs.pydantic_v2 import PydanticModelCodec
from .._runtime.model_codecs.schema import DirectionalView, SchemaBundle, SchemaResource
from .._runtime.model_codecs.wire import freeze_wire


@cache
def _resources() -> tuple[SchemaResource, ...]:
    return (
        SchemaResource(
            uri='https://dcg.invalid/inputs/root',
            contents=freeze_wire({
                'components': {
                    'schemas': {
                        'Error': {
                            'type': 'object',
                            'required': ['code', 'message'],
                            'properties': {
                                'code': {'type': 'integer', 'format': 'int32'},
                                'message': {'type': 'string'},
                            },
                        },
                        'NewPet': {
                            'type': 'object',
                            'required': ['name', 'tag'],
                            'properties': {
                                'name': {'type': 'string', 'minLength': 1},
                                'tag': {'type': ['string', 'null']},
                            },
                        },
                        'Pet': {
                            'type': 'object',
                            'required': ['id', 'name', 'tag'],
                            'properties': {
                                'id': {'type': 'integer'},
                                'name': {'type': 'string'},
                                'tag': {'type': ['string', 'null']},
                            },
                        },
                    },
                },
                'paths': {
                    '/pets': {
                        'get': {
                            'parameters': [
                                {
                                    'schema': {
                                        'type': 'integer',
                                        'format': 'int32',
                                        'minimum': 1,
                                        'maximum': 100,
                                        'default': 20,
                                    },
                                },
                                {'schema': {'type': 'array', 'items': {'type': 'string'}}},
                                {'schema': {'type': 'string', 'enum': ['cat', 'dog']}},
                                {'schema': {'type': 'string', 'format': 'uuid'}},
                                {'schema': {'type': 'string', 'format': 'date-time'}},
                                {'schema': {'type': 'string'}},
                            ],
                            'responses': {
                                '200': {
                                    'content': {
                                        'application/json': {
                                            'schema': {
                                                'type': 'array',
                                                'items': {
                                                    '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Pet',
                                                },
                                            },
                                        },
                                    },
                                },
                                'default': {
                                    'content': {
                                        'application/json': {
                                            'schema': {
                                                '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Error',
                                            },
                                        },
                                    },
                                },
                            },
                        },
                        'post': {
                            'requestBody': {
                                'content': {
                                    'application/json': {
                                        'schema': {
                                            '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/NewPet',
                                        },
                                    },
                                },
                            },
                            'responses': {
                                '201': {
                                    'content': {
                                        'application/json': {
                                            'schema': {
                                                '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Pet',
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/pets/mine': {
                        'get': {
                            'responses': {
                                '200': {
                                    'content': {
                                        'application/json': {
                                            'schema': {
                                                'type': 'array',
                                                'items': {
                                                    '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Pet',
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/pets/{petId}': {
                        'delete': {'parameters': [{'schema': {'type': 'integer', 'format': 'int64', 'minimum': 1}}]},
                        'get': {
                            'parameters': [{'schema': {'type': 'integer', 'format': 'int64', 'minimum': 1}}],
                            'responses': {
                                '200': {
                                    'content': {
                                        'application/json': {
                                            'schema': {
                                                '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Pet',
                                            },
                                        },
                                    },
                                },
                                '404': {
                                    'content': {
                                        'application/json': {
                                            'schema': {
                                                '$ref': 'https://dcg.invalid/inputs/root#/components/schemas/Error',
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                    '/store/inventory': {
                        'get': {
                            'responses': {
                                '200': {
                                    'content': {
                                        'application/json': {
                                            'schema': {'type': 'object', 'additionalProperties': {'type': 'integer'}},
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            }),
            roots=(
                '/components/schemas/Error',
                '/components/schemas/NewPet',
                '/components/schemas/Pet',
                '/paths/~1pets/get/parameters/0/schema',
                '/paths/~1pets/get/parameters/1/schema',
                '/paths/~1pets/get/parameters/2/schema',
                '/paths/~1pets/get/parameters/3/schema',
                '/paths/~1pets/get/parameters/4/schema',
                '/paths/~1pets/get/parameters/5/schema',
                '/paths/~1pets/get/responses/200/content/application~1json/schema',
                '/paths/~1pets/get/responses/default/content/application~1json/schema',
                '/paths/~1pets/post/requestBody/content/application~1json/schema',
                '/paths/~1pets/post/responses/201/content/application~1json/schema',
                '/paths/~1pets~1mine/get/responses/200/content/application~1json/schema',
                '/paths/~1pets~1{petId}/delete/parameters/0/schema',
                '/paths/~1pets~1{petId}/get/parameters/0/schema',
                '/paths/~1pets~1{petId}/get/responses/200/content/application~1json/schema',
                '/paths/~1pets~1{petId}/get/responses/404/content/application~1json/schema',
                '/paths/~1store~1inventory/get/responses/200/content/application~1json/schema',
            ),
        ),
    )


@cache
def _request_view() -> DirectionalView:
    return DirectionalView(direction='request')


@cache
def _response_view() -> DirectionalView:
    return DirectionalView(direction='response')


@cache
def request_bundle() -> SchemaBundle:
    return SchemaBundle(_resources(), _request_view())


@cache
def response_bundle() -> SchemaBundle:
    return SchemaBundle(_resources(), _response_view())


@cache
def _model_0() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldPetsGetCookieSessionParameter',
        native_kind='root',
        schema_id=None,
        root=LeafNode(),
    )


@cache
def _model_1() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldPetsGetResponse',
        native_kind='root',
        schema_id=None,
        root=ArrayNode(item=ModelNode(symbol='models:Pet')),
    )


@cache
def _model_2() -> ModelBinding:
    return ModelBinding(
        symbol='models:Pet',
        native_kind='model',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:Pet.id',
                native_name='id',
                wire_name='id',
                validation_key='id',
                validation_keys=('id',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:Pet.name',
                native_name='name',
                wire_name='name',
                validation_key='name',
                validation_keys=('name',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:Pet.tag',
                native_name='tag',
                wire_name='tag',
                validation_key='tag',
                validation_keys=('tag',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=UnionNode(members=(LeafNode(),), nullable=True),
            ),
        ),
    )


@cache
def _model_3() -> ModelBinding:
    return ModelBinding(
        symbol='models:Error',
        native_kind='model',
        schema_id=None,
        fields=(
            FieldBinding(
                field_id='models:Error.code',
                native_name='code',
                wire_name='code',
                validation_key='code',
                validation_keys=('code',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
            FieldBinding(
                field_id='models:Error.message',
                native_name='message',
                wire_name='message',
                validation_key='message',
                validation_keys=('message',),
                required=True,
                read_only=False,
                write_only=False,
                omit_none=False,
                type=LeafNode(),
            ),
        ),
    )


@cache
def _model_4() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldPetsMineGetResponse',
        native_kind='root',
        schema_id=None,
        root=ArrayNode(item=ModelNode(symbol='models:Pet')),
    )


@cache
def _model_5() -> ModelBinding:
    return ModelBinding(
        symbol='models:FieldStoreInventoryGetResponse',
        native_kind='root',
        schema_id=None,
        root=MapNode(value=LeafNode()),
    )


CONTEXT_0: Final = CodecContext(
    surface='server',
    direction='request',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/get/parameters/5/schema',
    operation_id='/paths/~1pets/get',
)


@cache
def codec_0() -> PydanticModelCodec[models.FieldPetsGetCookieSessionParameter]:
    """Codec of /paths/~1pets/get parameter (request cookie session)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1pets/get/parameters/5/schema|ModelNode(symbol='models:FieldPetsGetCookieSessionParameter')",
            direction='request',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/get/parameters/5/schema',
            operation_id='/paths/~1pets/get',
            media_type=None,
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='models:FieldPetsGetCookieSessionParameter',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:FieldPetsGetCookieSessionParameter'),
            models=(_model_0(),),
        ),
        models.FieldPetsGetCookieSessionParameter,
        {'models:FieldPetsGetCookieSessionParameter': models.FieldPetsGetCookieSessionParameter},
        request_bundle(),
    )


CONTEXT_1: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/get/responses/200/content/application~1json/schema',
    operation_id='/paths/~1pets/get',
    media_type='application/json',
)


@cache
def codec_1() -> PydanticModelCodec[models.FieldPetsGetResponse]:
    """Codec of /paths/~1pets/get response_body (response 200 application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1pets/get/responses/200/content/application~1json/schema|ModelNode(symbol='models:FieldPetsGetResponse')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/get/responses/200/content/application~1json/schema',
            operation_id='/paths/~1pets/get',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='models:FieldPetsGetResponse',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:FieldPetsGetResponse'),
            models=(_model_1(), _model_2()),
        ),
        models.FieldPetsGetResponse,
        {'models:FieldPetsGetResponse': models.FieldPetsGetResponse, 'models:Pet': models.Pet},
        response_bundle(),
    )


@cache
def outbound_1() -> NativeOutboundCodec[models.FieldPetsGetResponse]:
    return NativeOutboundCodec(codec_1(), CONTEXT_1)


CONTEXT_2: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/get/responses/default/content/application~1json/schema',
    operation_id='/paths/~1pets/get',
    media_type='application/json',
)


@cache
def codec_2() -> PydanticModelCodec[models.Error]:
    """Codec of /paths/~1pets/get response_body (response default application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Error|ModelNode(symbol='models:Error')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/get/responses/default/content/application~1json/schema',
            operation_id='/paths/~1pets/get',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='models:Error',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:Error'),
            models=(_model_3(),),
        ),
        models.Error,
        {'models:Error': models.Error},
        response_bundle(),
    )


@cache
def outbound_2() -> NativeOutboundCodec[models.Error]:
    return NativeOutboundCodec(codec_2(), CONTEXT_2)


CONTEXT_3: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/post/responses/201/content/application~1json/schema',
    operation_id='/paths/~1pets/post',
    media_type='application/json',
)


@cache
def codec_3() -> PydanticModelCodec[models.Pet]:
    """Codec of /paths/~1pets/post response_body (response 201 application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Pet|ModelNode(symbol='models:Pet')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/post/responses/201/content/application~1json/schema',
            operation_id='/paths/~1pets/post',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='models:Pet',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:Pet'),
            models=(_model_2(),),
        ),
        models.Pet,
        {'models:Pet': models.Pet},
        response_bundle(),
    )


@cache
def outbound_3() -> NativeOutboundCodec[models.Pet]:
    return NativeOutboundCodec(codec_3(), CONTEXT_3)


CONTEXT_4: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1pets~1mine/get/responses/200/content/application~1json/schema',
    operation_id='/paths/~1pets~1mine/get',
    media_type='application/json',
)


@cache
def codec_4() -> PydanticModelCodec[models.FieldPetsMineGetResponse]:
    """Codec of /paths/~1pets~1mine/get response_body (response 200 application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1pets~1mine/get/responses/200/content/application~1json/schema|ModelNode(symbol='models:FieldPetsMineGetResponse')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1pets~1mine/get/responses/200/content/application~1json/schema',
            operation_id='/paths/~1pets~1mine/get',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='models:FieldPetsMineGetResponse',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:FieldPetsMineGetResponse'),
            models=(_model_4(), _model_2()),
        ),
        models.FieldPetsMineGetResponse,
        {'models:FieldPetsMineGetResponse': models.FieldPetsMineGetResponse, 'models:Pet': models.Pet},
        response_bundle(),
    )


@cache
def outbound_4() -> NativeOutboundCodec[models.FieldPetsMineGetResponse]:
    return NativeOutboundCodec(codec_4(), CONTEXT_4)


CONTEXT_5: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1pets~1%7BpetId%7D/get/responses/200/content/application~1json/schema',
    operation_id='/paths/~1pets~1{petId}/get',
    media_type='application/json',
)


@cache
def codec_5() -> PydanticModelCodec[models.Pet]:
    """Codec of /paths/~1pets~1{petId}/get response_body (response 200 application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Pet|ModelNode(symbol='models:Pet')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1pets~1%7BpetId%7D/get/responses/200/content/application~1json/schema',
            operation_id='/paths/~1pets~1{petId}/get',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='models:Pet',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:Pet'),
            models=(_model_2(),),
        ),
        models.Pet,
        {'models:Pet': models.Pet},
        response_bundle(),
    )


@cache
def outbound_5() -> NativeOutboundCodec[models.Pet]:
    return NativeOutboundCodec(codec_5(), CONTEXT_5)


CONTEXT_6: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1pets~1%7BpetId%7D/get/responses/404/content/application~1json/schema',
    operation_id='/paths/~1pets~1{petId}/get',
    media_type='application/json',
)


@cache
def codec_6() -> PydanticModelCodec[models.Error]:
    """Codec of /paths/~1pets~1{petId}/get response_body (response 404 application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/components/schemas/Error|ModelNode(symbol='models:Error')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1pets~1%7BpetId%7D/get/responses/404/content/application~1json/schema',
            operation_id='/paths/~1pets~1{petId}/get',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='model',
            native_export='models:Error',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:Error'),
            models=(_model_3(),),
        ),
        models.Error,
        {'models:Error': models.Error},
        response_bundle(),
    )


@cache
def outbound_6() -> NativeOutboundCodec[models.Error]:
    return NativeOutboundCodec(codec_6(), CONTEXT_6)


CONTEXT_7: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1store~1inventory/get/responses/200/content/application~1json/schema',
    operation_id='/paths/~1store~1inventory/get',
    media_type='application/json',
)


@cache
def codec_7() -> PydanticModelCodec[models.FieldStoreInventoryGetResponse]:
    """Codec of /paths/~1store~1inventory/get response_body (response 200 application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1store~1inventory/get/responses/200/content/application~1json/schema|ModelNode(symbol='models:FieldStoreInventoryGetResponse')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1store~1inventory/get/responses/200/content/application~1json/schema',
            operation_id='/paths/~1store~1inventory/get',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='models:FieldStoreInventoryGetResponse',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='models:FieldStoreInventoryGetResponse'),
            models=(_model_5(),),
        ),
        models.FieldStoreInventoryGetResponse,
        {'models:FieldStoreInventoryGetResponse': models.FieldStoreInventoryGetResponse},
        response_bundle(),
    )


@cache
def outbound_7() -> NativeOutboundCodec[models.FieldStoreInventoryGetResponse]:
    return NativeOutboundCodec(codec_7(), CONTEXT_7)
