# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Operation plans of this package; regenerate them instead of editing."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Final, Literal, TypeAlias, TypedDict

import security_basemodel_models
from pydantic import TypeAdapter

from .._runtime.server.application import Dependency, OperationPlan
from .._runtime.server.responses import Declared, OperationResponses

OperationKey: TypeAlias = Literal[
    '/paths/~1pets/get',
    '/paths/~1public/get',
    '/paths/~1maybe/get',
    '/paths/~1pets~1{petId}/put',
    '/paths/~1session/get',
    '/paths/~1custom/get',
]
OperationDependencies = TypedDict(
    'OperationDependencies',
    {
        '/paths/~1pets/get': Sequence[Dependency],
        '/paths/~1public/get': Sequence[Dependency],
        '/paths/~1maybe/get': Sequence[Dependency],
        '/paths/~1pets~1{petId}/put': Sequence[Dependency],
        '/paths/~1session/get': Sequence[Dependency],
        '/paths/~1custom/get': Sequence[Dependency],
    },
    total=False,
)


class ListPets:
    """Plans of the list_pets operation."""

    OPERATION: Final = OperationPlan(
        name='list_pets',
        key='/paths/~1pets/get',
        service='pets',
        keywords=('principal',),
        secured=True,
    )
    RESPONSES: Final = OperationResponses(
        responses={
            '200': Declared(
                media_type='application/json',
                adapter=TypeAdapter(security_basemodel_models.FieldPetsGetResponse),
            ),
        },
    )


class GetPublic:
    """Plans of the get_public operation."""

    OPERATION: Final = OperationPlan(
        name='get_public',
        key='/paths/~1public/get',
        service='public',
    )
    RESPONSES: Final = OperationResponses(responses={'204': Declared()}, primary=204)


class GetMaybe:
    """Plans of the get_maybe operation."""

    OPERATION: Final = OperationPlan(
        name='get_maybe',
        key='/paths/~1maybe/get',
        service='untagged',
        keywords=('principal', 'query_principal'),
        asynchronous=True,
        secured=True,
    )
    RESPONSES: Final = OperationResponses(responses={'204': Declared()}, primary=204)


class PutPet:
    """Plans of the put_pet operation."""

    OPERATION: Final = OperationPlan(
        name='put_pet',
        key='/paths/~1pets~1{petId}/put',
        service='untagged',
        keywords=('principal', 'pet_id'),
        secured=True,
    )
    RESPONSES: Final = OperationResponses(responses={'204': Declared()}, primary=204)


class GetSession:
    """Plans of the get_session operation."""

    OPERATION: Final = OperationPlan(
        name='get_session',
        key='/paths/~1session/get',
        service='untagged',
        keywords=('principal',),
        secured=True,
    )
    RESPONSES: Final = OperationResponses(responses={'204': Declared()}, primary=204)


class GetCustom:
    """Plans of the get_custom operation."""

    OPERATION: Final = OperationPlan(
        name='get_custom',
        key='/paths/~1custom/get',
        service='untagged',
        keywords=('principal',),
        asynchronous=True,
        secured=True,
    )
    RESPONSES: Final = OperationResponses(responses={'204': Declared()}, primary=204)
