# generated by datamodel-codegen:
#   filename:  server-spellings.yaml

"""Endpoints of the pets operations; regenerate them instead of editing."""

from collections.abc import Sequence as Sequence_1
from decimal import Decimal
from re import compile
from typing import Annotated, Final, List, Optional

from annotated_types import MultipleOf
from fastapi import APIRouter, Depends, Path, Query, params
from fastapi.responses import Response
from pydantic import Field, StringConstraints
from spellings_exact_basemodel_models import (
    FieldCountsGetResponse,
    FieldPetsGetResponse,
    Pet,
)

from .._generated import contract
from .._generated.contract import OperationDependencies
from .._runtime.server.application import Wiring, build, checked
from .._runtime.server.responses import dispatch
from ..services import PetsService


def _add_list_pets(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    pets: PetsService = wiring.services['pets']
    list_pets_handler = checked(
        pets.list_pets,
        'The pets.list_pets method of GET /pets',
    )

    def list_pets(
        *,
        invalid: Annotated[Optional[bool], Query(alias='invalid')] = None,
    ) -> object:
        return dispatch(
            list_pets_handler(
                invalid=invalid,
            ),
            contract.ListPets.RESPONSES,
        )

    router.add_api_route(
        '/pets',
        list_pets,
        methods=['GET'],
        status_code=200,
        response_model=FieldPetsGetResponse,
        response_model_by_alias=True,
        response_model_exclude_unset=True,
        operation_id='listPets',
        tags=['pets'],
        response_description='The pets.',
        dependencies=wiring.dependencies.get('list_pets'),
    )


def _add_list_counts(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    pets: PetsService = wiring.services['pets']
    list_counts_handler = checked(
        pets.list_counts,
        'The pets.list_counts method of GET /counts',
    )

    def list_counts(
        *,
        invalid: Annotated[Optional[bool], Query(alias='invalid')] = None,
    ) -> object:
        return dispatch(
            list_counts_handler(
                invalid=invalid,
            ),
            contract.ListCounts.RESPONSES,
        )

    router.add_api_route(
        '/counts',
        list_counts,
        methods=['GET'],
        status_code=200,
        response_model=FieldCountsGetResponse,
        response_model_by_alias=True,
        response_model_exclude_unset=True,
        operation_id='listCounts',
        tags=['pets'],
        response_description='The counts.',
        dependencies=wiring.dependencies.get('list_counts'),
    )


def _add_get_code(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    pets: PetsService = wiring.services['pets']
    get_code_handler = checked(
        pets.get_code,
        'The pets.get_code method of GET /code',
    )

    def get_code(
        *,
        invalid: Annotated[Optional[bool], Query(alias='invalid')] = None,
    ) -> object:
        return dispatch(
            get_code_handler(
                invalid=invalid,
            ),
            contract.GetCode.RESPONSES,
        )

    router.add_api_route(
        '/code',
        get_code,
        methods=['GET'],
        status_code=200,
        response_model=Annotated[str, StringConstraints(min_length=2, max_length=5)],
        response_model_by_alias=True,
        response_model_exclude_unset=True,
        operation_id='getCode',
        tags=['pets'],
        response_description='A code.',
        dependencies=wiring.dependencies.get('get_code'),
    )


def _add_literal(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    pets: PetsService = wiring.services['pets']
    literal_handler = checked(
        pets.literal,
        'The pets.literal method of GET /literal',
    )

    def literal(
        *,
        parameters: Annotated[contract.LiteralModel1.Parameters, Depends(contract.LiteralModel1.PARAMETERS)],
    ) -> object:
        return dispatch(
            literal_handler(
                modes=parameters.modes,
                named=parameters.named,
                listed=parameters.listed,
            ),
            contract.LiteralModel1.RESPONSES,
        )

    router.add_api_route(
        '/literal',
        literal,
        methods=['GET'],
        status_code=204,
        response_model=None,
        response_class=Response,
        operation_id='literal',
        tags=['pets'],
        response_description='Done.',
        dependencies=wiring.dependencies.get('literal'),
    )


def _add_literal_model(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    pets: PetsService = wiring.services['pets']
    literal_model_handler = checked(
        pets.literal_model,
        'The pets.literal_model method of GET /literal-model',
    )

    def literal_model(
        *,
        parameters: Annotated[contract.LiteralModel.Parameters, Depends(contract.LiteralModel.PARAMETERS)],
    ) -> object:
        return dispatch(
            literal_model_handler(
                modes=parameters.modes,
            ),
            contract.LiteralModel.RESPONSES,
        )

    router.add_api_route(
        '/literal-model',
        literal_model,
        methods=['GET'],
        status_code=204,
        response_model=None,
        response_class=Response,
        operation_id='literalModel',
        tags=['pets'],
        response_description='Done.',
        dependencies=wiring.dependencies.get('literal_model'),
    )


def _add_get_pet(
    router: APIRouter,
    wiring: Wiring,
) -> None:
    pets: PetsService = wiring.services['pets']
    get_pet_handler = checked(
        pets.get_pet,
        'The pets.get_pet method of GET /pets/{petId}',
    )

    def get_pet(
        *,
        petId: Annotated[int, Field(ge=1), Path(alias='petId')],
        limit: Annotated[int, Field(ge=1, le=100), Query(alias='limit')] = 10,
        code: Annotated[Optional[Annotated[str, StringConstraints(min_length=2, max_length=5)]], Query(alias='code')] = None,
        codes: Annotated[Optional[List[Annotated[str, StringConstraints(min_length=2, max_length=5)]]], Query(alias='codes')] = None,
        step: Annotated[Optional[Annotated[Decimal, MultipleOf(Decimal('0.5'))]], Query(alias='step')] = None,
        raw: Annotated[Optional[bytes], Query(alias='raw')] = None,
        label: Annotated[Optional[Annotated[str, StringConstraints(pattern=compile('^(?!x)'))]], Query(alias='label')] = None,
        parameters: Annotated[contract.GetPet.Parameters, Depends(contract.GetPet.PARAMETERS)],
    ) -> object:
        return dispatch(
            get_pet_handler(
                petId=petId,
                limit=limit,
                code=code,
                codes=codes,
                step=step,
                raw=raw,
                day=parameters.day,
                filter=parameters.filter,
                pair=parameters.pair,
                label=label,
                pet=parameters.pet,
                tag=parameters.tag,
            ),
            contract.GetPet.RESPONSES,
        )

    router.add_api_route(
        '/pets/{petId}',
        get_pet,
        methods=['GET'],
        status_code=200,
        response_model=Pet,
        response_model_by_alias=True,
        response_model_exclude_unset=True,
        operation_id='getPet',
        tags=['pets'],
        response_description='The pet.',
        dependencies=wiring.dependencies.get('get_pet'),
    )


LITERAL_ROUTES: Final = (
    ('list_pets', _add_list_pets),
    ('list_counts', _add_list_counts),
    ('get_code', _add_get_code),
    ('literal', _add_literal),
    ('literal_model', _add_literal_model),
)
TEMPLATED_ROUTES: Final = (
    ('get_pet', _add_get_pet),
)


def build_router(
    *,
    pets: PetsService,
    dependencies: Sequence_1[params.Depends] = (),
    operation_dependencies: Optional[OperationDependencies] = None,
    prefix: str = "",
) -> APIRouter:
    """Register the pets operations on a new router, literal paths first."""
    return build(
        (*LITERAL_ROUTES, *TEMPLATED_ROUTES),
        services={'pets': pets},
        dependencies=dependencies,
        operation_dependencies=operation_dependencies,
        prefix=prefix,
    )
