# generated by datamodel-codegen:
#   filename:  server-spellings.yaml

"""Build the router and the application of every selected operation from the services that implement them."""

from collections.abc import Sequence
from typing import Any, Final

from fastapi import APIRouter, FastAPI, params

from ._generated.contract import OperationDependencies
from ._generated.openapi import serve_source_openapi
from ._runtime.server.application import build, error_handlers, validation_error_handler
from ._runtime.server.security import (
    AsyncAuthorize,
    Authorize,
    Credentials,
    PrincipalT,
    RequirementSets,
)
from .routers import days, fields, pets
from .services import DaysService, FieldsService, PetsService

ROUTES: Final = (
    *pets.LITERAL_ROUTES,
    *fields.LITERAL_ROUTES,
    *days.LITERAL_ROUTES,
    *pets.TEMPLATED_ROUTES,
    *fields.TEMPLATED_ROUTES,
    *days.TEMPLATED_ROUTES,
)
INFO: Final[dict[str, Any]] = {'title': 'Server type spellings', 'version': '1.0'}


def build_router(
    *,
    pets: PetsService,
    fields: FieldsService,
    days: DaysService[PrincipalT],
    authorize: Authorize[PrincipalT] | AsyncAuthorize[PrincipalT],
    dependencies: Sequence[params.Depends] = (),
    operation_dependencies: OperationDependencies | None = None,
    prefix: str = "",
) -> APIRouter:
    """Register every operation on a new router, literal paths first."""
    return build(
        ROUTES,
        services={'pets': pets, 'fields': fields, 'days': days},
        authorize=authorize,
        dependencies=dependencies,
        operation_dependencies=operation_dependencies,
        prefix=prefix,
    )


def create_app(
    *,
    pets: PetsService,
    fields: FieldsService,
    days: DaysService[PrincipalT],
    authorize: Authorize[PrincipalT] | AsyncAuthorize[PrincipalT],
    operation_dependencies: OperationDependencies | None = None,
    prefix: str = "",
    source_openapi: bool = True,
    **fastapi_kwargs: Any,
) -> FastAPI:
    """Create the application with every operation, passing the other keyword arguments to FastAPI.

    Validation errors leave out the request's values, unless exception_handlers handles RequestValidationError. The
    application serves the source OpenAPI document of its operations, or FastAPI's own with source_openapi=False.
    """
    fastapi_kwargs["exception_handlers"] = error_handlers(fastapi_kwargs.get("exception_handlers"))
    app = FastAPI(**{**INFO, **fastapi_kwargs})
    app.include_router(
        build_router(
            pets=pets,
            fields=fields,
            days=days,
            authorize=authorize,
            operation_dependencies=operation_dependencies,
            prefix=prefix,
        )
    )
    if source_openapi:
        serve_source_openapi(app, prefix=prefix, metadata=fastapi_kwargs)
    return app


__all__ = [
    'AsyncAuthorize',
    'Authorize',
    'Credentials',
    'OperationDependencies',
    'RequirementSets',
    'build_router',
    'create_app',
    'serve_source_openapi',
    'validation_error_handler',
]
