# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Model codec bindings of this generated package; regenerate them instead of editing."""

from __future__ import annotations
