# Generated by datamodel-code-generator; target=client; schema_version=1
"""The result types, errors, and header accessors of the labels operations."""

from __future__ import annotations

from typing import TypeAlias

from models import NamePage as _dcg_type_0

from ...errors import HTTPStatusError

ListLabelsResponse: TypeAlias = _dcg_type_0
ListLabelsErrorData: TypeAlias = None


class ListLabelsHTTPError(HTTPStatusError[ListLabelsErrorData]):
    """An error response of list_labels, with its decoded payload when one is declared."""
