# Generated by datamodel-code-generator; target=fastapi; schema_version=1
"""Model codec bindings of this generated package; regenerate them instead of editing."""

from __future__ import annotations

from functools import cache
from typing import Final

import customized_basemodel_models

from .._runtime.model_codecs.bindings import (
    ArrayNode,
    LeafNode,
    ModelBinding,
    ModelNode,
    UseBinding,
)
from .._runtime.model_codecs.context import CodecContext
from .._runtime.model_codecs.outbound import NativeOutboundCodec
from .._runtime.model_codecs.pydantic_v2 import PydanticModelCodec
from .._runtime.model_codecs.schema import DirectionalView, SchemaBundle, SchemaResource
from .._runtime.model_codecs.wire import freeze_wire


@cache
def _resources() -> tuple[SchemaResource, ...]:
    return (
        SchemaResource(
            uri='https://dcg.invalid/inputs/root',
            contents=freeze_wire({
                'paths': {
                    '/pets': {
                        'get': {
                            'responses': {
                                '200': {
                                    'content': {
                                        'application/json': {'schema': {'type': 'array', 'items': {'type': 'string'}}},
                                    },
                                },
                            },
                        },
                    },
                },
            }),
            roots=('/paths/~1pets/get/responses/200/content/application~1json/schema',),
        ),
    )


@cache
def _response_view() -> DirectionalView:
    return DirectionalView(direction='response')


@cache
def response_bundle() -> SchemaBundle:
    return SchemaBundle(_resources(), _response_view())


@cache
def _model_0() -> ModelBinding:
    return ModelBinding(
        symbol='customized_basemodel_models:FieldPetsGetResponse',
        native_kind='root',
        schema_id=None,
        root=ArrayNode(item=LeafNode()),
    )


CONTEXT_0: Final = CodecContext(
    surface='server',
    direction='response',
    schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/get/responses/200/content/application~1json/schema',
    operation_id='/paths/~1pets/get',
    media_type='application/json',
)


@cache
def codec_0() -> PydanticModelCodec[customized_basemodel_models.FieldPetsGetResponse]:
    """Codec of /paths/~1pets/get response_body (response 200 application/json)."""
    return PydanticModelCodec(
        UseBinding(
            binding_id="https://dcg.invalid/inputs/root#/paths/~1pets/get/responses/200/content/application~1json/schema|ModelNode(symbol='customized_basemodel_models:FieldPetsGetResponse')",
            direction='response',
            schema_id='https://dcg.invalid/inputs/root#/paths/~1pets/get/responses/200/content/application~1json/schema',
            operation_id='/paths/~1pets/get',
            media_type='application/json',
            backend='pydantic_v2.BaseModel',
            native_kind='root',
            native_export='customized_basemodel_models:FieldPetsGetResponse',
            projection_mode='native',
            converter_strategy='pydantic_type_adapter',
            type=ModelNode(symbol='customized_basemodel_models:FieldPetsGetResponse'),
            models=(_model_0(),),
        ),
        customized_basemodel_models.FieldPetsGetResponse,
        {'customized_basemodel_models:FieldPetsGetResponse': customized_basemodel_models.FieldPetsGetResponse},
        response_bundle(),
    )


@cache
def outbound_0() -> NativeOutboundCodec[customized_basemodel_models.FieldPetsGetResponse]:
    return NativeOutboundCodec(codec_0(), CONTEXT_0)
