# Generated by datamodel-code-generator; target=client; schema_version=1
"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

from typing import Final

import models

from .._runtime.model_codecs.native import PydanticCodec

codec_0: Final[PydanticCodec[models.FieldPetsPostQueryTagParameter]] = PydanticCodec(
    models.FieldPetsPostQueryTagParameter,
)
"""Codec of /paths/~1pets/post parameter (request query tag)."""

codec_1: Final[PydanticCodec[models.NewPet]] = PydanticCodec(models.NewPet)
"""Codec of /paths/~1pets/post request_body (request application/json)."""

codec_2: Final[PydanticCodec[models.PetForm]] = PydanticCodec(models.PetForm)
"""Codec of /paths/~1pets/post request_body (request application/x-www-form-urlencoded)."""

codec_3: Final[PydanticCodec[models.Pet]] = PydanticCodec(models.Pet)
"""Codec of /paths/~1pets/post response_body (response 201 application/json)."""

codec_4: Final[PydanticCodec[models.FieldPetsPetIdPatchPathPetIdParameter]] = PydanticCodec(
    models.FieldPetsPetIdPatchPathPetIdParameter,
)
"""Codec of /paths/~1pets~1{petId}/patch parameter (request path petId)."""

codec_5: Final[PydanticCodec[models.PetPatch]] = PydanticCodec(models.PetPatch)
"""Codec of /paths/~1pets~1{petId}/patch request_body (request application/json)."""

codec_6: Final[PydanticCodec[models.FieldPetsPetIdVisitsPostPathPetIdParameter]] = PydanticCodec(
    models.FieldPetsPetIdVisitsPostPathPetIdParameter,
)
"""Codec of /paths/~1pets~1{petId}~1visits/post parameter (request path petId)."""

codec_7: Final[PydanticCodec[models.Visit]] = PydanticCodec(models.Visit)
"""Codec of /paths/~1pets~1{petId}~1visits/post request_body (request application/json)."""

codec_8: Final[PydanticCodec[models.FieldPetsPetIdOwnerPutPathPetIdParameter]] = PydanticCodec(
    models.FieldPetsPetIdOwnerPutPathPetIdParameter,
)
"""Codec of /paths/~1pets~1{petId}~1owner/put parameter (request path petId)."""

codec_9: Final[PydanticCodec[models.Owner]] = PydanticCodec(models.Owner)
"""Codec of /paths/~1pets~1{petId}~1owner/put request_body (request application/json)."""

codec_10: Final[PydanticCodec[models.FieldOwnersPostRequest]] = PydanticCodec(models.FieldOwnersPostRequest)
"""Codec of /paths/~1owners/post request_body (request application/json)."""

codec_11: Final[PydanticCodec[models.FieldPetsPetIdLabelsPutPathPetIdParameter]] = PydanticCodec(
    models.FieldPetsPetIdLabelsPutPathPetIdParameter,
)
"""Codec of /paths/~1pets~1{petId}~1labels/put parameter (request path petId)."""

codec_12: Final[PydanticCodec[models.Labels]] = PydanticCodec(models.Labels)
"""Codec of /paths/~1pets~1{petId}~1labels/put request_body (request application/json)."""

codec_13: Final[PydanticCodec[models.FieldPetsPetIdPhotoPutPathPetIdParameter]] = PydanticCodec(
    models.FieldPetsPetIdPhotoPutPathPetIdParameter,
)
"""Codec of /paths/~1pets~1{petId}~1photo/put parameter (request path petId)."""

codec_14: Final[PydanticCodec[models.FieldPetsPetIdRecordsPutPathPetIdParameter]] = PydanticCodec(
    models.FieldPetsPetIdRecordsPutPathPetIdParameter,
)
"""Codec of /paths/~1pets~1{petId}~1records/put parameter (request path petId)."""

codec_15: Final[PydanticCodec[models.Pet]] = PydanticCodec(models.Pet)
"""Codec of /paths/~1pets~1{petId}~1records/put request_body (request application/json)."""

codec_16: Final[PydanticCodec[str]] = PydanticCodec(str)
"""Codec of /paths/~1pets~1{petId}~1photo/put request_body (request caption multipart/form-data)."""
