# generated by datamodel-codegen:
#   filename:  model.json

from __future__ import annotations

from re import compile
from typing import Annotated

from pydantic import BaseModel, Field
from typing_extensions import TypeAliasType

Code = TypeAliasType(
    "Code", Annotated[str, Field(pattern=compile('^(?!bad)[a-z]+$'), max_length=8)]
)


CodeCopy = TypeAliasType(
    "CodeCopy", Annotated[str, Field(pattern=compile('^(?!bad)[a-z]+$'), max_length=8)]
)


Codes = TypeAliasType(
    "Codes", list[Annotated[str, Field(pattern=compile('^(?=x)[a-z]+$'))]]
)


Mapping = TypeAliasType(
    "Mapping", dict[str, Annotated[str, Field(pattern=compile('^[a-z]+(?<!z)$'))]]
)


Keys = TypeAliasType(
    "Keys", dict[Annotated[str, Field(pattern=compile('^(?=k)[a-z]+$'))], int]
)


Either = TypeAliasType(
    "Either", Annotated[str, Field(pattern=compile('^(?!no)[a-z]+$'))] | int
)


class Holder(BaseModel):
    code: Code | None = None
    codeCopy: CodeCopy | None = None
    codes: Codes | None = None
    mapping: Mapping | None = None
    keys: Keys | None = None
    either: Either | None = None
