# generated by datamodel-codegen:
#   filename:  review.json

from __future__ import annotations
from typing import Literal, TypeAlias



Code: TypeAlias = Literal[1, 2]



Label: TypeAlias = Literal['alpha', 'beta']