# Generated by scripts/compile_builtin_templates.py; do not edit directly.
# Source: webhook.jinja2 (sha256:631be04a3a5bce24)
from __future__ import annotations

from typing import Any

from datamodel_code_generator.model._compiled_template_runtime import (
    Scope as _Scope,
    filter_repr as _filter_repr,
    getattr_ as _getattr,
    stringify as _stringify,
)


def render(**context: Any) -> str:
    return render_with_scope(_Scope(context))


def render_with_scope(_scope: _Scope) -> str:
    def _macro_signature(_parent: _Scope, function: Any) -> str:
        _parts: list[str] = []
        if _getattr(function, "coroutine"):
            _parts.append("async ")
        _value_0 = _stringify(_getattr(function, "name"))
        _parts.append(f"def {_value_0}(")
        for parameter in _getattr(function, "positional"):
            _value_1 = _stringify(_getattr(parameter, "name"))
            _value_2 = _stringify(_getattr(parameter, "annotation"))
            _parts.append(f"\n    {_value_1}: {_value_2},")
        _parts.append("\n    *,")
        for parameter in _getattr(function, "keywords"):
            _value_3 = _stringify(_getattr(parameter, "name"))
            _value_4 = _stringify(_getattr(parameter, "annotation"))
            _parts.append(f"\n    {_value_3}: {_value_4}")
            if _getattr(parameter, "default"):
                _value_5 = _stringify(_getattr(parameter, "default"))
                _parts.append(f" = {_value_5}")
            _parts.append(",")
        _value_6 = _stringify(_getattr(function, "returns"))
        _parts.append(f"\n) -> {_value_6}:")
        return "".join(_parts)

    def _macro_call(_parent: _Scope, function: Any) -> str:
        _parts: list[str] = []
        _parts.append("return ")
        if _getattr(function, "coroutine"):
            _parts.append("await ")
        _value_7 = _stringify(_getattr(function, "function"))
        _parts.append(f"{_value_7}(")
        for argument in _getattr(function, "arguments"):
            _parts.append("\n        ")
            if _getattr(argument, "keyword"):
                _value_8 = _stringify(_getattr(argument, "keyword"))
                _parts.append(f"{_value_8}=")
            _value_9 = _stringify(_getattr(argument, "value"))
            _parts.append(f"{_value_9},")
        _parts.append("\n    )")
        return "".join(_parts)

    _context_algorithm = _scope.get("algorithm")
    _context_exports = _scope.get("exports")
    _context_functions = _scope.get("functions")
    _context_imports = _scope.get("imports")
    _context_kind = _scope.get("kind")
    _context_plan = _scope.get("plan")
    _context_timestamp = _scope.get("timestamp")
    _context_typevar = _scope.get("typevar")
    _parts: list[str] = []
    if _context_kind == "none":
        _value_10 = _stringify(_scope.get("name"))
        _parts.append(
            f'"""Decode the unsigned deliveries of one webhook helper.\n\nThe helper is {_value_10}, whose deliveries carry no signature:\nnothing authenticates who sent one, that its body is unchanged, or that it is not a replay,\nso treat every event as untrusted input.\n"""'
        )
    elif _context_kind == "adapter":
        _value_11 = _stringify(_scope.get("name"))
        _parts.append(
            f'"""Verify the deliveries of one webhook helper with the caller\'s verifier, then decode their events.\n\nThe helper is {_value_11}, whose deliveries are verified by the Verifier the caller passes,\nwhich must authenticate the whole raw body and every fact it returns.\n"""'
        )
    else:
        _value_12 = _stringify(_scope.get("name"))
        _value_13 = _stringify(_context_algorithm)
        _parts.append(
            f'"""Verify the signed deliveries of one webhook helper, then decode their events.\n\nThe helper is {_value_12}, whose deliveries are signed with {_value_13}.\n"""'
        )
    _value_14 = _stringify(_context_imports)
    _parts.append(f"\n\nfrom __future__ import annotations\n\n{_value_14}\n\n\n__all__ = [")
    for name in _context_exports:
        _value_15 = _stringify(_filter_repr(name))
        _parts.append(f"\n    {_value_15},")
    _parts.append("\n]")
    if _context_typevar:
        _value_16 = _stringify(_context_typevar)
        _parts.append(f'\n\n\nK = {_value_16}("K")')
    _value_17 = _stringify(_getattr(_context_plan, "name"))
    _value_18 = _stringify(_getattr(_context_plan, "annotation"))
    _value_19 = _stringify(_getattr(_context_plan, "constructor"))
    _parts.append(f"\n\n\n{_value_17}: {_value_18} = {_value_19}(")
    for argument in _getattr(_context_plan, "arguments"):
        _value_20 = _stringify(_getattr(argument, "keyword"))
        _value_21 = _stringify(_getattr(argument, "value"))
        _parts.append(f"\n    {_value_20}={_value_21},")
    _parts.append("\n)")
    for function in _context_functions:
        _value_22 = _stringify(_macro_signature(_scope, function))
        _parts.append(f"\n\n\n{_value_22}")
        if _context_kind == "none":
            _parts.append(
                '\n    """Decode a delivery\'s event without authenticating it.\n\n    Nothing verifies who sent the delivery, that its body is unchanged, or that it is not a replay,\n    and no duplicate information is returned: treat the event as untrusted input.\n    Of options, only max_body_bytes applies.\n    """'
            )
        else:
            _parts.append('\n    """Verify a delivery')
            if _context_kind == "adapter":
                _parts.append(" with verifier")
            _parts.append(" and decode its event.\n")
            if _context_kind == "adapter":
                _parts.append(
                    "\n    The verifier is called once, synchronously in both functions,\n    and must authenticate the whole raw body and every fact it returns;\n    a result that is not a VerifiedSignature, lacks a fact this helper requires, returns one it does not declare,\n    or has a naive timestamp raises ConfigurationError before decoding."
                )
            if _context_timestamp:
                _parts.append("\n    Deliveries outside the timestamp window are rejected.")
            _parts.append(
                '\n    Verification retains no delivery state; deduplicate in your application using delivery_id when present.\n    """'
            )
        _value_23 = _stringify(_macro_call(_scope, function))
        _parts.append(f"\n    {_value_23}")
    return "".join(_parts)
