# Generated by datamodel-code-generator; target=client; schema_version=1
"""The asyncio operations of the default resource."""

from __future__ import annotations

from functools import cached_property

from ... import _operations
from ..._runtime.client.client import AsyncClientCore
from ...options import RequestOptions
from ...responses import Response
from ...types.default import GetStatusResponse


class AsyncDefaultResource:
    """The default operations."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    @cached_property
    def with_response(self) -> AsyncDefaultWithResponse:
        """The same operations, returning each result with its response metadata."""
        return AsyncDefaultWithResponse(self._core)

    async def get_status(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> GetStatusResponse:
        """Call GET /status."""
        return (await self._core.execute(
            _operations.OPERATION_0,
            (),
            options=options,
        )).data


class AsyncDefaultWithResponse:
    """The default operations, returning each result with its metadata."""

    def __init__(self, core: AsyncClientCore) -> None:
        """Keep the client core the operations send through."""
        self._core = core

    async def get_status(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> Response[GetStatusResponse]:
        """Call GET /status."""
        return await self._core.execute(_operations.OPERATION_0, (), options=options)
