# generated by datamodel-codegen:
#   filename:  collapse_root_models_lookaround_inheritance.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, constr


class Parent(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    own: constr(pattern=r'^(?=o)[a-z]+$') | None = None


class Child(Parent):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    code: constr(pattern=r'^(?!bad)[a-z]+$') | None = None
