"""The frozen context hooks read and templates receive, and the patches hooks return."""

from __future__ import annotations

from datamodel_code_generator._fastapi.context import (
    CONTEXT_VERSION,
    ArgumentView,
    CallbackOperationView,
    CallbackUseView,
    CallbackView,
    FastAPIContext,
    FastAPIContextPatch,
    FastAPIHook,
    FastAPIProjectionView,
    HeaderView,
    HookReference,
    ImportSpec,
    MediaView,
    ModelSymbolView,
    NativeDeclarationView,
    OperationView,
    PathSlotView,
    PrimaryResponseView,
    RenderType,
    RequestView,
    ResponseView,
    RouterView,
    SourceView,
)

__all__ = [
    "CONTEXT_VERSION",
    "ArgumentView",
    "CallbackOperationView",
    "CallbackUseView",
    "CallbackView",
    "FastAPIContext",
    "FastAPIContextPatch",
    "FastAPIHook",
    "FastAPIProjectionView",
    "HeaderView",
    "HookReference",
    "ImportSpec",
    "MediaView",
    "ModelSymbolView",
    "NativeDeclarationView",
    "OperationView",
    "PathSlotView",
    "PrimaryResponseView",
    "RenderType",
    "RequestView",
    "ResponseView",
    "RouterView",
    "SourceView",
]
