# generated by datamodel-codegen:
#   filename:  capture-branches.json

"""Native model codecs of this generated package; regenerate them instead of editing."""

from __future__ import annotations

import models
from typing import Final

from .._runtime.model_codecs.native import PydanticCodec


codec_0: Final[PydanticCodec[models.Parent]] = PydanticCodec(models.Parent)
"""Codec of /paths/~1bindings~10/post request_body (request application/json)."""

codec_1: Final[PydanticCodec[models.Parent]] = PydanticCodec(models.Parent)
"""Codec of /paths/~1bindings~10/post response_body (response 200 application/json)."""

codec_2: Final[PydanticCodec[models.Child]] = PydanticCodec(models.Child)
"""Codec of /paths/~1bindings~11/post request_body (request application/json)."""

codec_3: Final[PydanticCodec[models.Child]] = PydanticCodec(models.Child)
"""Codec of /paths/~1bindings~11/post response_body (response 200 application/json)."""

codec_4: Final[PydanticCodec[models.Node]] = PydanticCodec(models.Node)
"""Codec of /paths/~1bindings~12/post request_body (request application/json)."""

codec_5: Final[PydanticCodec[models.Node]] = PydanticCodec(models.Node)
"""Codec of /paths/~1bindings~12/post response_body (response 200 application/json)."""

codec_6: Final[PydanticCodec[models.Holder]] = PydanticCodec(models.Holder)
"""Codec of /paths/~1bindings~13/post request_body (request application/json)."""

codec_7: Final[PydanticCodec[models.Holder]] = PydanticCodec(models.Holder)
"""Codec of /paths/~1bindings~13/post response_body (response 200 application/json)."""

codec_8: Final[PydanticCodec[models.A]] = PydanticCodec(models.A)
"""Codec of /paths/~1bindings~14/post request_body (request application/json)."""

codec_9: Final[PydanticCodec[models.A]] = PydanticCodec(models.A)
"""Codec of /paths/~1bindings~14/post response_body (response 200 application/json)."""

codec_10: Final[PydanticCodec[models.B]] = PydanticCodec(models.B)
"""Codec of /paths/~1bindings~15/post request_body (request application/json)."""

codec_11: Final[PydanticCodec[models.B]] = PydanticCodec(models.B)
"""Codec of /paths/~1bindings~15/post response_body (response 200 application/json)."""

codec_12: Final[PydanticCodec[models.C]] = PydanticCodec(models.C)
"""Codec of /paths/~1bindings~16/post request_body (request application/json)."""

codec_13: Final[PydanticCodec[models.C]] = PydanticCodec(models.C)
"""Codec of /paths/~1bindings~16/post response_body (response 200 application/json)."""

codec_14: Final[PydanticCodec[models.Extra]] = PydanticCodec(models.Extra)
"""Codec of /paths/~1bindings~17/post request_body (request application/json)."""

codec_15: Final[PydanticCodec[models.Extra]] = PydanticCodec(models.Extra)
"""Codec of /paths/~1bindings~17/post response_body (response 200 application/json)."""

codec_16: Final[PydanticCodec[models.Open]] = PydanticCodec(models.Open)
"""Codec of /paths/~1bindings~18/post request_body (request application/json)."""

codec_17: Final[PydanticCodec[models.Open]] = PydanticCodec(models.Open)
"""Codec of /paths/~1bindings~18/post response_body (response 200 application/json)."""

codec_18: Final[PydanticCodec[models.Code]] = PydanticCodec(models.Code)
"""Codec of /paths/~1bindings~19/post request_body (request application/json)."""

codec_19: Final[PydanticCodec[models.Code]] = PydanticCodec(models.Code)
"""Codec of /paths/~1bindings~19/post response_body (response 200 application/json)."""

codec_20: Final[PydanticCodec[models.Limited]] = PydanticCodec(models.Limited)
"""Codec of /paths/~1bindings~110/post request_body (request application/json)."""

codec_21: Final[PydanticCodec[models.Limited]] = PydanticCodec(models.Limited)
"""Codec of /paths/~1bindings~110/post response_body (response 200 application/json)."""

codec_22: Final[PydanticCodec[models.Defaulted]] = PydanticCodec(models.Defaulted)
"""Codec of /paths/~1bindings~111/post request_body (request application/json)."""

codec_23: Final[PydanticCodec[models.Defaulted]] = PydanticCodec(models.Defaulted)
"""Codec of /paths/~1bindings~111/post response_body (response 200 application/json)."""
