# generated by datamodel-codegen:
#   filename:  pets.yaml

"""The pets.photos resource."""

from ._async import (
    AsyncPetsPhotosResource,
    AsyncPetsPhotosWithRawResponse,
    AsyncPetsPhotosWithResponse,
    AsyncPetsPhotosWithStreamingResponse,
)
from ._sync import (
    PetsPhotosResource,
    PetsPhotosWithRawResponse,
    PetsPhotosWithResponse,
    PetsPhotosWithStreamingResponse,
)

__all__ = [
    'AsyncPetsPhotosResource',
    'AsyncPetsPhotosWithRawResponse',
    'AsyncPetsPhotosWithResponse',
    'AsyncPetsPhotosWithStreamingResponse',
    'PetsPhotosResource',
    'PetsPhotosWithRawResponse',
    'PetsPhotosWithResponse',
    'PetsPhotosWithStreamingResponse',
]
