# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Level(StrEnum):
    low = 'low'
    high = 'high'


class Sample(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    user_name: Annotated[str, Field(alias='userName')]
    level: Level
    count: Annotated[int, Field(ge=0)]
    note: str | None = None