# generated by datamodel-codegen:
#   filename:  extra_collision.json

from __future__ import annotations

from typing import Annotated as Annotated_aliased
from typing import Dict

from pydantic import BaseModel, ConfigDict, Field


class SomeSpec(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[
            Annotated_aliased[str, Field(pattern=r'^[A-Za-z_]+$')], int
        ],
    }
    Annotated: str | None = None
    StringConstraints: str | None = None
