# generated by datamodel-codegen:
#   filename:  server-strict.yaml

"""Service interfaces of this package's router groups; regenerate them instead of editing."""

from __future__ import annotations

from abc import abstractmethod
from typing import Protocol

import pydantic
from fastapi.responses import Response

from ._runtime.model_codecs.unset import Unset
from ._runtime.server.responses import HTTPResult


class UntaggedService(Protocol):
    """Implement the untagged operations: subclass this Protocol, or give an object its methods."""

    @abstractmethod
    def get_values(
        self,
        *,
        id: pydantic.StrictInt,
        count: pydantic.StrictInt | Unset,
        bounded: int | Unset,
        score: pydantic.StrictFloat | Unset,
        flag: pydantic.StrictBool | Unset,
        name: pydantic.StrictStr | Unset,
        label: str | Unset,
        counts: list[pydantic.StrictInt] | Unset,
        names: list[pydantic.StrictStr] | Unset,
        page: pydantic.StrictInt,
        size: int,
        maybe: pydantic.StrictInt | None | Unset,
        x_trace: pydantic.StrictInt | Unset,
        x_tag: pydantic.StrictStr | Unset,
    ) -> None | HTTPResult[None] | Response: ...
