# generated by datamodel-codegen:
#   filename:  legacy-reference-sibling-override.yaml

from __future__ import annotations
from pydantic import BaseModel, RootModel


class Pet(BaseModel):
    name: str | None = None


class PetsGetResponse(RootModel[list[Pet]]):
    root: list[Pet]


class PetsGetResponse1(BaseModel):
    count: int | None = None