# Generated by datamodel-code-generator; target=client; schema_version=1
"""The result types and header accessors of the retry operations."""

from __future__ import annotations

from typing import TypeAlias

from models import FieldIdempotentPostResponse as _dcg_type_2
from models import FieldKeyedPostResponse as _dcg_type_3
from models import FieldKeyedSafeGetResponse as _dcg_type_8
from models import FieldKeyOnlyPostResponse as _dcg_type_4
from models import FieldNeverGetResponse as _dcg_type_5
from models import FieldNeverPostResponse as _dcg_type_6
from models import FieldSafeGetResponse as _dcg_type_0
from models import FieldUnsafePostResponse as _dcg_type_1
from models import FieldVendorGetResponse as _dcg_type_7

GetSafeResponse: TypeAlias = _dcg_type_0


PostUnsafeResponse: TypeAlias = _dcg_type_1


PostIdempotentResponse: TypeAlias = _dcg_type_2


PostKeyedResponse: TypeAlias = _dcg_type_3


PostKeyOnlyResponse: TypeAlias = _dcg_type_4


GetNeverResponse: TypeAlias = _dcg_type_5


PostNeverResponse: TypeAlias = _dcg_type_6


GetVendorResponse: TypeAlias = _dcg_type_7


GetKeyedSafeResponse: TypeAlias = _dcg_type_8
