# Generated by datamodel-code-generator; target=client; schema_version=1
"""The operation registry of this package; regenerate it instead of editing."""

from __future__ import annotations

from typing import Final

from models import Address as _dcg_type_0
from models import Draft as _dcg_type_1

from ._generated import model_bindings
from ._runtime.client.codecs import envelope_value, native_value
from ._runtime.client.multipart import PartPlan, file_part, value_part
from ._runtime.client.operations import (
    BodyMedia,
    Encoder,
    OperationPlan,
    ParameterSpec,
    PartsReader,
    RequestBody,
    ResponseDecoder,
    ServerPlan,
    ServerVariable,
    empty_branch,
    envelope_branch,
    form_branch,
    model_branch,
    multipart_branch,
    parts_branch,
    text_branch,
    wire_branch,
)
from ._runtime.model_codecs.media import FieldPlan
from ._runtime.model_codecs.parameters import ParameterPlan
from .model_codecs import DecodedValue
from .types.documents import (
    ReadDocumentErrorData,
    ReadDocumentHTTPError,
    ReadDocumentResponse,
    ReplaceNoteErrorData,
    ReplaceNoteHTTPError,
    ReplaceNoteResponse,
    StoreDocumentErrorData,
    StoreDocumentHTTPError,
    StoreDocumentResponse,
    StoreNoteErrorData,
    StoreNoteHTTPError,
    StoreNoteResponse,
)
from .types.forms import (
    ReadPartsErrorData,
    ReadPartsHTTPError,
    ReadPartsResponse,
    ReadProfileErrorData,
    ReadProfileHTTPError,
    ReadProfileResponse,
    ReadUploadErrorData,
    ReadUploadHTTPError,
    ReadUploadResponse,
    SubmitAnythingErrorData,
    SubmitAnythingHTTPError,
    SubmitAnythingResponse,
    SubmitAvatarErrorData,
    SubmitAvatarHTTPError,
    SubmitAvatarResponse,
    SubmitFormErrorData,
    SubmitFormHTTPError,
    SubmitFormResponse,
    SubmitLabelsErrorData,
    SubmitLabelsHTTPError,
    SubmitLabelsResponse,
    SubmitPairsErrorData,
    SubmitPairsHTTPError,
    SubmitPairsResponse,
    SubmitPartsErrorData,
    SubmitPartsHTTPError,
    SubmitPartsResponse,
    SubmitPhotosErrorData,
    SubmitPhotosHTTPError,
    SubmitPhotosResponse,
    SubmitProfileErrorData,
    SubmitProfileHTTPError,
    SubmitProfileResponse,
    SubmitScansErrorData,
    SubmitScansHTTPError,
    SubmitScansResponse,
    SubmitUploadErrorData,
    SubmitUploadHTTPError,
    SubmitUploadResponse,
)

_SERVERS_0: Final = (ServerPlan(url='https://media.example.com/api/'),)

OPERATION_0: Final[OperationPlan[SubmitFormResponse, SubmitFormErrorData]] = OperationPlan(
    operation_id='submitForm',
    method='POST',
    path='/forms',
    servers=_SERVERS_0,
    responses=ResponseDecoder(
        (
            model_branch(
                '200',
                'application/x-www-form-urlencoded',
                'form',
                model_bindings.codec_1, model_bindings.CONTEXT_1,
                fields=(FieldPlan('name', 'string'), FieldPlan('count', 'integer')),
                additional=FieldPlan('', 'string'),
            ),
        ),
        (),
        SubmitFormHTTPError,
    ),
    body=RequestBody(
        media=(
            BodyMedia(
                media_type='application/x-www-form-urlencoded',
                kind='form',
                encoder=Encoder(model_bindings.codec_0, model_bindings.CONTEXT_0),
                fields=(
                    FieldPlan('name', 'string'),
                    FieldPlan('count', 'integer'),
                    FieldPlan('labels', 'string', repeated=True),
                ),
                additional=FieldPlan('', 'string'),
            ),
        ),
        default='application/x-www-form-urlencoded',
        required=True,
    ),
)

OPERATION_1: Final[OperationPlan[SubmitProfileResponse, SubmitProfileErrorData]] = OperationPlan(
    operation_id='submitProfile',
    method='POST',
    path='/profiles',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), SubmitProfileHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(
                media_type='multipart/form-data',
                kind='multipart',
                encoder=Encoder(model_bindings.codec_2, model_bindings.CONTEXT_2),
            ),
        ),
        default='multipart/form-data',
        required=True,
    ),
)

OPERATION_2: Final[OperationPlan[ReadProfileResponse, ReadProfileErrorData]] = OperationPlan(
    operation_id='readProfile',
    method='GET',
    path='/profiles',
    servers=_SERVERS_0,
    responses=ResponseDecoder(
        (
            model_branch(
                '200',
                'multipart/form-data',
                'multipart',
                model_bindings.codec_3, model_bindings.CONTEXT_3,
                parts=(
                    PartPlan('name', 'string'),
                    PartPlan('age', 'integer'),
                    PartPlan('score', 'number'),
                    PartPlan('ratio', 'number'),
                    PartPlan('active', 'boolean'),
                    PartPlan('tags', 'string', repeated=True),
                    PartPlan('address', 'json'),
                ),
                additional_part=PartPlan('', 'integer'),
            ),
        ),
        (),
        ReadProfileHTTPError,
    ),
)

OPERATION_3: Final[OperationPlan[SubmitAnythingResponse, SubmitAnythingErrorData]] = OperationPlan(
    operation_id='submitAnything',
    method='POST',
    path='/anything',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), SubmitAnythingHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(
                media_type='multipart/form-data',
                kind='multipart',
                encoder=Encoder(model_bindings.codec_4, model_bindings.CONTEXT_4),
            ),
        ),
        default='multipart/form-data',
        required=True,
    ),
)

OPERATION_4: Final[OperationPlan[SubmitPartsResponse, SubmitPartsErrorData]] = OperationPlan(
    operation_id='submitParts',
    method='POST',
    path='/attachments',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), SubmitPartsHTTPError),
    body=RequestBody(
        media=(BodyMedia(media_type='multipart/form-data', kind='multipart'),),
        default='multipart/form-data',
    ),
)

OPERATION_5: Final[OperationPlan[ReadPartsResponse, ReadPartsErrorData]] = OperationPlan(
    operation_id='readParts',
    method='GET',
    path='/attachments',
    servers=_SERVERS_0,
    responses=ResponseDecoder(
        (
            multipart_branch('200', 'multipart/mixed'),
            model_branch(
                '202',
                'multipart/form-data',
                'multipart',
                model_bindings.codec_5, model_bindings.CONTEXT_5,
                parts=(PartPlan('id', 'integer'),),
            ),
        ),
        (),
        ReadPartsHTTPError,
    ),
)

OPERATION_6: Final[OperationPlan[SubmitPairsResponse, SubmitPairsErrorData]] = OperationPlan(
    operation_id='submitPairs',
    method='POST',
    path='/pairs',
    servers=_SERVERS_0,
    responses=ResponseDecoder(
        (form_branch('200', 'application/x-www-form-urlencoded'),),
        (),
        SubmitPairsHTTPError,
    ),
    body=RequestBody(
        media=(BodyMedia(media_type='application/x-www-form-urlencoded', kind='form'),),
        default='application/x-www-form-urlencoded',
    ),
)

OPERATION_7: Final[OperationPlan[SubmitUploadResponse, SubmitUploadErrorData]] = OperationPlan(
    operation_id='submitUpload',
    method='POST',
    path='/uploads',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), SubmitUploadHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(
                media_type='multipart/form-data',
                kind='multipart',
                parts=(
                    PartPlan(
                        'id',
                        encoder=Encoder(model_bindings.codec_12, model_bindings.CONTEXT_12),
                    ),
                    PartPlan(
                        'title',
                        required=True,
                        encoder=Encoder(model_bindings.codec_13, model_bindings.CONTEXT_13),
                    ),
                    PartPlan(
                        'count',
                        encoder=Encoder(model_bindings.codec_14, model_bindings.CONTEXT_14),
                    ),
                    PartPlan(
                        'tags',
                        repeated=True,
                        encoder=Encoder(model_bindings.codec_15, model_bindings.CONTEXT_15),
                    ),
                    PartPlan(
                        'meta',
                        encoder=Encoder(model_bindings.codec_16, model_bindings.CONTEXT_16),
                    ),
                    PartPlan('photo', file=True, required=True),
                    PartPlan('pages', repeated=True, file=True),
                ),
                additional_part=PartPlan(
                    '',
                    encoder=Encoder(model_bindings.codec_17, model_bindings.CONTEXT_17),
                ),
            ),
        ),
        default='multipart/form-data',
        required=True,
    ),
)

OPERATION_8: Final[OperationPlan[ReadUploadResponse, ReadUploadErrorData]] = OperationPlan(
    operation_id='readUpload',
    method='GET',
    path='/uploads',
    servers=_SERVERS_0,
    responses=ResponseDecoder(
        (
            parts_branch(
                '200',
                'multipart/form-data',
                PartsReader[str | int | _dcg_type_0 | DecodedValue[_dcg_type_1] | bytes](
                    (
                        value_part(
                            'title',
                            'string',
                            native_value(model_bindings.codec_18, model_bindings.CONTEXT_18),
                            required=True,
                        ),
                        value_part(
                            'count',
                            'integer',
                            native_value(model_bindings.codec_19, model_bindings.CONTEXT_19),
                        ),
                        value_part(
                            'tags',
                            'string',
                            native_value(model_bindings.codec_20, model_bindings.CONTEXT_20),
                            repeated=True,
                        ),
                        value_part(
                            'meta',
                            'json',
                            native_value(model_bindings.codec_21, model_bindings.CONTEXT_21),
                        ),
                        value_part(
                            'draft',
                            'json',
                            envelope_value(model_bindings.codec_22, model_bindings.CONTEXT_22),
                        ),
                        file_part('photo', required=True),
                        file_part('pages', repeated=True),
                        value_part(
                            'secret',
                            'string',
                            native_value(model_bindings.codec_23, model_bindings.CONTEXT_23),
                        ),
                    ),
                    additional=value_part(
                        '',
                        'integer',
                        native_value(model_bindings.codec_24, model_bindings.CONTEXT_24),
                    ),
                ),
            ),
            parts_branch(
                '201',
                'multipart/form-data',
                PartsReader[str | bytes](
                    (
                        value_part(
                            'note',
                            'string',
                            native_value(model_bindings.codec_25, model_bindings.CONTEXT_25),
                        ),
                    ),
                    additional=file_part(''),
                ),
            ),
            parts_branch(
                '202',
                'multipart/form-data',
                PartsReader[bytes](
                    (file_part('photo'),),
                    additional=file_part('', repeated=True),
                ),
            ),
            parts_branch(
                '203',
                'multipart/form-data',
                PartsReader[bytes]((file_part('photo'),)),
            ),
        ),
        (),
        ReadUploadHTTPError,
    ),
)

OPERATION_9: Final[OperationPlan[SubmitAvatarResponse, SubmitAvatarErrorData]] = OperationPlan(
    operation_id='submitAvatar',
    method='POST',
    path='/avatars',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), SubmitAvatarHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(
                media_type='multipart/form-data',
                kind='multipart',
                parts=(
                    PartPlan(
                        'caption',
                        encoder=Encoder(model_bindings.codec_26, model_bindings.CONTEXT_26),
                    ),
                    PartPlan('avatar', file=True),
                ),
                additional_part=PartPlan(''),
            ),
            BodyMedia(
                media_type='application/json',
                kind='json',
                encoder=Encoder(model_bindings.codec_6, model_bindings.CONTEXT_6),
            ),
        ),
    ),
)

OPERATION_10: Final[OperationPlan[SubmitScansResponse, SubmitScansErrorData]] = OperationPlan(
    operation_id='submitScans',
    method='POST',
    path='/scans',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), SubmitScansHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(
                media_type='multipart/form-data',
                kind='multipart',
                parts=(
                    PartPlan(
                        'note',
                        encoder=Encoder(model_bindings.codec_27, model_bindings.CONTEXT_27),
                    ),
                ),
                additional_part=PartPlan('', file=True),
            ),
        ),
        default='multipart/form-data',
    ),
)

OPERATION_11: Final[OperationPlan[SubmitPhotosResponse, SubmitPhotosErrorData]] = OperationPlan(
    operation_id='submitPhotos',
    method='POST',
    path='/photos',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), SubmitPhotosHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(
                media_type='multipart/form-data',
                kind='multipart',
                parts=(PartPlan('photo', file=True, required=True),),
            ),
        ),
        default='multipart/form-data',
        required=True,
    ),
)

OPERATION_12: Final[OperationPlan[SubmitLabelsResponse, SubmitLabelsErrorData]] = OperationPlan(
    operation_id='submitLabels',
    method='POST',
    path='/labels',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), SubmitLabelsHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(
                media_type='multipart/form-data',
                kind='multipart',
                parts=(PartPlan('sheet', file=True),),
                additional_part=PartPlan(
                    '',
                    encoder=Encoder(model_bindings.codec_28, model_bindings.CONTEXT_28),
                ),
            ),
        ),
        default='multipart/form-data',
        required=True,
    ),
)

OPERATION_13: Final[OperationPlan[StoreDocumentResponse, StoreDocumentErrorData]] = OperationPlan(
    operation_id='storeDocument',
    method='POST',
    path='/documents',
    servers=_SERVERS_0,
    responses=ResponseDecoder(
        (
            wire_branch('200', 'application/json'),
            text_branch('200', 'text/plain'),
            empty_branch('202'),
            envelope_branch(
                '3XX',
                'application/json',
                'json',
                model_bindings.codec_8, model_bindings.CONTEXT_8,
            ),
        ),
        (text_branch('5XX', 'text/plain'),),
        StoreDocumentHTTPError,
        success_statuses=frozenset({302}),
    ),
    body=RequestBody(
        media=(
            BodyMedia(media_type='application/json', kind='json'),
            BodyMedia(media_type='text/plain; charset=utf-16', kind='text'),
            BodyMedia(
                media_type='application/vnd.api+json',
                kind='json',
                encoder=Encoder(model_bindings.codec_7, model_bindings.CONTEXT_7),
            ),
        ),
        default='application/json',
        required=True,
    ),
)

OPERATION_14: Final[OperationPlan[ReadDocumentResponse, ReadDocumentErrorData]] = OperationPlan(
    operation_id='readDocument',
    method='GET',
    path='/documents/{id}',
    servers=_SERVERS_0,
    responses=ResponseDecoder(
        (
            envelope_branch(
                '200',
                'application/vnd.api+json',
                'json',
                model_bindings.codec_10, model_bindings.CONTEXT_10,
            ),
        ),
        (),
        ReadDocumentHTTPError,
    ),
    parameters=(
        ParameterSpec(
            plan=ParameterPlan(
                location='path',
                name='id',
                required=True,
                content_media_type='application/json',
            ),
            encoder=Encoder(model_bindings.codec_9, model_bindings.CONTEXT_9),
        ),
        ParameterSpec(
            plan=ParameterPlan(
                location='query',
                name='filter',
                content_media_type='application/json',
            ),
        ),
        ParameterSpec(
            plan=ParameterPlan(
                location='header',
                name='X-Mode',
                content_media_type='text/plain',
            ),
        ),
    ),
)

OPERATION_15: Final[OperationPlan[StoreNoteResponse, StoreNoteErrorData]] = OperationPlan(
    operation_id='storeNote',
    method='POST',
    path='/notes',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), StoreNoteHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(media_type='application/json', kind='json'),
            BodyMedia(media_type='application/vnd.note+json', kind='json'),
        ),
        required=True,
    ),
)

OPERATION_16: Final[OperationPlan[ReplaceNoteResponse, ReplaceNoteErrorData]] = OperationPlan(
    operation_id='replaceNote',
    method='PUT',
    path='/notes',
    servers=_SERVERS_0,
    responses=ResponseDecoder((empty_branch('204'),), (), ReplaceNoteHTTPError),
    body=RequestBody(
        media=(
            BodyMedia(media_type='application/json', kind='json'),
            BodyMedia(media_type='text/plain', kind='text'),
        ),
    ),
)
